- lib/Layer/Layer.js
Pruning dead code. Once upon a time componentDidUpdate referred to
providing focus to a modal, but even on initial import the actual
implementation was commented out (see
ddd91a0e71cf7c836eb72e3ce038e5533b90aac8).
> Lint: Layer. See STCOM-21.

- lib/Button/Button.css
"+ New" buttons in a pane header need a right-margin.
> Add style for new-of-type button. See UIU-164

- lib/Checkbox/Checkbox.js
- lib/DropdownMenu/DropdownMenu.js
- lib/RadioButton/RadioButton.js
- util/separateComponentProps.js
In some cases props passed to a component are then pushed down to a
child element and we would have to filter out irrelevant props with code
like this:
const { junk1, junk2, junk3, ...inputProps } = this.props;
<input type="checkbox" {...inputProps} />
The junkX variables are created solely for the purpose of pulling those
keys out of inputProps, which causes ESLint to complain about unused
variables.
The function separateComponentProps provides a better way of handling
this situation without creating unused variables.
> Lint: separate component, element props. See STCOM-21

- lib/MultiColumnList/MCLRenderer.js
Curiously, the column map wasn't being used to handle the display
of column headers.
> use column map to map header values. See UIU-176

- index.js
`lib/index.js` currently re-exports the `default` export from several packages as its own. However, every JS module can only have at most a single `default` export. This was giving rise to errors like:
```
ERROR in ../stripes-components/index.js
Module build failed: SyntaxError: Only one default export allowed per module. (3:8)
1 | /*form elements*/
2 | export {default} from './lib/Button';
> 3 | export {default} from './lib/Checkbox';
|         ^
```
This change re-exports each referenced component module as a named
export so that you can import them by name. E.g.
```js
import { Button } from '@folio/stripes-components';
```
> Note: `InputList` does not appear to be in the codebase anymore, so
> that export was removed.
> Fix compilation errors in index.js

- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
By default cells in an MCL hide any overflow, but a cell which contains
a dropdown list, which will extends beyond the borders, needs to show
that overflow.
> support columnOverflow prop. Refs UIU-128

- CHANGELOG.md
- lib/TabButton/TabButton.css
- lib/TabButton/TabButton.js
- lib/TabButton/index.js
A UI element for navigation on a tab-like interface where each tab represents a different filter applied to a list of data. See the screen shot for https://issues.folio.org/browse/UIU-128; this is used to implement the "Open Loans" and "Closed Loans" filters.
> Uiu 128 tab button

- lib/Select/Select.js
- lib/structures/AddressFieldGroup/AddressEdit/AddressEdit.js
- lib/structures/AddressFieldGroup/AddressList/AddressList.js
- lib/structures/AddressFieldGroup/AddressView/AddressView.js
- lib/structures/EditableList/EditableList.js
- lib/structures/EditableList/EditableListForm.js
- lib/structures/EditableList/ItemEdit.js
- lib/structures/EditableList/ItemView.js
Removes this warning:
`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see` https://fb.me/prop-types-docs
> Import PropTypes directly from package, not React

- lib/Pane/Pane.js
Whenever a Pane component is mounted, it installs an animation callback to make sure that it syncs its `contentMinWidth` property with the actual content width of the frame as rendered. However, after the Pane component is unmounted, the callback remains installed and attempts to `setState` the component which is no longer present. It repeatedly spews Errors like the following to the console.
```
ERROR: 'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Pane component.'
ERROR: 'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the …
```
> Teardown animation callbacks on Pane unmount.

- CHANGELOG.md
- lib/structures/Notes/NoteRenderer.js
- lib/structures/Notes/Notes.js
- lib/structures/Notes/NotesForm.js
Prep for refactoring the business logic of `<Notes>` into a separate repository, and a bug fix: re-render the new-note-form with updated props when the notes pane is left open and the selected-item, which sets the note's `link` prop, changes.
> Stutilnote 2 refactor notes

- lib/TextField/TextField.js
use of separateComponentProps() helps to clean up code by not littering
it with a bunch of local variables that exist for no other reason than
to pull out a key that would otherwise be left in a destructured object.
But it does have the side effect of not passing along key-value pairs to
the nested component if that key is defined on the parent component.
"id" is such a key here. So this commit fixes that, restoring the "id"
attribute on the generated component.
> restore "id" to the generated component

- .eslintrc
- lib/Accordion/Accordion.js
- lib/AuthorityList/AuthorityList.js
- lib/Datepicker/Calendar.js
- lib/MultiColumnList/MCLRenderer.js
- lib/RadioButton/RadioButton.js
- lib/Select/Select.js
- lib/Settings/Settings.js
- lib/TextArea/TextArea.js
- lib/TextField/TextField.js
- lib/structures/AddressFieldGroup/AddressEdit/AddressEdit.js
- lib/structures/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
- lib/structures/AddressFieldGroup/AddressList/AddressList.js
- lib/structures/AddressFieldGroup/AddressView/AddressView.js
- lib/structures/EditableList/EditableListForm.js
- package.json
I noticed on our builds of `thefrontside/ui-eholdings` that we were still getting `WARN: 'Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs'`, even though I thought it had been resolved with https://github.com/folio-org/stripes-components/pull/45.
It turns out I missed one - in searching for `React.PropTypes`, I didn't notice an instance of `import React, { PropTypes } from 'react';`.
That would've been caught by the ESLint `react/no-deprecated` rule provided as part of `eslint-config-airbnb`, but the error was not being thrown. I upgraded all the `eslint`-related packages, and …
> Upgrade ESLint and fix broken rules

- CHANGELOG.md
- lib/Button/Button.js
- lib/TextField/TextField.js
In an effort to appease ESLint by removing unused variables, we changed
the way some props destined for a child component were pulled from
`props` by using `separateComponentProps()` but this add some unintended
consequences. Namely, by requiring that those props be explicitly named,
we prevented tools like redux-form from implicitly handling their own
props on the components they managed. IOW, things broke. Things broke
BADLY.
Replacing the naively-conceived `separateComponentProps()` with
`omitProps()` feels kludgy since we're back to hard-coding a list of
props to ignore instead of but since doing it automatically didn't
actually work, the brute-force approach wins for now.
> push all props down to generated components. Fixes STCOM-84

- lib/structures/AddressFieldGroup/AddressList/AddressList.js
Enables UIU-242. Uses the `canEdit` prop to determine if the "Add Address" button appears.
> use canEdit prop to display add button

- lib/IfPermission/readme.md
Documentation for cases where an 'else' case is needed for <IfPermissions>. (use `hasPerm()` directly.)
> STCOM-93 add advanced conditional rendering section to readme

- lib/EntrySelector/EntrySelector.js
Otherwise items with no name are invisible and unclickable.
> <EntrySelector> uses default name "[unnamed]"

- CHANGELOG.md
- lib/Callout/Callout.css
- lib/Callout/Callout.js
- lib/Callout/CalloutElement.js
- lib/Callout/index.js
- lib/Callout/readme.md
- lib/Modal/Modal.css
- lib/Modal/Modal.js
- lib/structures/ConfirmationModal/ConfirmationModal.js
- lib/structures/ConfirmationModal/index.js
- lib/structures/ConfirmationModal/readme.md
- package.json
This contains 2 significant additions to our toolset.
A) An alert pop-up component (`<Callout>`) that's super-easy to use and nicely accessible.
B) A reusable confirmation modal component for all of those 'Yes' or 'No' (or 'Submit' or 'Cancel') scenarios.
Submitted for approval!
> STCOM 66 delete confirmation

- lib/Layer/Layer.js
- package.json
When I tried to pass `document.body` or `document.getElementById('ModuleContainer')` as a container to the `Layer` I would get:
`warning.js:36 Warning: Failed prop type: Invalid prop `container` supplied to `Layer`, expected a ReactNode.`
> Relax Layer's propType for container. Fixes STCOM-98

- CHANGELOG.md
- lib/Settings/Settings.js
This PR moves `stripes.connect` from `render` into `constructor` so the connection happens only once for each component.
> Fix connect in Settings. Fixes STCOM-99

- CHANGELOG.md
- lib/Layout/Layout.css
- lib/structures/AddressFieldGroup/AddressEdit/AddressEdit.css
- lib/structures/AddressFieldGroup/AddressEdit/AddressEditList.js
- lib/structures/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
- lib/structures/AddressFieldGroup/AddressList/AddressList.js
- lib/structures/AddressFieldGroup/AddressView/AddressView.js
A few aesthetic and functional changes to Address Fieldgroup:
- Fields are re-arranged. AddressType is displayed first. Country displayed last.
- Delete action represented as icon.
- Primary represented as radio button.
- AddressType only displays options that have not been previously used in the form.
Field re-arrangement was applied to both the edit and read-only views.
> UIU-260 Address Fieldgroup Update

- CHANGELOG.md
- util/transitionToParams.js
> transitionToParams uses queryString.stringify instead of by-hand gluing

- CHANGELOG.md
- lib/Settings/Settings.js
Fix defaultRoute in Settings when pages is not sorted by label. Fixes STCOM-113.
> Fix defaultRoute in Settings when pages is not sorted. Fixes STCOM-113.

- lib/Pane/Pane.js
- lib/Paneset/Paneset.js
Fixes a symptom called when multiple Panes are unmounted at once. One of them can leave its ghost registered with Paneset and resizing happens under the belief that the dismissed Pane is still there, leaving a blank space. This fixes STSMACOM-17
> Account for removal of multiple panes in Paneset.

- CHANGELOG.md
- lib/Settings/Settings.js
You gotta keep 'em separated
Like the latest data
Like a diff'rent `entry`
The keys are unique on their way to the table
Mapping values with the greatest of ease
The keys stake their own hashmap value
But if they share `resources` then it's curtains for you
If one key's label and the other's the same
They're gonna bash it up
Hey - man you got a copied key?
Take it out
You gotta keep 'em separated
> include dataKey in calls to connect. Fixes UICIRC-33

- .storybook/addons.js
- .storybook/config.js
- .storybook/webpack.config.js
- lib/Accordion/Accordion.stories.js
- lib/global.css
- package.json
"[Storybook](https://github.com/storybooks/storybook) is a development environment for UI components. It allows you to browse a component library, view the different states of each component, and interactively develop and test components." Storybook should make component development and styling a breeze, since each component can easily run in isolation.
We only set up a single story for the first component in alpha order, `Accordion`. We also pulled in the `storybook-readme` addon to show off the READMEs already present in `stripes-components`.
`yarn storybook` will spin up the Storybook environment at [http://localhost:9001](http://localhost:9001).
For a component like the `Accordion` to render 100% visually styled in Storybook, it needs to know about styles previously defined globally …
> Set up Storybook development environment

- .eslintrc
- lib/Accordion/Accordion.stories.js
- lib/Modal/Modal.stories.js
- lib/TextField/TextField.stories.js
Storybook is currently a `devDependency` of `stripes-components`, since consuming applications don't need to pull in Storybook.
The `import/no-extraneous-dependencies` ESLint rule was breaking on `.stories.js` files that need to import pieces of Storybook, because Storybook is simply a `devDependency`. We were disabling the rule on lines that violated it, but that won't scale well.
This `.eslintrc` change will affect files that end in `.stories.js`:
```
"import/no-extraneous-dependencies": ["error", {
"devDependencies": ["**/*.stories.js"]
}]
```
Any file that matches that pattern will not complain about dependencies anymore. All other files will continue to lint the same as before.
> Adjust devDependency linting for .stories.js files

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/index.js
Works with anointed resource instead of component state.
Fixes STCOM-148.
> Add `handleFilterChange` method for FilterGroups

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/index.js
This is like `initialFilterState`, but doesn't need the configuraton
object.
Also, modify handleFilterChange to use this rather then duplicating
its code.
Fixes STCOM-147.
> Add `filterState` method for FilterGroups

- lib/MultiColumnList/MCLRenderer.css
Updated paddings/margins to achieve 15px padding from edge to text (in connection with the padContent=false prop on Pane).
The padContent prop should be set on all panes that that has MultiColumnList as direct child. I will submit a pull request for stripes-smart-components once this, #123  and #125 is merged.
> Updated paddings/margins on MCL

- lib/FilterPaneSearch/FilterPaneSearch.js
Really weird new console warning from Stripes:
```
Warning: Failed prop type: Invalid prop `icon` of value `right-double-chevron-bold` supplied to `Icon`, expected one of ["info","plus-sign","validation-check","validation-error","default","clearX","closeX","calendar","trashBin","comment","bookmark","search","duplicate","edit","hollowX","archive","forward-arrow","back-arrow","down-arrow","up-arrow","down-caret","up-caret","down-triangle","up-triangle","right-double-chevron","left-double-chevron","eye-open","eye-close","end-mark","ellipsis","spinner-ellipsis"].
in Icon (created by FilterPaneSearch)
in FilterPaneSearch (created by SearchAndSort)
in header (created by PaneHeader)
```
But `<FilterPaneSearch>` has been asking for this very icon since commit …
> Use valid icon-name

- .eslintrc
- package.json
I noticed `@storybook/addon-actions` and `@storybook/addon-knobs` were being pulled in as dependencies of `ui-eholdings`. I assume they were moved because ESLint was throwing a `import/no-extraneous-dependencies` warning, but that rule is now ignored for all story files. We can move them back to simply being `devDependencies`.
> Move storybook addons to devDependencies

- lib/Datepicker/Datepicker.js
Errored datepicker fields were showing two clear icons.
> Datepickers should only show a single clear icon

- CHANGELOG.md
- util/makeQueryFunction.js
Functions made by `makeQueryFunction` now operate as follos: if the `qfield` query-parameter is defined, it is interpreted as the name of the _only_ field to search, superseding the queryTemplate that was passed in when the function was created.
This allows us to support field-specific searching.
Fixes STCOM-172.
> makeQueryFunction supports the "qfield" parameter

- CHANGELOG.md
- util/makeQueryFunction.js
> `makeQueryFunction` supports relation-modifiers in the `qindex` parameter

- CHANGELOG.md
- lib/Select/Select.js
- lib/Select/readme.md
Allows for `<Select>` dropdowns to have options greyed out via a 'disabled' property supplied in the `dataOptions` prop such as:
```
<Select
dataOptions={[
{value: "Y", label: "Yes"},
{value: "N", label: "No"},
{value: "M", label: "Maybe", disabled: true}
]} 
/>
```
> Stcom 173 disabled select options

- lib/Accordion/Accordion.css
- lib/Accordion/Accordion.js
- lib/Badge/Badge.css
- lib/Badge/Badge.js
- lib/Callout/Callout.css
- lib/Callout/Callout.js
- lib/Checkbox/Checkbox.css
- lib/Checkbox/Checkbox.js
- lib/Datepicker/Calendar.css
- lib/Datepicker/Calendar.js
- lib/Icon/Icon.css
- lib/Icon/Icon.js
- lib/List/List.css
- lib/List/List.js
- lib/SegmentedControl/SegmentedControl.css
- lib/SegmentedControl/SegmentedControl.js
- lib/Select/Select.css
- lib/Select/Select.js
- lib/TextArea/TextArea.css
- lib/TextArea/TextArea.js
- lib/TextField/TextField.css
- lib/TextField/TextField.js
- lib/structures/AddressFieldGroup/AddressEdit/AddressEdit.css
- lib/structures/AddressFieldGroup/AddressEdit/AddressEditList.js
When debugging markup and writing tests for the browser, it'd be more helpful to have explicit class names for components, instead of `.root--${MODULE_HASH}`.
Many `stripes-components` already follow this pattern.
> Give explicit class names instead of .root

- lib/PaneHeader/PaneHeader.css
Pane headers that have a 44px-tall `IconButton` end up one pixel taller than pane headers that do not.
Because `box-sizing` is set to `border-box`, the `height` calculation includes the 1px border. Increasing the `min-height` to 45px accommodates both a 44px-tall button and the border.
> Increase pane header min-height to include border

- lib/Accordion/Accordion.css
- lib/Accordion/headers/FilterAccordionHeader.js
- lib/Button/Button.css
- lib/Button/Button.js
- lib/Button/readme/general.md
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/index.js
Implements the first part of [STCOM-164](https://issues.folio.org/browse/STCOM-164)
- Added a `Reset All` button at the top of the `FilterGroups` component which clears all existing filters.
- Added a "clear" X to the right of every `FilterAccordionHeader` which clears the filters in that FilterGroup.
- This requires `SearchAndSort` to be used by the module. Decided against backporting this functionality to modules that don't use SAS yet per discussion on the JIRA.
- There's a dependent change in SAS that'll have a PR in stripes-smart-components as well.
Be as pedantic and overcorrective as you want with this PR since it's my first. If I didn't catch some corner-case or idiosyncrasy or my style doesn't match I'd love to know. 👍 
Reviewers assigned based on Github suggestions or people who …
> STCOM-164: Add buttons to clear filters

- lib/IconButton/IconButton.js
The short-circuiting of the expression will still result in the first part of the expression being rendered, so any falsey value gets rendered to the page.
Note that if we didn't want to show a badge when the count was 0, then the logic would still be off since the "0" gets rendered out as DOM text.
> IconButton: Fixed bug where a badgeCount of 0 wouldn't render a Badge

- lib/global.css
Since we have a place for a limited set of global styles, the color of `<a>`s makes sense to define on the global level.
- Should there be a different hover state? Background? Underline? Darken the primary color? Lighten the primary color?
- Should there be a `:visited` state? My inclination is that coloring visited links purple (or any other type of indication it's been visited) is more detrimental than useful in an application like FOLIO. Other opinions welcome.
> Establish global primary link color

- lib/structures/RepeatableField/FieldRow.js
- lib/structures/RepeatableField/RepeatableField.js
- lib/structures/RepeatableField/readme.md
Bugfix to correctly apply a custom id to `<RepeatableField>`'s 'add' button.
> STCOM-187 `<RepeatableField>` `addButtonId` prop

- docs/CSSinStripes.md
- lib/Button/Button.css
- lib/Dropdown/Dropdown.css
- lib/DropdownMenu/DropdownMenu.css
- lib/Modal/Modal.css
- lib/Pane/Pane.css
- lib/Paneset/Paneset.css
- lib/Select/Select.css
- lib/TextField/TextField.css
- lib/sharedStyles/form.css
- lib/variables.css
Justification added to `CSSinStripes.md`:
`stripes-components` provides [pre-set breakpoints](../lib/variables.css) that you can use to adjust styles at different browser window widths.
```
@media (--mediumUp) {
.button {
height: 2em;
}
}
```
Use `min-width` breakpoints like `smallUp`, `mediumUp`, and `largeUp` when possible. There are `max-width` breakpoints available, but the cases for their use should be rare. Leaning on `min-width` promotes a mobile-first CSS workflow, where the narrowest screen size is the default. Layout can gradually be added as the width increases with breakpoints like `--mediumUp` and `--largeUp`.
This:
```
x ≥ 321px, x ≥ 641px, x ≥ 1025px, x ≥ 1441px
```
is easier to debug and reason about than this:
```
x ≤ 640px, 641px ≤ x ≤ 1024px, 1025px ≤ x < 1440px, x ≥ …
```
> Use min-width media queries instead of max-width

- lib/Pane/Pane.css
All `Pane`s have a `border-right`. The rightmost `Pane` (in LTR languages) doesn't need a `border-right`.
[`:last-child`](https://developer.mozilla.org/en-US/docs/Web/CSS/:last-child)
> Do not show right border for final Pane in Paneset

- lib/MultiColumnList/MCLRenderer.js
- Fixes issue with <MCL> not filling the entire height of large screens with data.
- Sets id's on column headers.
- Checks for presense of 'onNeedMoreData' callback before calling.
> MCL Updates - STCOM-29, STCOM-74

- lib/FilterGroups/FilterGroups.js
We need the button to be located above the SearchField component which is above the filters. 
Since it doesn't make much sense to start shoving that component and the functionality into the FilterGroups component, SearchAndSort now instantiates the SearchField component and the "Reset all" button.
> STCOM-164: Removed "Reset all" button from the FilterGroups component

- lib/Datepicker/Calendar.js
- lib/Datepicker/Datepicker.js
ITPR, supplying an `id` prop to <Datepicker> will apply it as a suffix to sub-components that are used to operate the calendar widget and clear the text.
If no prop is supplied, the id suffix will be automatically generated via `lodash/uniqueId` (currently workable solution for multiple instances on page)
> STCOM-192 added ids to `<Datepicker>` sub-components based on id prop

- lib/Dropdown/Dropdown.js
- lib/Icon/Icon.js
- package.json
- util/isStatefulComponent.js
- Move to React as a peer dependency.
- React 16 (rightly) complains about setting a ref on a functional component so I changed `<Icon>` to be a class and added a helper function to introspect where that seemed like a better solution like in `<Dropdown>`.
> Upgrade to React 16

- lib/Button/Button.css
- lib/Button/Button.js
- lib/Button/readme/general.md
- lib/Button/readme/styles.md
- lib/Button/stories/general.js
- lib/Button/stories/styles.js
- lib/variables.css
The FOLIO button styles available take a very similar approach to [Bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/) and [Foundation](https://foundation.zurb.com/sites/docs/button.html). That means there are a wide variety of styles available, but they are unprescriptive about use.
Weaknesses of the current strategy:
- Primary buttons (in solid blue) are the default if no specific style of button has been specified. That means there are frequently multiple primary buttons visible at the same time.
- Secondary buttons can be confused with a disabled state.
- Secondary buttons have a very similar visual weight to primary buttons. We're solely relying on color to distinguish between them.
- Hollow buttons don't have an explicit purpose.
Based on a session at the FOLIO Madrid …
> Modify default button style

- lib/TextField/TextField.js
Id's... tests need them. Having a good way for automated tests to clear the <Textfield> component regardless of how the devs have implemented the field is a good idea...
This PR also adds id's to the validation icons.
> supply generated id to clear button if none is supplied

- lib/AuthorityList/AuthorityList.js
Prevents EditableListForm from re-rendering before confirming success from the backend
> Prevents EditableListForm from re-rendering before confirming success

- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
This considers the presence of an `onHeaderClick` handler before assigning a 'clickable' class to the rendered column headers.
> Mcl clickable header style

- README.md
Update to the root readme that sets up use-case categories for components - meant to guide developers and designers on the instances where certain components can be useful.
> add component categories to root readme

- lib/SegmentedControl/SegmentedControl.js
After #209 Segmented control needed modification due to the removal of `hollow`. It now displays non-active buttons with the `default` class.
> updated rendered button styles for SegmentedControl

- .eslintrc
- CHANGELOG.md
- lib/Accordion/Accordion.stories.js
- lib/MultiColumnList/MCLRenderer.js
- package.json
MCL was sending a `ref` prop down to its rowFormatter - not good, as the formatter could be a functional component, in which case the ref would return null.
An additional lint tweak here as well: allow for `console.error` and `console.warn` but still bark at `console.log`.
> STCOM-202 remove unreliable tracking of focused row.

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- package.json
As a result, selecting all filters in a group now has no effect -- except for groups where `restrictWhenAllSelected` is true, where the old behaviour is retained.
Version patchlevel bumped (yielding 2.0.1) so we can depend on this new functionality in accordance with the recent document [Depending on unreleased features](https://github.com/folio-org/stripes-core/blob/master/doc/depending-on-unreleased-features.md). This is a test-case for the procedure described therein.
Fixes STCOM-204.
> Implement restrictWhenAllSelected group flag

- lib/TextField/TextField.js
Since type of a textfield can be either "text" or "number", proptype of its value can be either string or number. 
This resolves a JS console warning of the type below:
```warning.js:33 Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `TextField`, expected `string`.
in TextField
in Unknown (created by ConnectedField)
in ConnectedField (created by Connect(ConnectedField))
in Connect(ConnectedField) (created by Field)
in Field (created by CustomEmbargoForm)```
This warning occurs when redux form tries to pass value of type "number" to TextField which accepts only string
> Update textfield value proptypes to accept both string and number

- lib/AppIcon/AppIcon.js
- lib/AppIcon/readme.md
This update adds support for React Context in the AppIcon-component.
It relies on stripes being in context which allows it to check for the metadata-key to find icon(s) for an app specified by the "app"-prop.
**Usage:**
`<AppIcon app="users" />`
I also updated the readme with examples.
**Note:** I have preserved two other options of adding icons even though the context one will be the recommended. This is mainly because of some apps not being actual apps yet - such as "Settings". In this case I needed another way of passing the icon data down.
In the future we'll probably limit the options to only using the context part (assuming we don't decide to use another way of implementation).
I have been adding icons to various apps so that they are ready for this change. I will also submit a PR …
> Updating AppIcon to support context

- lib/AppIcon/AppIcon.js
- lib/AppIcon/readme.md
Adding iconKey from to use when you need another app icon than the default one.
Example: In Inventory we need to get an items-icon in some cases so you can do:
`<AppIcon app="inventory" iconKey="items" />`
> Updating AppIcon

- docs/Accessibility.md
- lib/Accordion/headers/DefaultAccordionHeader.js
- lib/Accordion/headers/FilterAccordionHeader.js
- lib/LayoutHeader/LayoutHeader.js
- lib/MetaSection/MetaAccordionHeader.js
- lib/Pane/Pane.js
- lib/PaneHeader/PaneHeader.js
- lib/structures/AddressFieldGroup/AddressList/AddressList.js
- lib/structures/AddressFieldGroup/AddressView/AddressView.js
As part of a headings/<section> overhaul to achieve a nice, accessible page outline, I found the culprit of the ugly and infamous: 
and struck it down.
Additionally, this PR touched heavily on the Accordion headers and Pane Headers, making them work in conjunction with the `<h1>` added to the main FOLIO header in the stripes-core PR #206 https://github.com/folio-org/stripes-core/pull/206
> STCOM-215 adjust heading levels and section tags - fix the H3 console error

- CHANGELOG.md
- lib/structures/SearchField/SearchField.js
> `<SearchForm>` omits placeholder if specified to be null

- CHANGELOG.md
- package.json
- util/makeQueryFunction.js
Fixes STCOM-219. Available from v2.0.2.
> Generalise `failIfNoQuery` argument to `makeQueryFunction`, now `failOnCondition`

- lib/structures/EditableList/EditableListForm.js
Resolves [STCOM-218](https://issues.folio.org/browse/STCOM-218)
The EditableList already had a validation function, but was not using it. This PR is disabling the 'create' button when the value is unchanged, in the process of being submitted, or the validation function returns a validation error.
> Added disabled property to EditableListForm's save button

- lib/Checkbox/Checkbox.js
[Fixing STCOM-175.](https://issues.folio.org/browse/STCOM-175)
Adding the `disabled` prop to `<Checkbox>` pulled it off of the props that get spread onto the `<checkbox>` so we now have to apply it explicitly.
> STCOM-175: Fixed bug when disabling filter checkboxes

- lib/Accordion/Accordion.css
- lib/Accordion/Accordion.js
- lib/Accordion/headers/FilterAccordionHeader.js
- lib/Checkbox/Checkbox.css
- lib/FilterGroups/FilterGroups.js
Disabled FilterGroups didn't have obvious styling to show they were disabled beyond the CheckBox itself. This adds background styling by adding a `disabled` prop to `<Accordion>`s themselves and CSS styles on that class.
Did it this way since we wanted both the header and `<FilterGroup>` styled and it'd let us just have the one set of rules. The ruleset is general enough to work for an Accordion in any parent that has a `major-padding` for its padding (like SearchAndSort).
Screenie:
> Added styling for disabled FilterGroups and Accordions

- CHANGELOG.md
- package.json
- util/makeQueryFunction.js
Fixes STCOM-225
Available from v2.0.3.
> Make `makeQueryFunction` robust to failed substitutions

- CHANGELOG.md
- package.json
- util/makeQueryFunction.js
Fixes STCOM-226.
Available from v2.0.4.
> `makeQueryFunction` favours parameter-access via the anointed resource rather than the URL

- CHANGELOG.md
- lib/Checkbox/Checkbox.js
- lib/FilterGroups/readme.md
- package.json
Fixes STCOM-227.
Available from 2.0.5.
> In `<Checkbox>`, nest HTML checkboxes inside labels instead of associating the labels by ID

- CHANGELOG.md
- lib/Checkbox/Checkbox.css
- package.json
Prior to this change, the UI element was 9999 pixels offscreen, so there must have been some additional CSS/JS magic going on here prior to #270 (See [UIU-430](https://issues.folio.org/browse/UIU-430)). 
Tagging @rasmuswoelk in case there is any restorative CSS work to make this pretty again now that we've made it functional again.
> restore checkbox position. Refs STCOM-227

- CHANGELOG.md
- lib/structures/EditableList/EditableListForm.js
- lib/structures/EditableList/readme.md
- package.json
- The existing `actionSuppressors` props allows the hiding of Edit and Delete actions buttons but sometimes more fine control of the buttons is necessary.
- E.g., now you can set the `disabled` or `title` attributes on the action buttons depending on the item being rendered.
- The prop type of actionProps is the same as actionSuppressors: an object of callbacks per action type.
> UIU-431: Added actionProps prop to EditableListForm

- lib/KeyValue/KeyValue.js
- lib/KeyValue/readme.md
- lib/KeyValue/stories/BasicUsage.js
Over six months ago in `ui-eholdings`, we made a fork of the `KeyValue` component to accept a child node for the "value," instead of a `value` prop.
Like this:
```
<KeyValue label="Instruments">
<span>Vocals guitar</span>
</KeyValue>
```
This makes that child-rendering pattern available for `KeyValue`. The change is backwards-compatible - the `value` prop can still be passed in before, as either a string or node.
If there are children and a `value` prop, the children are rendered and the `value` prop is ignored.
I removed the unused `kvValue` class.
- Replace the `KeyValueLabel` component in `ui-eholdings` with the `KeyValue` from `stripes-components`.
> Render children passed to KeyValue component

- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Timepicker/Timepicker.js
- lib/Timepicker/readme.md
Creates a prop for pass-throughs on Datepicker and Timepicker: passThroughValue - this is used for passing through a string like 'today' or 'now' to be interpreted and adjusted at the time of submission. Doing this as a prop will allow for it to be localized.
> Timepicker pass-through

- lib/Datepicker/Datepicker.js
Applied `passThroughValue` behavior for non-redux-form fields, and fixed issue with 'invalid date' appearing on form reset when a `passThroughValue` is employed.
> Datepicker - Fix for passThroughValue behavior on form reset

- lib/Timepicker/TimeDropdown.js
Before: time picker dropdown would accept values 0-99 for the hour field in 24hr mode. 
After: If input hours is greater that 23, it is automatically set to 23.
> Limit timepicker range for 24h

- CHANGELOG.md
Escape angle brackets in Markdown 
Otherwise "`<Foo>`" names are rendered invisible.
> FOLIO-398 doc tweaks 15

- lib/structures/EditableList/EditableListForm.js
Converting the buttons used to `<IconButton>`s per @rasmuswoelk suggestion on [STCOM-229](https://issues.folio.org/browse/STCOM-229). 
Note that STCOM-229 is still valid, and `<IconButton>` does not have disabled styles either. However, because of a change from UX, we won't be disabling the buttons in `<ControlledVocab>` so it's not _as_ pressing an issue.
> EditableListForm: Changed action buttons use IconButton

- index.js
Per conversation at https://github.com/folio-org/ui-eholdings/pull/295#discussion_r176257629, we'd rather do:
```
import {
Button,
Icon,
IconButton
} from '@folio/stripes-components';
```
than
```
import Button from '@folio/stripes-components/lib/Button';
import Icon from '@folio/stripes-components/lib/Icon';
import IconButton from '@folio/stripes-components/lib/IconButton';
```
... but the list of exports in `index.js` is out of date. I just added the components lacking to have `ui-eholdings` use the more elegant imports, but there are plenty more components in the library not being exported. I'll make a JIRA issue to make sure the rest of the components get added to the index.
As future components get added to the library, we should make sure they get added to `index.js`.
> STCOM-238 Update list of exports

- lib/Settings/Settings.css
- lib/Settings/Settings.js
The `Settings` component was unusable on narrow screens. The UX pattern was such that if you selected a module in the leftmost pane, you'd be taken directly to the first item in that module's subnav, with no way to ever access the subnav.
Groundwork for https://issues.folio.org/browse/UIEH-212
Adjusting for a narrow screen meant several changes:
- Assuming the first link in the list is where the user wants to go means the subnav won't appear on narrow screens. The automatic selection of the first nav item has been removed.
- There's now a back button in the `firstMenu` of the pane containing the module's settings pages.
- To get around the brittle logic of `activeLink` (makes some assumptions about url structure), consumers of the `Settings` component can now pass in an `activeLink` prop. …
> UIEH-212 Make Settings component responsive

- index.js
Encouraging
```
import { 
Button, 
Icon, 
IconButton 
} from '@folio/stripes-components';
```
over
```
import Button from '@folio/stripes-components/lib/Button';
import Icon from '@folio/stripes-components/lib/Icon';
import IconButton from '@folio/stripes-components/lib/IconButton';
```
Finishes https://issues.folio.org/browse/STCOM-238
> STCOM-238 Update exports to include all components

- lib/Popover/Popover.css
This CSS leaked into the global scope, causing unexpected margin/padding side effects for lots of other paragraphs.
> Locally scope Popover paragraph CSS

- lib/PaneHeader/PaneHeader.css
- lib/PaneHeader/PaneHeader.js
Resolves https://issues.folio.org/browse/STCOM-243
Pane titles were occasionally getting rendered with incorrect CSS:
The `PaneHeader` component was trying to pass some of its own styles to a `Headline` component. The order of those styles in the CSS bundle was inconsistent. The `paneTitle` CSS overrode most of what `Headline` was giving anyway, so the simplest solution was to just use a raw `<h2>`. The DOM output is identical to the previous version.
> STCOM-243 Fix pane title CSS ordering bug

- lib/global.css
Raises dropdowns to the topmost layer.
> UIEH-130 Raise tethers up to topmost layer

- lib/MultiColumnList/MCLRenderer.js
In certain scenarios, the data provided to the MCLRenderer during the process of several re-renders can get it into some trouble without these sanity checks. For example, the amount of items to render will momentarily become NaN since we get a 0 averageRowHeight. 
This is part of the fixes for UIU-466
> MCLRenderer: Added safety checks

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/readme.md
- package.json
- util/makeQueryFunction.js
Allow filters to have hidden configuration values. For example, suppose
a filter group "species" existed and the query should *always* include
humans and allow the user to choose whether Ewok, Jawa, or Wookie
members should also be included in the search. Ewok, Jawa, and Wookie
would be included in the "values" array of the config element with
name: "species" and Human would be included in the array of the
hiddenConfig element keyed by "species".
Refs [UIU-400](https://issues.folio.org/browse/UIU-400)
> add hidden filter config. Refs UIU-400

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
Added in the prop `ignoreLocalOffset`. When set to true, this props helps to parse the dates passed in from the server in UTC and display dates like the birthdates constant irrespective of the tenant level timezone setting.
> Stcom ignore time offset refs UIORG-55

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- package.json
Provide a default value for filters so that we don't ever try to call
"split" on an undefined string because, not that I'd know, but I've
heard that bad things happen when you do that.
Fixes [UIU-470](https://issues.folio.org/browse/UIU-470)
> don't choke on undefined filters. Fixes UIU-470

- lib/structures/EditableList/EditableListForm.js
Clicking the cancel button on a form managed by `<EditableList>` does not restore the original values. It removes the editable field, but leaves the changed value in place. Navigating away then causes the "unsaved changes" prompt to appear.
This change updates `redux-form`'s `initialValues` after every successful save, and the calls `reset()` on any Cancel button press.
> STCOM-249 EditableList: Fixed Cancel button not resetting changed values

- lib/Callout/Callout.js
- lib/Callout/CalloutElement.js
Callouts are 'system-level' messages, so they deserve z-index prominence that the new overlay-container div will give them.
> Render callouts using React.Portal to overlay container.

- CHANGELOG.md
- lib/structures/EditableList/EditableItem.js
- lib/structures/EditableList/ItemEdit.js
We're using the HTML5 `autoFocus` prop here rather than mucking around and relying on `redux-form` refs or the format of our name parameters and `focus()` hacks. Seems cleaner to me than those alternatives.
> STCOM-256: Automatically focus textfields when editing/creating EditableList item

- lib/Callout/Callout.js
[STRIPES-528](https://issues.folio.org/browse/STRIPES-528)
During `<Callout>`'s `render()`, it attempts to create a React Portal at `#OverlayContainer` which is rendered by `<OverlayContainer>`. However, Callout's render can be fired before OverlayContainer's, which leads to React throwing an error when it's told to create a Portal at `null`.
This PR attempts to update the Portal container as long as it's falsey, and if an update still results in a falsey value for the container, doesn't try to create the Portal.
> STRIPES-528 Callout: Ensure calloutContainer exists before using it

- lib/Checkbox/Checkbox.js
Reverts folio-org/stripes-components#342. 
Unfortunately, we still haven't resolved the underlying issues that led to https://issues.folio.org/browse/UIU-430 (https://issues.folio.org/browse/STCOR-173 and https://issues.folio.org/browse/STRIPES-512).
> Revert "Re-added ID for Checkbox input and htmlFor on label"

- CHANGELOG.md
- lib/Checkbox/Checkbox.js
- package.json
Checkbox IDs were accidentally removed in #339, and then restored #342 which _also_ restored the (broken because we don’t have unique checkbox IDs) `<label for="some-id">` attribute, which, because it was broken, was reverted in #343. 
In other words, this reverts half the reversion of the inadvertent revision.
> restore missing checkbox id

- TESTING.md
- lib/Accordion/tests/interactor.js
- lib/Button/tests/interactor.js
- lib/IconButton/tests/interactor.js
- package.json
`bigtest/interaction` is now `bigtest/interactor`: https://github.com/bigtestjs/interactor
The `thefrontside/bigtest` monorepo was broken up into the `bigtestjs` org: https://github.com/bigtestjs
There weren't any breaking API changes for `stripes-components` to move from `bigtest/interaction` is now `bigtest/interactor` (there were several for `folio-org/ui-eholdings`).
> Upgrade bigtest/interaction to bigtest/interactor

- .eslintrc
- lib/Accordion/tests/Accordion-test.js
- lib/TextField/tests/TextField-test.js
- lib/TextField/tests/TextFieldHarness.js
- lib/TextField/tests/interactor.js
- tests/helpers.js
Tests get written a bit differently from typical JS code - especially chai assertions.
Adding some rules overrides to not be so noisy when we're trying to write tests.
> Add linting overrides for tests

- lib/Selection/SelectList.js
- lib/Selection/SingleSelect.js
@JohnC-80 this PR includes couple small changes to support https://issues.folio.org/browse/STSMACOM-94.
The locations in STSMACOM-94 are being pulled from the server when institution, campus or library is being changed. I was running into couple issues with `Selection`:
1. The new values were never populated
2. The `Selection` was throwing exceptions when `dataOptions` was empty
3. The filter input would stay read only (not sure why this was happening but I noticed that everything is working well when `TetherComponent` has just one child).
> Adjust Selection component to support dynamic data options. Part of STSMACOM-94

- tests/Harness.js
`TextField` tests were throwing errors (but somehow not failing?) like this:
```
ERROR: '[React Intl] Missing message: "stripes-components.fieldHasError" for locale: "en"'
ERROR: '[React Intl] Cannot format message: "stripes-components.fieldHasError", using message id as fallback.'
```
Resolves https://issues.folio.org/browse/STCOM-268
The translation strings in `stripes-components` weren't being prefixed with the string `stripes-components.` in tests.
Prefixing implementation adapted from https://github.com/folio-org/stripes-core/blob/master/webpack/stripes-translations-plugin.js
> STCOM-268 Prefix translation strings in tests

- lib/Datepicker/Calendar.css
- lib/FilterPaneSearch/FilterPaneSearch.css
- lib/LayoutBox/LayoutBox.css
When I tried upgrading the version of `stripes-components` used by `ui-eholdings`, I got several CSS loader errors:
```
WARNING in ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/@folio/stripes-components/lib/Datepicker/Calendar.css
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/jeffrey/Sites/Frontside/ui-eholdings/node_modules/@folio/stripes-components/lib/Datepicker/Calendar.css:46:7: variable '--color-fill-disabled' is undefined and used without a fallback
```
Any CSS file using a variable should import the file containing the variable definition.
> Explicitly import css variables

- CHANGELOG.md
- lib/structures/EditableList/EditableListForm.js
- lib/structures/EditableList/readme.md
- package.json
All fields are blank in newly created list items, there's no way to tell the component what you'd like for default values. This is especially important for uneditable fields.
`itemTemplate` wasn't being used anywhere and looks like an artifact from previous refactoring of `EditableList` according to the previous authors of this. So I made it actually do something since I liked the prop name. 😆
> EditableList STCOM-273: Added support for default field values

- lib/MenuItem/MenuItem.js
All we're doing here is passing along the item's meta to the callback so we shouldn't be imposing a propType on it.
> MenuItem: Adjusted itemMeta propTypes

- lib/TextField/TextField.js
- lib/TextField/tests/TextField-test.js
- lib/TextField/tests/interactor.js
- tests/TestForm.js
I'm interested in using the `reduxFormField` HoC with `TextField`, but it needed some more tests before that significant of a refactor.
- `onMouseDown` for the input clear button is now an `onClick`- there wasn't really a good reason for it to be a mouse-specific event, and most assistive technology will appropriately deal with `onClick`
- `title`s are now `ariaLabel`
- I made `tests/TestForm.js` more generic for future reuse; instead I leaned on field-level Redux Form validation.
- I made a more generic `fillAndBlur()` on the `TextField` interactor
- I did some minor reformats to the component: `contextTypes`/`propTypes`/`defaultProps` are all now static on the class (reads a lot nicer), and I split particularly long lines into multiple lines
- Start using `reduxFormField` - will need …
> Expand TextField tests

- lib/Dropdown/Dropdown.js
https://issues.folio.org/browse/STCOM-275
`_focusInDropdown` was equal to `this._menu.node.contains(document.activeElement)`, and its state is the same before and after render, so I moved it to after.
> STCOM-275: Dropdown: Refactor away componentWillUpdate

- CHANGELOG.md
- lib/Accordion/headers/DefaultAccordionHeader.js
- lib/Accordion/headers/FilterAccordionHeader.js
Provide an id to the accordion expander buttons in order to make them
accessible to testing infrastructure.
Refs [STCOM-276](https://issues.folio.org/browse/STCOM-276)
> provide id to accordion expander buttons

- CHANGELOG.md
- lib/Modal/Modal.js
- lib/Modal/readme.md
This is needed for when you have something that should be able to take focus _inside_ a Modal. 
E.g., without this, having a `<Datepicker>` inside a Modal doesn't work at all - the clicks on the Calendar's day buttons never hit their click handler.
> Modal: Added pass-through of enforceFocus prop

- lib/Button/Button.css
Prevent buttonInner from stealing focus on click which causes interactionStyles to display improperly.
> Prevent buttonInner from stealing focus on click

- package.json
`create-react-class` was added as a dependency in https://github.com/folio-org/stripes-components/commit/93c421f2e357e676d2ae7fe8525ae0bf3eb44055
`@folio/stripes-react-hotkeys` declares a dependency on `create-react-class`, and `@folio/stripes-components` has no other dependency on `create-react-class`. Therefore it doesn't need to be declared as a dependency of `@folio/stripes-components`.
> Remove create-react-class from dependencies

- package.json
Yarn throws warnings like...
```
warning " > @folio/stripes-components@2.0.16000323" has unmet peer dependency "stripes-core@^2.7.0".
```
... even if `stripes-cli` has installed `stripes-core`.
Update the dependency to `@folio/stripes-core`. This will need to happen in several `@folio` repos, but since they're all just nonblocking warnings, that can happen in any order/timing.
> Add @folio prefix to stripes-core peer dependency

- lib/MultiColumnList/MCLRenderer.js
- lib/Pane/Pane.css
- translations/en.json
I observed this aria-label in the ContributerTypes EditableList: `undefined with 5 columns`
Besides a variable not being passed down, the aria-label was prone to error in translation because it inserts one display string into another. I made the label generic so the whole string can be translated.
e.g. `Table with 5 columns`
I removed the `background-color: #fff` because it was unnecessary; the background is already white.
> MCLRenderer: i18n for aria-label

- lib/EntrySelector/EntrySelector.js
- translations/en.json
`stripes-components` should rely solely on its own translation strings, instead of leaning on `stripes-core`'s.
> Use own translation strings instead of stripes-core

- package.json
Prevents a yarn warning that `@bigtest/mocha`'s peer dependency on `mocha` wasn't being fulfilled.
> Explicitly state mocha dependency

- .gitignore
- lib/RadioButtonGroup/RadioButtonGroup.css
The `RadioButtonGroup` legend styling should match other labels styling (like `TextField`). This was pointed out when implementing `RadioButtonGroup` in `ui-eholdings`. (https://issues.folio.org/browse/UIEH-354)
**Before**
**After**
> Make the `RadioButtonGroup` legend styling match other labels

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/tests/Datepicker-test.js
- lib/Datepicker/tests/interactor.js
- lib/Timepicker/Timepicker.js
- lib/Timepicker/readme.md
- lib/Timepicker/tests/Timepicker-test.js
- lib/Timepicker/tests/interactor.js
- package.json
Mimics the approach for `Timepicker` in https://github.com/folio-org/stripes-components/pull/401. Adding a `timezone` prop gets us to testability for the `Datepicker` without dealing with `stripes` context.
Avoids using default props for `locale` and `timezone`, so the logic is more clear. When we get to the point of implementing a React 17-friendly strategy for context, we should revisit that implementation.
The most exciting part of this PR: TESTS! Datepicker and Timepicker now have minimal tests.
`ignoreLocalOffset` is no longer really needed, but I left it in for now.
> Add timezone prop to Datepicker

- lib/Select/Select.js
- lib/Select/tests/Select-test.js
- lib/Select/tests/interactor.js
- lib/TextArea/TextArea.js
- lib/TextArea/tests/TextArea-test.js
- lib/TextArea/tests/interactor.js
- lib/TextField/tests/interactor.js
- lib/sharedStyles/form.css
- lib/sharedStyles/sharedInputStylesHelper.js
- package.json
I was trying to use `reduxFormField` with `TextField`, but since changes will be needed in `sharedInputStylesHelper.js`, I wanted to make sure all the components using the helper (`TextField`, `TextArea`, and `Select`) had test coverage first.
Notable change: I renamed some of the classes in `sharedInputStylesHelper.js`. Since both an errored input and its error text had the class `feedbackError`, it was difficult to test that both the class got applied and that the text was present. Now the errored input will have the class `hasError` to differentiate from the feedback text.
This _will_ fail the eHoldings test suite when eHoldings updates to a newer `stripes-components`. This automated test might also fail?
- https://github.com/folio-org/ui-testing/blob/4ae910138d3c6fb69ba64fc8cf000e54343 …
> Create tests for TextArea and Select

- lib/IconButton/tests/IconButton-test.js
`react-router` 4.3.x introduced a change to the way `Link`s construct: https://github.com/ReactTraining/react-router/pull/5489
Use the `StaticRouter` to test instead of `HashRouter`.
> Update IconButton test for react-router 4.3

- .storybook/config.js
Storybook wasn't runnable, because the translations files moved. Follow-up to https://github.com/folio-org/stripes-components/pull/414
We should add a test to CI just to make sure storybook builds.
> Fix translations path for storybook

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/tests/Datepicker-test.js
- lib/Timepicker/Timepicker.js
- lib/Timepicker/readme.md
- lib/Timepicker/tests/Timepicker-test.js
- package.json
`timezone` was consistent with `this.context.stripes` and `moment`, but not with `react-intl`'s API or any other props in `stripes-components`.
camelCase it.
The `DueDatePickerForm` in `stripes-smart-components` is the only use I know of that will break.
> Camel case timeZone props

- lib/TextField/TextField.js
React 16.3 introduced `React.createRef()`, a new way for working with refs: https://reactjs.org/docs/refs-and-the-dom.html
I was having trouble wrapping `TextField` with a higher-order component (in this case, `reduxFormField`, and this new ref API should solve it.
To get the underlying DOM of the ref, use `current`.
> Update TextField to use React.createRef()

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Timepicker/Timepicker.js
- package.json
Didn't get caught by tests because we're not running any tests with `stripes` context.
> Fix stripes.context.locale logic

- lib/ErrorBoundary/ErrorBoundary.js
`children` can be an array of objects, so use the more precise `node` prop type.
> ErrorBoundary: Specify more precise proptypes

- .storybook/config.js
Storybook was loading in the list of English strings like `fieldHasError`, but wasn't prefixing them like the `stripes-core` environment does.
Copied over prefixing from the `stripes-components` test suite config so strings get registered like `stripes-components.fieldHasError`.
The `prefixKeys()` function is duplicated from the test config, but there wasn't an obvious spot to put code intended for reuse between tests and storybook (that might not even be a coupling we want to create).
> Fix storybook translation string prefixes

- CHANGELOG.md
- lib/Icon/Icon.css
- lib/Icon/Icon.js
- lib/Icon/stories/BasicUsage.js
- lib/Icon/stories/Icon.stories.js
- package.json
It's currently not possible to `fill` an `<Icon>`'s SVG without hardcoding a color in your JS and passing that as a prop. This is because we currently don't have a way of getting CSS variables into JS. 
Until we do, I added a `status` prop on Icon that satisfies the main goal, which is colouring an Icon based on our warn/error/success colours.
> Icon: Added "status" prop used for fill color

- lib/IconButton/tests/IconButton-test.js
We were passing in an empty context in other `describe()` blocks, just missed one.
> Fix Router context in IconButton test

- lib/InjectIntl/InjectIntl.js
- package.json
`injectIntl` needed a little more time in the oven. Follow-up to https://github.com/folio-org/stripes-components/pull/426
Being thrown:
```
ERROR: 'Warning: Failed prop type: Invalid prop `forwardedRef` of type `function` supplied to `InjectIntl`, expected a single ReactElement.
```
and
```
ERROR: 'Warning: React does not recognize the `forwardedRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `forwardedref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
- Be more permissive of `forwardedRef` prop type.
- Don't pass along `forwardedRef` to children.
- Give a `displayName` for `injectIntl`.
> Clean up injectIntl

- lib/Datepicker/Datepicker.js
- lib/Timepicker/Timepicker.js
- package.json
https://github.com/folio-org/stripes-components/pull/441 unfortunately broke the `Datepicker` and the `Timepicker`. Our very minimal tests for those components were covering typing in the inputs, but not actually using the tethered pickers.
On the TODO list: write tests for the pickers.
https://github.com/folio-org/stripes-components/pull/443 introduces Storybook stories for the `Datepicker` and `Timepicker` for easier debugging in the future.
> Fix Datepicker and Timepicker refs

- lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
Some recent changes around `forward_ref` caused `mergedFieldComponents[fieldName`] to return object instead of a react function:
````js
{ $$typeof: Symbol(react.forward_ref), render: ƒ}
````
which caused tests fo fail. This PR just adds extra check for the component. We should probably refactor it a bit more but for now I just want to get the tests to pass again.
> Add extra check for component in EmbeddedAddressForm

- lib/AppIcon/AppIcon.js
- lib/Datepicker/Datepicker.js
- lib/IfInterface/IfInterface.js
- lib/IfPermission/IfPermission.js
- lib/ModalFooter/ModalFooter.js
- lib/Pluggable/Pluggable.js
- lib/Settings/Settings.js
- lib/Timepicker/Timepicker.js
https://issues.folio.org/browse/STCOR-208
- This PR converts components from the legacy context API to the new context API
- `withStripes()` is a HoC to wrap components with a `StripesContext.Consumer`
- The Providers were set in https://github.com/folio-org/stripes-core/pull/330
> STCOR-208 Use new context API: withStripes()

- lib/Datepicker/Calendar.js
- lib/Datepicker/tests/Datepicker-test.js
- lib/Datepicker/tests/interactor.js
- package.json
https://github.com/folio-org/stripes-components/pull/426 broke `Datepicker` keyboard focus behavior, and prevented dates simply typed in (vs. being clicked on in the calendar) from being validated.
`Calendar` needed to pass along its ref to `Datepicker`.
The calendar picker needs some acceptance tests.
> Add withRef to Calendar

- lib/Datepicker/Datepicker.js
- lib/InjectIntl/InjectIntl.js
- lib/Settings/Settings.js
- lib/Timepicker/Timepicker.js
- package.json
In a storybook context, `Datepicker` and `Timepicker` (https://github.com/folio-org/stripes-components/pull/443) wouldn't receive the `intl` context. The `intl` prop would just get eaten before it made its way down.
Flip the order of the higher-order components.
> Fix withStripes bugs

- lib/Pane/Pane.js
- lib/PaneHeader/PaneHeader.js
With the introduction of `React.createRef()` in React 16.3, refs are now recommended to be created using this new API.
Using this API with `Pane` or `PaneHeader` causes a propTypes warning to be thrown
Adjusted the prop type to be one of object or function
- https://reactjs.org/docs/refs-and-the-dom.html
- I went to make this change across all refs, but then noticed that some refs use `ref.bind(this)` and other refs are wrapped in a fallback function that then invokes the ref itself as a function. Instead of changing all of these refs, I made sure this pane title ref works with the new API. The other refs may require additional work besides simply changing the prop type.
> Add object to pane title ref prop type

- lib/Datepicker/Datepicker.js
- lib/Datepicker/tests/Datepicker-test.js
- lib/Datepicker/tests/interactor.js
`Datepicker` was the only component using `TextField` to have a whitespace character at the beginning of its placeholder (vs. `Timepicker` or `TextField` itself).
The whitespace was probably intentional originally, but now it'll match the other components.
> Update whitespace in Datepicker placeholder

- lib/Icon/icons.js
- lib/Timepicker/Timepicker.js
- package.json
The `<Timepicker>` clock icon was out of scale. Now it's the same size as the `clearX`.
> Adjust clock icon for Timepicker

- lib/Button/tests/interactor.js
- lib/ModalFooter/tests/ModalFooter-test.js
- lib/ModalFooter/tests/interactor.js
Some minor refactoring of the ModalFotoer tests. Now using the Button-interactor for buttons in the ModalFooter-interactor using the `scoped` method.
I also added "label" to the Button interactor.
> Refactor ModalFooter tests

- lib/Dropdown/Dropdown.js
When on the Edit page for a SearchAndSort record (e.g., Edit Request) that uses the `actionMenuItems` prop to add a dropdown menu, clicking the button to open the dropdown menu instead reloads the page with a query string of the edited fields.
Looks like an issue where we're stopping propagation, but not preventing the browser from doing what it wants to do. This is a quick patch, unless y'all wanted to approach the fix differently.
> Dropdown: preventDefault when toggling dropdown

- .eslintignore
- lib/Selection/SelectList.js
The `/artifacts` directory created by coverage reports was being run through `eslint`, with lots of errors.
>  Ignore artifacts directory when linting

- lib/Modal/Modal.js
`<Modal>` needs a z-index-safe place to render. `#OverlayContainer` provides that without covering the universal navigation.
fix styling in stripes-core so that the top nav does not appear blocked.
> STCOM-304 render modal in Overlay Container

- lib/Callout/index.js
- lib/Datepicker/index.js
- package.json
The webpack 4 upgrade work (https://github.com/folio-org/stripes-core/pull/347) exposed a couple of named export problems:
`"export 'Calendar' was not found in './Calendar'`
`"export 'CalloutElement' was not found in './CalloutElement'`
> Fix named exports

- jsconfig.json
VSCode interprets descriptors as as TypeScript feature and shows a warning that descriptors are experimental. This PR adds `jsconfig.json` file to the project to tell editors that descriptors are 👌
To learn more about jsconfig.json checkout [VSCode documentation](https://code.visualstudio.com/docs/languages/jsconfig\#_jsconfig-options).
> Added jsconfig.json

- CHANGELOG.md
- util/makeQueryFunction.js
- util/nsQueryFunctions.js
The purpose of this PR is to introduce a way for namespacing params used by `makeQueryFunction`.
The implementation follows the document written by @MikeTaylor here:
https://github.com/folio-org/stripes-components/blob/master/util/parameterizing-makeQueryFunction.md
There is another PR against `stripes-smart-components` which modifies `<SearchAndSort>` component in order to set/namespace the URL query parameters: 
https://github.com/folio-org/stripes-smart-components/pull/201/files
An example of the usage of this new functionality can be found in `ui-users`:
https://github.com/folio-org/ui-users/blob/STCOM-300/Users.js#L37-L59
> Modify makeQueryFunction to support param namespacing. Part of STCOM-300

- CHANGELOG.md
- lib/Modal/Modal.css
- package.json
#476 started rendering Modals into the `overlayContainer`, but the `overlayContainer` has `pointer-events: none` set on it so all mouse events get sent to what's _behind_ the Modal.
This PR turns pointer-events back on for Modals.
> UICHKOUT-437 Modal: Catch pointer events

- CHANGELOG.md
- lib/MetaSection/MetaSection.js
- lib/MetaSection/readme.md
- package.json
`MetaSection` can now take an Okapi user object as well as a string for the `createdBy` and `updatedBy` props. This object contains the `personal` object from which it will construct the name itself, and the user's `id` with which it will construct a `Link` to that record if the logged-in user has the appropriate permissions.
> STCOM-305: Add link to user record in MetaSection

- CHANGELOG.md
- package.json
This will bring stripes-components in sync with corresponding updates in
[stripes-core](/folio-org/stripes-core/pull/347) and [stripes-cli](/folio-org/stripes-cli/pull/88).
Refs [STCOR-175](https://issues.folio.org/browse/STCOR-175)
> upgrade to webpack 4

- lib/ModalFooter/examples/ModalFooterExample.js
Live reload wasn't working for the CSS on the `ModalFooter` story. It's because there was an un-relative path that resolved to the `@folio/stripes-components` found in `node_modules`.
Stick to relative paths in Storybook stories.
> Fix paths for ModalFooter story CSS

- lib/SearchField/SearchField.js
- lib/SearchField/tests/SearchField-test.js
- lib/SearchField/tests/interactor.js
- package.json
- Upgrades `@bigtest/mocha` and `@bigtest/interactor`
- The `TextField` used by `SearchField` won't try to run in "`redux-form` mode" because of the `meta` prop.
- Some tests skipped until `Select` can be more independent of `redux-form`.
> Add tests for SearchField

- CHANGELOG.md
- lib/structures/AddressFieldGroup/AddressEdit/AddressEditList.js
- lib/structures/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
- lib/structures/AddressFieldGroup/AddressEdit/index.js
- lib/structures/AddressFieldGroup/AddressList/index.js
- lib/structures/AddressFieldGroup/AddressView/index.js
- lib/structures/ConfirmationModal/index.js
- lib/structures/EditableList/index.js
- lib/structures/EmptyMessage/index.js
- lib/structures/InfoPopover/index.js
- lib/structures/RepeatableField/index.js
- lib/structures/SearchField/index.js
- package.json
No `folio-org` repos are pointing to components previously found in `lib/structures` anymore.
Resolves https://issues.folio.org/browse/STCOM-284.
Major version bump to 3.0.0. I'll create corresponding tag too on merging.
> STCOM-284 Remove structures deprecation

- lib/SearchField/SearchField.js
- lib/SearchField/tests/SearchField-test.js
- lib/Select/Select.js
- lib/Select/stories/BasicUsage.js
- lib/Select/tests/Select-ReduxForm-test.js
- lib/Select/tests/Select-test.js
- lib/Select/tests/interactor.js
- lib/TextArea/TextArea.js
- lib/TextArea/stories/BasicUsage.js
- lib/TextArea/tests/TextArea-ReduxForm-test.js
- lib/TextArea/tests/TextArea-test.js
- lib/TextArea/tests/interactor.js
- lib/sharedStyles/sharedInputStylesHelper.js
- package.json
Continue the pattern established in https://github.com/folio-org/stripes-components/pull/372.
Related to https://issues.folio.org/browse/STCOM-269
Resolves https://issues.folio.org/browse/STCOM-310
Use the `reduxFormField()` higher-order component to simplify the logic in form field components.
With `Select` and `TextArea` using `reduxFormField()`, we can also simplify `SearchField` and the `sharedInputStylesHelper` to not know anything about `input` or `meta` props from Redux Form.
`SearchField` needed a pattern described in https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html
> STCOM-310 Use ReduxFormField for Select and TextArea

- lib/Button/index.js
- lib/Modal/Modal.css
- lib/ModalFooter/ModalFooter.css
- lib/ModalFooter/ModalFooter.js
Longer button text was getting cut off by keeping the `ModalFooter` buttons inline on narrower screens / high zoom level.
Part of https://issues.folio.org/browse/UIEH-432
Use mobile-first CSS to display the buttons as block-level until the `medium` breakpoint (641px wide).
> Introduce responsive behavior for ModalFooter buttons

- lib/Select/Select.js
eHoldings uses a `<Select>` with Redux Form to add identifiers to a title:
```
<Field
name={`${identifier}.flattenedType`}
type="text"
component={Select}
autoFocus={Object.keys(allFields.get(index)).length === 0}
label="Type"
dataOptions={[
{ value: '0', label: 'ISSN (Online)' },
{ value: '1', label: 'ISSN (Print)' },
{ value: '2', label: 'ISBN (Online)' },
{ value: '3', label: 'ISBN (Print)' }
]}
/>
```
That fails the `<Select>` `propType` validation because the values eventually get parsed as numbers, not strings.
It seems like it'd be a common use case to have a numerical ID as the value for a `<Select>`.
> Allow number for Select value prop

- lib/Modal/Modal.css
- lib/ModalFooter/ModalFooter.css
- lib/ModalFooter/ModalFooter.js
Uses `flex-direction` to show the primary button:
- first in markup
- first on small screens
- last on wider screens
I also replaced `gutter` with `controlMarginBottom`, which reduced the vertical spacing between buttons from 15px to 12px. Fits in better with other form elements.
> Change order of ModalFooter buttons

- README.md
- docs/Accessibility.md
- docs/patterns/AccessibleRouting.md
This document details the things @wwilsman & I learned while spiking an approach to make the FOLIO UI module we work on accessibile. You can see this work in action in the demos that happened for sprint review 40-41, @cowboyd did a great job! [Here's a direct link to that demo on YouTube](https://youtu.be/nhNdlyCMZVg?t=2459).
This document is written as a way to describe what we learned so other developers FOLIO can use this as a launch point for making their apps accessibile. This document does not describe _the_ way to make your app accessibile.
As always we are always happy to help with any questions you might have regarding accessibility :)
Lastly here's the PR to eHoldings that was the implementation of this work: https://github.com/folio-org/ui-eholdings/pull/448
[Link to the …
> Introduce accessible routing documentation

- lib/Icon/Icon.css
- lib/Icon/tests/Icon-test.js
- In order to use this Icon in ui-eholdings app, we want size "small" to be 14x14 since that matches with font size. 
- We are using this Icon component as part of an external link component, which displays an external link inline with this icon.
- Open question is whether changing this size affects other apps in a bad way, and if we want to introduce another size, possibly x-small that represents 14x14 and leave small as 16x16.
> change size of a small icon

- lib/Datepicker/Calendar.js
- lib/Datepicker/Datepicker.js
- lib/Datepicker/DayButton.js
- lib/Datepicker/tests/Datepicker-Redux-test.js
- lib/Datepicker/tests/Datepicker-test.js
- lib/Datepicker/tests/interactor.js
- lib/TextField/stories/BasicUsage.js
- package.json
The goal of this PR is to increase confidence in the Datepicker/Calendar/DayButton components by writing tests for them. 
I gathered required requirements about this component from @JohnC-80 and @cherewaty. 
**Features that Datepicker should support**
- uses a standard text input - value can be typed as well as picked using the calendar
- picker disappears with a click outside or blur of the input
- presents in localized format (based on locale to determine input and output)
- custom format can be applied
- excluded dates
- a11y - screen reader compatibility (announces actions, selections, values)
- a11y - keyboard navigation of dates
- accepts colors from a stripes theme/works with stripes-components postcss workflow/css-modules
- supports some version of the “passThroughValue” to keep …
> Add tests to Datepicker components

- CHANGELOG.md
- lib/Checkbox/Checkbox.js
- lib/Checkbox/tests/Checkbox-test.js
- lib/ReduxFormField/readme.md
- lib/Selection/SingleSelect.js
- lib/Selection/tests/SingleSelection-test.js
- package.json
1. `<SingleSelect>` and `<Checkbox>` have props `errorText` and `warningText`.
2. `<Select>`, `<TextArea>`, and `<TextField>` call those same props `error` and `warning`.
Resolves https://issues.folio.org/browse/STCOM-314
We decided on style 2 as the preferred.
This is technically a breaking change, but no `folio-org` projects were using the old prop naming.
> STCOM-314 Rename errorText and warningText props

- CHANGELOG.md
- lib/Settings/Settings.js
- lib/Settings/readme.md
- package.json
[UIORG-84](https://issues.folio.org/browse/UIORG-84) is a bit of an umbrella issue for all the scenarios where the pane sizing on Settings page is a bit off. 
PR #486 handled some of these scenarios but only solves the problem for Settings pages that use an EntrySelector. Pages that don't include the Locations pages that are specifically called out in UIORG-84, along with any page that uses `<ControlledVocab>`. 
Those three-pane pages are made cleaner by shrinking the nav pane that contains the links to a module's settings pages. I've exposed the width of that pane via `<Settings>.navPaneWidth`.
**Feedback requested about whether `navPaneWidth`'s default should be changed to something like 30% instead of keeping the same behaviour that we currently have (`fill`)**.
> Settings: Expose nav pane width

- package.json
Fixes nested scoping issue that required us to pin to `0.7.0`: https://github.com/bigtestjs/interactor/pull/39
> Upgrade @bigtest/interactor

- CHANGELOG.md
- lib/Button/Button.css
- package.json
This CSS in `button.css`...
```
&:first-child {
margin-left: 0;
}
```
... meant that any button that's a first child of its parent (even if it's by itself) would have its margin overridden.
The specific case I ran into: I wanted to put a button on the `firstMenu` of a `<PaneHeader>` with a `buttonClass` that defined some margins. 
`:first-child` was more specific than my class, so I couldn't set a left margin:
Rely on relationships between buttons instead.
Set left and right margins of `<Button>`s to zero by default, then buttons that are next to each other get 4px between them (in both LTR and RTL languages).
> Change button relationship margins

- CHANGELOG.md
- lib/Accordion/Accordion.css
- lib/Accordion/Accordion.js
- package.json
Replaces https://github.com/folio-org/stripes-components/pull/520. Related to https://github.com/folio-org/ui-eholdings/pull/482.
Fixes scenarios around putting a scrollable list within an `<Accordion>`. Does not change behavior of `<Accordion>`s in storybook environment.
> Adjust Accordion expand logic and CSS

- lib/PaneHeader/PaneHeader.css
Added line-height of 1.2 to pane header sub to avoid letters that go below the text baseline (g, j, p, q) to be cropped off.
> Minor pane header sub fix

- lib/ConfirmationModal/examples/ConfirmationModalExample.js
- lib/ConfirmationModal/readme.md
- lib/Modal/stories/BasicUsage.js
- lib/ModalFooter/examples/ModalFooterExample.js
These popped up in SonarCloud "Security" reports: https://sonarcloud.io/component_measures?id=folio-org%3Astripes-components&metric=security_rating
Uses Storybook actions instead of `alert()`: https://github.com/storybooks/storybook/tree/release/3.4/addons/actions
> Replace alerts with Storybook actions

- CHANGELOG.md
- lib/ModalFooter/ModalFooter.css
- lib/ModalFooter/ModalFooter.js
- package.json
`<ModalFooter>` buttons had a zone of screen widths where buttons with longer strings didn't have any space between them.
Buttons can now be inline even below the medium breakpoint, just based on how long the button text is. I used some negative margins to improve the spacing.
> Adjust ModalFooter button CSS

- lib/Modal/Modal.css
On larger screens, the modal widths got a little out of control.
To fix this I have updated the modal to use max-width in pixels instead of percentage widths. This makes the width of the modal more predictable.
I also changed the margins on mobile devices to make sure that it fills up the space available with a margin of 15px on each side (the standard margin for the system currently).
Below is an example of a modal with the size of "small". Before it got too big on larger screens and it got a bit squashed before going to a 90vw width. Using max-width fixes this issue.
The new max-width values might not be the ideal ones but this can always be adjusted. Currently they are 550px on small, 750px on medium and 1100px on large.
> Change modal widths from percentage to pixels

- .gitignore
- package.json
The command makes it easy to generate a static storybook site.
Simply run `yarn run storybook-build` to generate a static site.
I use it when uploading updated versions of the storybook to http://ux.folio.org/storybook-draft.
> Added 'storybook-build' to scripts.

- CHANGELOG.md
- lib/Button/stories/Button.stories.js
- lib/Selection/SingleSelect.js
- lib/Selection/stories/BasicUsage.js
- lib/Selection/stories/Selection.stories.js
Initially I just wanted to add a storybook example for the `<Selection>` but I ended up making a few changes as well:
- Fixed a minor bug in the <Button> stories file that caused the Storybook to break
- Made sure that the disabled state actually can be activated (passing the disabled prop down to the <button> in SingleSelect
- Added the correct label class from sharedStyles/form.css so that the label matches the labels from the rest of the form components
> Adding <Selection> example + minor changes

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/exportToCsv.js
- lib/MultiColumnList/readme.md
- package.json
- translations/stripes-components/en.json
https://issues.folio.org/browse/UIU-459
- `exportToCsv(csv)` is in its own file for transforming the JSON to CSV, optionally omitting columns, and triggering the download
- MultiColumnList was originally just the table. I added a sibling that precedes it, ActionbarContainer, which caused the whitespace diff seen on Github. This container has two children: the optional prop `actionbar` and the "Export to CSV" `<Button>`
- increment patch version so it can be consumed by `ui-users`
> UIU-459: export csv

- lib/Button/Button.js
- lib/Button/readme.md
- lib/Button/tests/Button-test.js
Added 'to' prop to <Button> that returns an instance of react-router-dom's `<Link>` component - useful for changing routes inside the react-router powered application. It's still possible to pass a href-prop which renders a regular link - useful for external links.
I added tests for this new addition as well as a few other tests to reach 100% test coverage 🎊
> Added "to"-prop to <Button> and updated tests

- lib/Selection/Selection.js
Resolves https://issues.folio.org/browse/STCOM-324.
I confirmed that `<SingleSelect>` is using `reduxFormField` effectively. This change doesn't really get us much besides one less instance of `meta` and `input` props when we search around the repo. Since `<Selection>` isn't doing anything with any props besides passing them along, we're not missing out on any prop type validation by removing these.
> STCOM-324 Remove input and meta propTypes from Selection

- lib/Icon/icons.js
in the creation of the svg a path was added, which in the print icon had an erroneous rendering.
> fix wrong conversion

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Timepicker/Timepicker.js
Removing `passThroughValue` will toss out a lot of complexity from `<Datepicker>` and `<Timepicker>`.  `ui-checkin` is the only `folio-org` repo using `passThroughValue`, and I'm closing in on an alternative design solution. Probably a good time to start throwing deprecation warnings.
> Deprecate passThroughValue

- lib/Button/Button.js
Currently, if `<Button>` is passed a `buttonRef` prop via `React.createRef()` it does not work since `<Button>` treats it as a function internally.
Instead of using the method `getButtonRef` simply pass the prop right through to the element... also, expanded propTypes since `React.creatdRef()` creates an object.
Less code == more coverage, amiright?
> Clean button ref-handling

- util/makePathFunction.js
`makePathFunction()` was replaced by `makeQueryFunction()`.
No `folio-org` repos are still using `makePathFunction()`.
> Introduce deprecation warnings for makePathFunction

- lib/Datepicker/readme.md
- lib/Timepicker/readme.md
Follow-up from https://github.com/folio-org/stripes-components/pull/563
Removes explanations of deprecated props, and marks them as deprecated in the prop tables.
> Mark deprecated Datepicker and Timepicker props in readmes

- .eslintrc
- lib/Selection/SelectList.js
- package.json
- yarn.lock
Removes rules that now appear in the shared config.
> Upgrade eslint-config-stripes to 3.1.1

- CHANGELOG.md
- package.json
The previous release of stripes-react-hotkeys was hard-coded to use
React 15. The 1.1.0 release instead pulls in an unversioned release as a
peerDependency, i.e. it does the same thing stripes-components does and
will get us the same version of the library.
> update to current stripes-react-hotkeys

- .circleci/config.yml
- lib/TextField/TextField.css
- lib/TextField/TextField.js
- lib/TextField/tests/TextField-test.js
- lib/TextField/tests/interactor.js
- lib/sharedStyles/form.css
[STCOM-286](https://issues.folio.org/browse/STCOM-286) - `TextField` can occasionally get in a state where it does not have adequate padding for the search icon at the beginning of the field.
While unable to reproduce this case specifically, I was able to reproduce a related issue in storybook:
1. Open storybook
2. Navigate to the `TextField` basic usage and scroll down to the start/end control example
3. Refresh the page and scroll down to the example again
4. Observe that the final example is now double the width of the viewport due to excessive padding.
Storybook injects CSS for a module on demand. When this page loads for the first time, there are no styles associated with icon sizes, so the icons default to 100% width.
`TextField` is mounted and calculates the ridiculous padding.
CSS …
> STCOM-286 - Fix overlapping TextField icons

- lib/AppIcon/AppIcon.js
- lib/AppIcon/readme.md
- lib/PaneHeader/PaneHeader.js
Today I noticed that the icon in the PaneHeader was a bit misaligned and after some brief investigation I found that it had been wrapped in an additional `<span>` with `aria-hidden="true"`.
To avoid having the extra span I decided to add an "ariaHidden" prop to the AppIcon but then I realized that the AppIcon can have a label so it does not make sense to make the whole component aria-hidden.
Instead, I added the prop "iconAriaHidden" which only applies to the icon itself - leaving the label (if available) to still be readable by screen readers.
> Allow 'iconAriaHidden' on <AppIcon> and updated PaneHeader

- lib/global.css
Part of https://issues.folio.org/browse/STCOM-342
Will encourage semantic usage of `<fieldset>` and `<legend>` without the odd styles browsers have by default for those elements.
> Remove default fieldset padding

- lib/Headline/Headline.js
- lib/Headline/readme.md
`h1`/`h2`/`h*`, etc. should always be in descending order.
By switching the default `<Headline>` tag to be a `<div>`, consumers won't lazily end up with out-of-order `<h2>`s.
> Make Headline a div by default

- lib/AppIcon/AppIcon.js
- lib/AppIcon/readme.md
- lib/AppIcon/tests/AppIcon-test.js
In order to fix this issue: https://issues.folio.org/browse/STCOR-253, we need to be able to overwrite the alt and title attributes on the AppIcon. In this update, I changed the AppIcon so that it's possible to pass alt, src, and title as props without breaking the existing functionality.
I also updated the if statement for icons that are retrieved from the stripes context, that has a size of "small" to check if the user's screen is a non-retina screen. We only want to render the 14px PNG version of the icon for users on non-retina screens because the SVG version can get a bit blurry on non-retina screens.
Since the screen resolution (afaik) can't be tested consistently I decided to ignore this specific block of code from tests so that the test coverage is still 100%.
> Added src, title & alt props to AppIcon + retina detection

- lib/Modal/Modal.js
- lib/Modal/readme.md
- Added 'contentClass' prop that makes it possible to apply class names to the content area of the Modal
- Updated readme
- Changed the order of props to be alphabetical in the readme
- Re-factored functions to be arrow-functions
The reasoning behind adding this class is that I need to be able to add some classes to fix some issues in the `ui-plugin-find-user` but in general I think it's a nice option to have when working with the Modal-component.
Issue: https://github.com/folio-org/ui-plugin-find-user/pull/37
> Added 'contentClass' prop to <Modal>

- lib/TextField/TextField.js
Added className prop that applies to the root element.
Moved 'inputClass' prop to be applied to the input itself.
This fixes the styling of the "Sign in" route TextField's.
> Minor TextField class name changes

- lib/Badge/Badge.css
Badges should consistent label colors - even when inside an :active element.
Made default badge color very specific to prevent label from changing color when inside an element with interactionStyles applied (IconButton, Button etc.)
> Minor badge label color fix

- index.js
This missing export was found while consuming `stripes-*` modules via `stripes` (the framework) from within `ui-users`.  Related to STRIPES-547
> Add component missing from exports

- lib/NavListItem/NavListItem.css
Added 'odd' class for NavListItem that can be used to control background-color of even/odd rows manually in a list of NavListItem's (when used outside a NavListSection with `striped=true`.
Replaced hardcoded rgba color with color variable.
> Added 'odd' class for NavListItem 

- CHANGELOG.md
- lib/Pane/Pane.css
- lib/Paneset/Paneset.css
Paneset no longer simply disappears on smaller screens. Still lots of related bugs to work out before https://issues.folio.org/browse/STCOM-274 is marked as done.
"After" screenshot also indicates poor grid usage.
> STCOM-274 Fix paneset CSS behavior on narrow screens

- CHANGELOG.md
- lib/Headline/Headline.js
- lib/Headline/readme.md
- lib/global.css
Will make `<legend>` use easier, since it can be styled to look like the appropriate `<h*>` for its hierarchy context.
> Expose legend as tag for Headline

- CHANGELOG.md
- lib/Headline/Headline.css
- lib/Headline/Headline.js
- lib/Headline/readme.md
- lib/Headline/stories/BasicUsage.js
- lib/global.css
Replaces https://github.com/folio-org/stripes-components/pull/606
- Removed global heading styles, then set the new `<Headline>` sizes to browser default proportions:
https://www.w3.org/TR/html5/rendering.html#sections-and-headings
- Added `base` option that creates
> Adjust headline sizes

- CHANGELOG.md
- lib/Headline/Headline.js
I want to use `<Headline>` more extensively in `ui-eholdings` for consistent typography. In one place where we currently use a bare `<h2>`, we use a ref to focus it when its parent pane mounts:
https://github.com/folio-org/ui-eholdings/blob/9c2e05956bd95624c00856993786f17ecc617af2/src/components/details-view/details-view.js#L258-L264
Expose a ref from `<Headline>` with ref forwarding: https://reactjs.org/docs/forwarding-refs.html
> Expose headline ref

- lib/IconButton/IconButton.js
Refs are good for focus-management in React. Buttons are typical focus-management targets, so this is definitely needed for those scenarios (it did not work previously)
Use `React.forwarRef()` functionality... had to pass `innerRef` to `<Link>` since that's what it wanted.
> STCOM-351 Iconbutton `ref` support

- lib/Checkbox/Checkbox.css
- lib/RadioButton/RadioButton.css
After the font-size changed there were some minor misalignments in the RadioButton and the Checkbox component.
Removed margin-top from custom checkbox/radio button and applied align-items: baseline to the parent elements. This fixes the misaligned checkbox/radioButtons and it's also less 'hardcoded' therefore making it work better with different font-sizes.
> Fixed misaligned RadioButton and Checkbox

- CHANGEMANAGEMENT.md
- MIGRATIONPATHS.md
- README.md
Adding some informational docs here that discuss managing breaking changes and versioning. 
A guide for making changes due to upgrading stripes components. Ideally create a permanent document that we might be able to link to from deprecation console warnings or any other documentation to facilitate the upgrade process from any previous version.
There's probably already more that we can add to the migration document. Just floating this idea...
[Change mangement](https://github.com/folio-org/stripes-components/blob/migration-docs/CHANGEMANAGEMENT.md)
[Migration paths](https://github.com/folio-org/stripes-components/blob/migration-docs/MIGRATIONPATHS.md)
> Migration docs

- CHANGELOG.md
- lib/SearchField/SearchField.js
Related to https://issues.folio.org/browse/STCOM-354
`normalize.css` takes care of the style nuances of `input type="search"`:
```
/**
* 1. Correct the odd appearance in Chrome and Safari.
* 2. Correct the outline style in Safari.
*/
[type="search"] {
-webkit-appearance: textfield; /* 1 */
outline-offset: -2px; /* 2 */
}
/**
* Remove the inner padding and cancel buttons in Chrome and Safari on macOS.
*/
[type="search"]::-webkit-search-cancel-button,
[type="search"]::-webkit-search-decoration {
-webkit-appearance: none;
}
```
> STCOM-354 Use input type="search" for SearchField

- CHANGELOG.md
- lib/Accordion/Accordion.css
- lib/AddressFieldGroup/AddressEdit/AddressEdit.css
- lib/Badge/Badge.css
- lib/Button/Button.css
- lib/Checkbox/Checkbox.css
- lib/Datepicker/Calendar.css
- lib/Dropdown/Dropdown.css
- lib/DropdownMenu/DropdownMenu.css
- lib/Headline/Headline.css
- lib/Headline/Headline.js
- lib/Headline/readme.md
- lib/Headline/stories/BasicUsage.js
- lib/Icon/stories/style.css
- lib/KeyValue/KeyValue.css
- lib/LayoutHeader/LayoutHeader.css
- lib/Modal/Modal.css
- lib/MultiColumnList/MCLRenderer.css
- lib/PaneHeader/PaneHeader.css
- lib/RadioButton/RadioButton.css
- lib/RadioButtonGroup/RadioButtonGroup.css
- lib/TextField/stories/BasicUsage.js
- lib/Timepicker/TimeDropdown.css
- lib/sharedStyles/form.css
- lib/variables.css
Have enough levels of hierarchy in font sizes (esp. for headlines) that laying out pages is easy.
I created these variables, based on the very fresh CSS Fonts Module Level 3 recommendation:  https://www.w3.org/TR/css-fonts-3/#propdef-font-size
```
--font-size-xx-small: 0.67rem;
--font-size-x-small: 0.75rem;
--font-size-small: 0.83rem;
--font-size-medium: 1rem;
--font-size-large: 1.17rem;
--font-size-x-large: 1.5rem;
--font-size-xx-large: 2rem;
```
The global base is set at 16px, as of https://github.com/folio-org/stripes-components/pull/611
I then updated every use of `font-size` in `stripes-components` to use one of those seven sizes.
The biggest restriction was that the font size of `<input>` elements need to be >=16px.
I generally set `<label>` and label-like elements to …
> Create wider type stack with consistent variables

- CHANGELOG.md
- lib/Accordion/Accordion.css
- lib/FilterControlGroup/FilterControlGroup.css
Resolves https://issues.folio.org/browse/STCOM-355
Filter groups were already good, but needed some CSS changes to override the new defaults:
> STCOM-355 Add padding to accordion content

- CHANGELOG.md
- lib/RadioButton/RadioButton.css
- lib/RadioButton/RadioButton.js
- lib/RadioButton/readme.md
- lib/RadioButton/stories/BasicUsage.js
- lib/RadioButton/tests/RadioButton-ReduxForm-test.js
- lib/RadioButton/tests/RadioButton-test.js
- lib/RadioButton/tests/interactor.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/RadioButtonGroup/readme.md
- lib/RadioButtonGroup/stories/BasicUsage.js
- lib/RadioButtonGroup/stories/RadioButtonGroup.stories.js
- lib/RadioButtonGroup/tests/RadioButtonGroup-ReduxForm-test.js
- lib/RadioButtonGroup/tests/RadioButtonGroup-test.js
- lib/RadioButtonGroup/tests/interactor.js
Resolves [STCOM-88](https://issues.folio.org/browse/STCOM-88), [STCOM-322](https://issues.folio.org/browse/STCOM-322), and [STCOM-323](https://issues.folio.org/browse/STCOM-323).
Replaces https://github.com/folio-org/stripes-components/pull/567.
- Use `reduxFormField()` for consistent logic with or without Redux Form.
- Made the props identical between `<Checkbox>` and `<RadioButton>`.
- Checked against the eHoldings acceptance tests. Found and fixed several regressions that way.
- Updated stories and readme.
Contains significant prop changes to `<RadioButton>` and `<RadioButtonGroup>`. I bumped to the next major version in `package.json` and the changelog. Consumers of those two components with Redux Form shouldn't expect any breaking changes.
> STCOM-88 Update <RadioButton> and <RadioButtonGroup> to work independently of Redux Form

- CHANGELOG.md
- lib/DropdownMenu/DropdownMenu.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/SegmentedControl/SegmentedControl.js
`react-hot-loader` prevents accurate `type` evaluations of children: https://issues.folio.org/browse/STCOM-356
By disabling these checks, these components are easier to misuse, but if they're used as intended and documented, everything should be fine.
> STCOM-356 Remove child.type checks

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/tests/Datepicker-ReduxForm-test.js
- lib/Datepicker/tests/Datepicker-test.js
Removes `excludeDates`, `ignoreLocalOffset`, and `passThroughValue`.
There's definitely more refactoring to do here (with `reduxFormField()`'s help), but we get some nice deletions out of this.
> Remove deprecated props from Datepicker

- lib/Callout/Callout.js
Introduced in https://github.com/folio-org/stripes-components/pull/633; was causing an ESLint ordering error.
> Fix react/sort-comp for Callout

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- package.json
Encountered an issue with an empty datepicker - clicking a date in the calendar would not allow me to set a date - but it worked to change the date after I entered some text in the textfield. This PR adds the `presentedValue` to the gDSFP call.
> Datepicker - update presentedValue on change

- README.md
- index.js
- lib/AutoSuggest/AutoSuggest.css
- lib/AutoSuggest/AutoSuggest.js
- lib/AutoSuggest/index.js
- lib/AutoSuggest/readme.md
With the move to `@folio/stripes`, importing from the `stripes-components` directory structure will no longer be possible.
`AutoSuggest` was using some un-exported APIs from `stripes-components`, and was in healthy enough shape to warrant moving it to `stripes-components` proper. This will help unblock https://github.com/folio-org/ui-organization/pull/133
Tests. Storybook stories.
> Move AutoSuggest into component library

- CHANGELOG.md
- index.js
- lib/Accordion/index.js
This is the only component being consumed by `ui-eholdings` that wasn't already exported.
> Export DefaultAccordionHeader

- index.js
Changes for the conversion to `stripes v1.0.0`
* added exports of functions from `util` directory as needed by core-platform modules.
* add exports of a few named exports from `<FilterGroups>` - these should definitely go to stripes-smart-components as they relate most to the functionality of `SearchAndSort`
> Update exports for stripes-v1.0.0 usage

- CHANGELOG.md
- lib/MetaSection/MetaSection.css
The `<MetaSection>` was a little large for its context. I've shrunk it down from `font-size-medium` to `font-size-small`.
> Shrink MetaSection font sizes

- CHANGELOG.md
- lib/KeyValue/KeyValue.css
- lib/sharedStyles/form.css
`<KeyValue>` is essentially used like a form element, with a label... except the margins were inconsistent for the label/key element. I noticed in eHoldings when I tried to do
```
<KeyValue>
<Button />
</KeyValue>
```
and the spacing was a lot tighter than I expected. Labels had 8px margin bottom, while the key had 2px.
I met in the middle - now `label`s and the "keys" of `<KeyValue>` both have a `0.25rem` (`4px`) bottom margin.
> Make label margins consistent

- lib/Layer/Layer.js
- package.json
- util/trapFocus.js
The existence of this bug/PR illustrates the difficulty with accessibility and focus-management that comes with the layer-based routing setup ( mentioned here: https://issues.folio.org/browse/STRIPES-537). Inventory uses `<Layer>` in a slightly different way than most other ui-modules since it leans on both a URL path **and** a `layer` query parameter - it creates a situation where there is more than one Layer component present. Both have focus-trapping, and so they battle! This results in the recursion.
While the transition of focus is still maintained by this PR, the accessibility only gets weaker as more layers are present and more focusable elements. A real fix under current conditions would involve a top-layer 'manager' component for these along with a corresponding PR to insert it …
> STCOM-366 Focus-trapping with multiple layers.

- CHANGELOG.md
- lib/Selection/SelectList.js
- package.json
`<SelectList>` was generating a console error since a string attribute was being applied where a boolean would be best. Not a functional bug, just a noisy one - still, the less noise, the better...
> STCOM-369 quiet console warnings from SelectList

- CHANGELOG.md
- lib/Layout/styles/padding.css
Both `padding-start-gutter` and `padding-end-gutter` were just setting the `padding-left` property. Changed it so `padding-end-gutter` now sets the `padding-right` property instead.
> Layout: Fixed padding-end-gutter

- CHANGELOG.md
- lib/EntrySelector/EntrySelector.js
- package.json
Use a CSS class to indicate when this component is rendered with one or
more entries. This component may re-render once results become
available, but there's no easy way for a test to know that because there
are no element classes, no element ids, nothin'. It would have to parse
some crazy long nested structure of divs and anchors, which feels pretty
nasty.
In fact, the loan renewal tests in platform core sometimes blow up when
trying to click on non-existent links because they don't have a good way
to test whether those links are present. This helps.
Refs [UITEST-55](https://issues.folio.org/browse/UITEST-55)
> indicate whether `<EntrySelector>` has any entries

- lib/Button/Button.css
The pane header "New" button had a bit too much margin.
> Reduce pane header button margin

- lib/MultiColumnList/MCLRenderer.css
Attempts to solve the same problem as https://github.com/folio-org/stripes-components/pull/669, where the `MultiColumnList` headers are not aligned with their column content.
Maintains `1rem` (`16px`) gutter, not `15px`.
> Fix MCL header padding

- lib/variables.css
The icon color is failing when tested with contrast ratio tools so we are making it a bit darker.
This should fix the icon related issues in:
https://issues.folio.org/browse/STCOM-377
> Updated icon color variable to 62% black to improve contrast

- lib/Icon/Icon.css
- lib/Icon/Icon.js
- lib/Icon/tests/Icon-test.js
- lib/Icon/tests/interactor.js
The size of the icon should not affect the font-size of the label.
E.g. when using an `<Icon>` inside of a `<Button>` we need the label to enherit the font-size from the button.
I also adjusted the spacing between icon and label.
> Move icon sizing to SVG instead of root element

- lib/IconButton/IconButton.css
- lib/IconButton/IconButton.js
- lib/Selection/Selection.css
Since we removed the white-space from icons, the icon and the badge was a little bit too close to each other.
This PR adds some spacing in a RTL compatible way.
> Added RTL compatible spacing between Icon and Badge

- CHANGELOG.md
- package.json
* Make label margins consistent
* Add ability to filter items in EntrySelector. Fixes STCOM-367.
* Resolve issue recursion issue with `trapFocus` with multiple `<Layer>`s. STCOM-366.
* Clear console noise from `<Selection>`/`<SelectList>`. STCOM-369.
* Removed title attribute from AppIcon (STCOR-268) and minor line-height fix
* Fixed `<Layout>`'s `padding-end-gutter` rule.
* Use a CSS class to indicate whether `<EntrySelector>` has any entries. Available from v4.2.2.
* Added more flexbox classes to `<Layout>`. Available from v4.2.4.
* Resize icons
* Export `<NavListItem>`
> Release v4.3.0

- package.json
- yarn.lock
This was the last warning left in the ` Linking dependencies` stage of `yarn install`, and this change makes it go away 🎉 :
```
warning "@folio/stripes-cli > @folio/stripes-core > @folio/stripes-components@3.3.0" has unmet peer dependency "@folio/stripes-form@^1.0.0".
```
> Upgrade stripes-cli and regenerate lockfile

- lib/InjectIntl/InjectIntl.js
- lib/ReduxFormField/ReduxFormField.js
- package.json
- yarn.lock
When prepping a PR to `react-intl` to share our `forwardRef` usage upstream, I noticed some sloppiness around how we label components using `InjectIntl`. 
- Now components using `injectIntl()` that don't opt into `withRef` have one less layer of component tree.
- `hoist-non-react-statics` helps with sending around `displayName`.
- The `intlPropName` change just aligns our fork closer to the upstream `InjectIntl`.
> Improve dev tools output for forwardRef

- CHANGELOG.md
- lib/variables.css
hsl and rgba
when all we want is opaque white
call `color(hex)`, the others, nay,
to paint the background with delight
> `color()` chokes on rgb/rgba; use hex

- CHANGELOG.md
- lib/Button/Button.js
Best not to call a function that doesn't exist.
> check presence of props.onClick before calling it

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.js
- lib/Checkbox/Checkbox.js
- lib/Datepicker/Datepicker.js
- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/MultiSelection.js
- lib/RadioButton/RadioButton.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/RepeatableField/RepeatableField.js
- lib/Select/Select.js
- lib/Selection/Selection.js
- lib/Selection/SingleSelect.js
- lib/TextArea/TextArea.js
- lib/TextField/TextField.js
- lib/Timepicker/Timepicker.js
- package.json
Expands prop type validation for `error`, `label`, and `warning` props to make internationalization easier (more `<FormattedMessage />` from `react-intl`, less `formatMessage()`).
Set up for `v4.3.1` release.
> Allow node prop types for labels and validation messages

- lib/Icon/stories/style.css
Fixes
```
WARNING in ./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/lib??ref--4-2!./lib/Icon/stories/style.css
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/jeffrey/Sites/folio/stripes-components/lib/Icon/stories/style.css:30:3: variable '--font-size-x-small' is undefined and used without a fallback
```
> Fix missing CSS var import in Icon story

- lib/Datepicker/readme.md
- lib/Timepicker/readme.md
Tests related to dates were found to be failing for some people in other timezones. Upon investigating they were rightfully failing because UTC dates were incorrectly being formatted as local dates. This was happening because `moment()` assumes values to be local time when there is no timezone information. So dates such as `12/01` were being formatted as `11/30` when viewed in timezones east of UTC.
Related: [STCOR-265](https://issues.folio.org/browse/STCOR-265)
Working with dates can be a nightmare. When comparing or manipulating dates, it is safest to always work in UTC and let internationalization helpers handle formatting the display for local timezones. This PR adds a short description to the `Datepicker` and `Timepicker` docs and links to `moment.utc()`.
The `Datepicker` and …
> Add documentation reference for moment.utc

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.js
- lib/Checkbox/Checkbox.js
- lib/MultiSelection/MultiSelection.js
- lib/RadioButton/RadioButton.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/ReduxFormField/ReduxFormField.js
- lib/ReduxFormField/readme.md
- lib/Select/Select.js
- lib/Selection/SingleSelect.js
- lib/TextArea/TextArea.js
- lib/TextField/TextField.js
- lib/Timepicker/tests/Timepicker-test.js
`ReduxFormField` is a temporary tool introduced to help decouple `stripes-components` from the `redux-form` API.
It provides a facility for mapping the `input` and `meta` passed along by `redux-form` into the props expected by our components.
I realized there was a huge amount of overlap in the `input` prop - there wasn't really a reason to not pass along all of that prop every time.
- Spread the `input` prop onto every component hooked up with `ReduxFormField`.
- Remove `input` mappings from relevant components.
This will make a transition to a future without `ReduxFormField` smoother.
> Simplify ReduxFormField usage

- lib/Accordion/headers/FilterAccordionHeader.js
- lib/Avatar/Avatar.js
- lib/Datepicker/Calendar.js
- lib/Datepicker/DayButton.js
- lib/EntrySelector/EntrySelector.js
- lib/Icon/Icon.js
- lib/Icon/tests/Icon-test.js
- lib/Icon/tests/interactor.js
- lib/MultiColumnList/MCLRenderer.js
- lib/PaneHeader/PaneHeader.js
- lib/TextField/TextFieldIcon.js
Resolves https://issues.folio.org/browse/STCOM-296
The `title` attributes on `Avatar`, `Icon`, and `TextFieldIcon` have been deprecated and replaced by `ariaLabel`. `title` will still continue to work for now.
> STCOM-296 Repeal and replace title attributes

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.css
- lib/AutoSuggest/AutoSuggest.js
- lib/AutoSuggest/readme.md
AutoSuggest is pretty prescriptive about what it expects from its parents and as a result, wasn't flexible enough to use as-is in the ERM modules. It currently drives everything off of the `value` field of an object which is limiting.
This PR gives us the ability to custom render the value and dropdown items, as well as construct more elaborate searches.
Going forward, this component could use a pass in the beauty parlour but I'm hoping to get at least this _functionality_ in now since I'd like to use it asap.
> AutoSuggest: Added custom search/render functionality

- lib/AutoSuggest/AutoSuggest.css
Quick follow-up to #704. Noticed that you couldn't see all items in the dropdown list if it went past the end of the page and there weren't any scrollbars. There's a more accurate way of handling this where we'd calculate how much spare room vertically we have in JS (perhaps also throwing the dropdown _above_ the textfield) but I stuck with the simple fix for now.
> AutoSuggest: Fixed bug where not all <li>s were visible

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
- package.json
Previously, the row-count was included in the `title` attribute of the
table header, but `title` isn't a11y-friendly so we've been getting rid
of it. Nonetheless, we still need access to the row-count
programmatically for tests, so here it is.
An alternative would be to include a `data-test-row-count` attribute and
to include `data-test-*` attributes in our builds, but we don't have
those builds yet.
> include data-total-count attribute in output

- lib/AutoSuggest/AutoSuggest.js
- lib/TextField/TextField.js
AutoSuggest was constantly throwing two errors onto the console.
For reference, the component hierarchy is: AutoSuggest > Downshift > TextField
1. When the TextField lost focus (on blur), Downshift was trying to access the `event` in its blur handler. TextField wasn't passing on the `event` so Downshift threw TypeErrors when it tried to access the event properties. Fixed by passing along `event`.
2. React complained that it didn't know what the `innerRef` property was. We're setting it on a `ul`, so we [don't actually _need_ to be setting `innerRef`](https://github.com/paypal/downshift#getmenuprops). Removed it.
> AutoSuggest: Fixed bugs where AS would throw errors

- .storybook/config.js
Adds more locales to storybook.
There are some question marks around how to handle country-specific translations (`es_ES`, `fr_FR`, etc.), so I ignored that wrinkle in this round.
The locale bootstrapping for `storybook` could use a refactor to just read the directory of translation files, but I just continued down the same hard-coded path.
> Add more translations to storybook

- CHANGELOG.md
- lib/Pane/Pane.js
Allows `<Pane>` to be a `<form>` and applies any props to the top level element, so we won't have to wrap `<Pane>` in any other kind of tag.
Current spots where this is a problem:
- https://github.com/folio-org/ui-inventory/pull/353
- eHoldings settings: http://folio-snapshot.aws.indexdata.com/settings/eholdings/knowledge-base
This moves the `...rest` props spread from `<PaneHeader>` to the top level element of `<Pane>`. May have unknown side effects.
> Introduce tagName prop on Pane

- CHANGELOG.md
- lib/Modal/Modal.js
- lib/Modal/readme.md
- lib/Modal/tests/Modal-test.js
It should be possible to give a `label` for the `<Modal>` header that's a `node`, not just a `string` (makes dealing with `react-intl` `<FormattedMessage>` much easier).
But `aria-label` needs to be a string, and `label` was being reused for both purposes.
- Split the `ariaLabel` and `label` props.
- Accept a `node` for `label`.
> Update Modal propTypes

- CHANGELOG.md
- package.json
- yarn.lock
Raise depended version of stripes-react-hotkeys to include new functionality put to use in UI-users [#557](https://github.com/folio-org/ui-users/pull/577)
Conformed publish/build setup in s-r-h to be closer to that of the upstream repo. This was similar to the work performed on the fork of react-big-calendar, and sets us up for smoother transition to an official fork of `react-hotkeys`
> STCOM-383 Hotkeys update

- lib/EntrySelector/EntrySelector.js
Makes passing in a `<FormattedMessage>` less chatty.
> Accept nodes for renderable EntrySelector props

- lib/Button/Button.js
`props.to` wasn't defined, until now.
> add missing prop

- lib/Accordion/ExpandAllButton.js
- lib/ConfirmationModal/ConfirmationModal.js
- lib/IconButton/IconButton.js
- lib/InfoPopover/InfoPopover.js
- lib/Layer/Layer.js
Follow on to #693, expanding prop type validation for various button
labels and other labels to make internationalization easier, using
`<FormattedMessage />` in favor of `formatMessage`.
> allow PropTypes.node for labels

- lib/Pane/Pane.js
- lib/PaneHeader/PaneHeader.js
- package.json
The deprecation console.warn was shown a lot of times in console.
Now using the 'deprecated' function from prop-types-extra to indicate that the `actionMenuItems`-prop is deprecated which only warns once pr. instance.
> Updated deprecated warning for actionMenuItems-prop

- CHANGELOG.md
- lib/InfoPopover/InfoPopover.js
- lib/InfoPopover/readme.md
- translations/stripes-components/en.json
1. Extend `InfoPopover` component to make it more flexible. Add new props `contentClass`, `iconSize` and `allowAnchorClick `.
> UIDATIMP-5

- lib/Datepicker/Calendar.js
- lib/Datepicker/DayButton.js
Prevents:
```
Warning: Invalid ARIA attribute `ariaLabel`. Did you mean `aria-label`?
in button (created by FormattedMessage)
```
Regression introduced in https://github.com/folio-org/stripes-components/pull/703.
> Fix calendar aria labels

- lib/Pane/readme.md
Added a more specific `Pane Action Menu` example in the Pane-readme.
> Updated Pane Action Menu example in Pane readme

- lib/Checkbox/Checkbox.js
- lib/RadioButton/RadioButton.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/Select/Select.js
- lib/TextArea/TextArea.js
- lib/TextField/TextField.js
Inline validations are not being announced by screen readers.
Wrapping error messages in `<div role="alert">` will announce the errors aloud when they appear. Some suggested approaches looked for some focus management, but I would rather wait for feedback before we manipulate focus (seems like it should be the user's choice on whether or not to go back now or wait).
Additionally, `aria-invalid` was added to the fields which AT's will also announce when the field is focused.
> STCOM-403 Accessible validation messages

- CHANGELOG.md
- package.json
* Deprecate `<EntrySelector>`
* Introduce `showUserLink` prop on `<MetaSection>`
* Deprecate `<IfInterface>` and `<IfPermission>`, STCOM-357
* Extend InfoPopover with new props (UIDATIMP-5).
> Release v4.5.0

- lib/AutoSuggest/AutoSuggest.js
- lib/Checkbox/Checkbox.js
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/readme.md
- lib/RadioButton/RadioButton.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/Select/Select.js
- lib/Select/stories/BasicUsage.js
- lib/Selection/SingleSelect.js
- lib/TextArea/TextArea.js
- lib/TextArea/stories/BasicUsage.js
- lib/TextField/TextField.js
- lib/TextField/stories/BasicUsage.js
- lib/TextField/tests/TextField-ReduxForm-test.js
Move toward the end goal of building our form field components agnostic of any form state library.
- The `touched` styles were no longer in effect, so no `touched` props were doing anything.
- Always declare `dirty`, `error`, `valid`, and `warning` mappings in the same way.
- Removed `loading` mapping. `asyncValidating` was part of Redux Form, but is not part of React Final Form. Consumers of those components can still use the `loading` prop as needed.
In the very near future we'll be able to remove the `reduxFormField` HOC completely. Instead, hooking up the form state to form field components would be opt-in. This will provide more expressiveness for composing forms in more use cases. It will be more verbose, but consuming developers will have more options according to the needs of …
> Consistently declare redux form field mappings

- lib/Button/Button.css
- lib/Button/Button.js
- lib/PaneHeader/PaneHeader.css
- lib/PaneHeader/PaneHeader.js
Axe-reported issues in color contrast issues led me to investigate - based on the Axe project's issues/PR's these reports are often flags for deeper issues. It turns out that the CSS rule `pointer-events: none` can cause textual elements to not be accurately compared with their backgrounds. Buttons and Pane headers/dropdowns have `pointer-events: none` applied to keep inner elements from stealing focus as part of the way that focus styling is set up in the system.  This only appears to be an issue in the case that an inner element of a `<button>` is actually focusable (has a tab index, implicit or otherwise.) Testing on Chrome and Firefox for Windows, non-focusable elements didn't affect the appearance of interaction styles and, more importantly, clicks were not blocked from the …
> A11y clean-up - aria button roles, color contrast issues.

- lib/AutoSuggest/AutoSuggest.js
- lib/Checkbox/Checkbox.js
- lib/FormField/FormField.js
- lib/FormField/index.js
- lib/FormField/readme.md
- lib/FormFieldArray/FormFieldArray.js
- lib/FormFieldArray/index.js
- lib/MultiSelection/MultiSelection.js
- lib/RadioButton/RadioButton.js
- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/ReduxFormField/index.js
- lib/ReduxFormFieldArray/index.js
- lib/RepeatableField/RepeatableField.js
- lib/Select/Select.js
- lib/Selection/SingleSelect.js
- lib/TextArea/TextArea.js
- lib/TextField/TextField.js
I have a branch of `ui-eholdings` where I've completely replaced `redux-form` with `react-final-form`. With `redux-form`'s project health in doubt, we should be actively encouraging use of alternative form state management solutions that meet our needs better. Related to https://issues.folio.org/browse/STCOM-269
- Rename `reduxFormField()` and `reduxFormFieldArray()` to `formField()` and `formFieldArray()`
- Updated `formField()` readme to add links to React Final Form docs.
> STCOM-269 Generically rename to formField()

- lib/Accordion/Accordion.css
According to [UIEH-574](https://issues.folio.org/browse/UIEH-574), there was a bug with scrolling in the eHoldings app. It also impeded the looking of the whole list of packages ([UIEH-576](https://issues.folio.org/browse/UIEH-576)).
Accordion wrapper had a border, which disappeared when the title of the accordion was becoming sticky. The problem was resolved with adding border to not only the sticky mode, but in the usual either. 
This PR also resolves [UIEH-576](https://issues.folio.org/browse/UIEH-576).
> UIEH-574: Resolve scrolling bug

- CHANGELOG.md
- README.md
- lib/AutoSuggest/AutoSuggest.js
- lib/Datepicker/Datepicker.js
- lib/SearchField/SearchField.js
- lib/TextField/Readme.md
- lib/TextField/TextField.js
- lib/TextField/stories/BasicUsage.js
- lib/TextField/tests/TextField-test.js
- lib/Timepicker/TimeDropdown.js
- package.json
Various instances where ref's to a `<TextField>`'s rendered input element have been required by modules with shakey success due to ref complications with HOC's and not-so-great ref-forwarding.
An `inputRef` prop on `<TextField>` that will accept a ref and pass it straight through to the `<TextField>` component.
Deprecate `<TextField>`'s methods `getInput()` and `focusInput()` in favor of using the `inputRef` prop directly.
Components within `stripes-components` that depend on the deprecated methods have been updated to use the new prop.
Added a long-needed documentation for `<TextField>`
Also added a prop to support additional labeling options - `AriaLabelledBy`.
Update the modules that have made use of the `focusInput()` method - `ui-checkin` and `ui-checkout` are mentioned in the JIRA …
> STCOM-372 expose ref prop for TextField - "inputRef"

- lib/Selection/SelectList.js
- lib/Selection/SingleSelect.js
`SelectList` was already complaining that `SingleSelect` was passing it a node by default for the `emptyMessage` prop, so this gets rid of that warning. Additionally, it adds propType support for passing `emptyMessage` nodes directly into `Selection`.
> Selection: Added support for emptyMessages of node proptypes

- lib/EmptyMessage/EmptyMessage.js
- lib/EmptyMessage/readme.md
Updated EmptyMessage to simply allow for children of type 'node' instead of strings/elements.
> Updated EmptyMessage children prop-type to 'node'

- CHANGELOG.md
- lib/SegmentedControl/SegmentedControl.js
- lib/SegmentedControl/readme.md
The consensus from https://github.com/folio-org/stripes-components/pull/761 was that we'd deprecate `<SegmentedControl>`.
Least path of resistance: existing modules using it can clone `<SegmentedControl>` to their own repos. In most cases it'll make sense to just use `<ButtonGroup>` with `buttonStyle` coming from state or the router.
Closes https://issues.folio.org/browse/STCOM-415
> STCOM-415 Deprecate SegmentedControl

- lib/TabButton/TabButton.js
The `<TabButton>` component is being phased out.
Searching the FOLIO organization on GitHub showed no trace of this component being used anywhere. As far as I know, the tab layout design pattern in which this component was used in, is no longer used and it's not planned to be implemented again.
This change should prevent anyone from using it in any new code – and should there be other repos out there using it they will be notified so that they can remove it.
I will follow up with a PR against the next major release (5.0.0) to remove it completely.
> STCOM-421 Add deprecation warning for TabButton

- index.js
Exported the `ButtonGroup` component created in https://github.com/folio-org/stripes-components/pull/761
(I'm assuming we didn't _purposely_ skip exporting it for some Q4-release-related reasons.)
> Exported ButtonGroup from package

- lib/ConfirmationModal/ConfirmationModal.js
- lib/ModalFooter/ModalFooter.css
- lib/ModalFooter/ModalFooter.js
- lib/ModalFooter/examples/ModalFooterExample.js
- lib/ModalFooter/readme.md
- lib/ModalFooter/tests/ModalFooter-test.js
Changes the ergonomics of `<ModalFooter>` to accept children instead of prop objects.
- Makes adding `data-test-*` attributes less awkward.
- Makes it possible to construct a `<ModalFooter>` with more than two buttons. I don't know of any current cases of that, but it'll probably come up.
- Makes it possible to change order of the buttons - that might be desired for modals asking to confirm destructive actions.
- Adjusted button margins a hair to look better on narrow screens.
Very similar to https://github.com/folio-org/stripes-components/pull/761
We probably want to leave the deprecations for `primaryButton` and `secondaryButton` in until `stripes` `v3.0.0`.
> Render ModalFooter children

- CHANGELOG.md
- lib/Selection/SelectList.js
- lib/Selection/Selection.css
- lib/Selection/SingleSelect.js
On small screens, Selection misbehaves since the ref for its filter field doesn't quite get reconciled before the state of its root updates.
Having the SelectList component actually focus its own filter input on mount assures the presence of the ref rather than leaning on the parent component's state update.
> STCOM-433 Selection focus management.

- lib/FilterGroups/FilterGroups.js
As deprecated pattern `formatMessage` was replaced with `<FormattedMessage/>`, currently it sends warnings to console relating to wrong propTypes for a label in `<FilterGroup/>` and `<FilterGroup/>`.
- the label in propTypes was changed from 'string' to 'node'
> Resolve propTypes warnings for filterGroup

- lib/Timepicker/TimeDropdown.css
- lib/Timepicker/TimeDropdown.js
**Ticket:** https://issues.folio.org/browse/STCOM-437
Webkit desktop browsers add little up/down arrows to number inputs. This caused the input values to be pushed out when focusing the inputs within the Timepicker dropdown.
In this PR I removed those controls since we already have arrow controls for these inputs. I also made some minor style adjustments: Centering number in inputs and properly vertically aligned the colon between the inputs.
> STCOM-437: Remove controls from Timepicker inputs + minor style updates

- lib/ExportCsv/ExportCsv.js
- lib/ExportCsv/exportToCsv.js
- package.json
Moves `exportToCsv()` from `stripes-util` into `stripes-components` itself.
Refactor `ui-requests` to use the `<ExportCsv>` component instead of the `stripes-util` function: https://issues.folio.org/browse/STUTL-3
> Remove stripes-util dependency

- lib/AppIcon/AppIcon.css
Fixed AppIcon img offset bug when browser font-size is set to larger than default.
**Issue:** https://issues.folio.org/browse/STCOM-445
> STCOM-445: Fix minor AppIcon bug

- lib/MultiSelection/MultiSelectOptionsList.js
By default, `MultiSelection` passes a react-intl `FormattedMessage` to `MultiSelectOptionsList` which then throws proptype warnings. This correctly sets a `node` proptype instead.
> MultiSelectOptionsList: Support node proptype for emptyMessage

- lib/TextField/TextField.js
**Problem**
If no inputRef prop is applied, TextField currently focuses *the last TextField instance rendered when the 'clear' button is clicked... This is due to the createRef call happening in static default props rather than the constructor. 
**Approach** 
Modify ref conditional so that the ref stays local to the component. I knew the clean implementation that existed before was too good to be true 😭
> Fix issue with TextField focusing outside of itself when Clear pressed

- lib/Button/Button.css
- lib/Button/Button.js
- lib/Button/stories/styles.js
While working on something else I needed a way to left align the content of a `<Button>`. I looked in the readme and found that there already was a prop for this – great!
_The problem:_ the align-prop wasn't really doing anything.
In this PR I added alignment functionality for the `<Button>`-component. I also removed a reference for `css.floatEnd` which aren't defined in `Button.css` anymore and probably has not been for a while.
> Make <Button> align-prop great again

- lib/ButtonGroup/ButtonGroup.js
Checking `.type` doesn't work when using `webpack-dev-server` since all components get wrapped in an HOC.
> ButtonGroup: Remove propTypes check

- README.md
- lib/AppIcon/AppIcon.js
- lib/PaneHeader/PaneHeader.js
`<AppIcon>` is the last place in `stripes-components` which relies on `withStripes`. That's why we want to move it to `stripes-core`.
* `<AppIcon>` was refactored to a class component in order to be able to show a deprecation message in its constructor
* `<PaneHeader>` component was changed to use `stripes-core`'s `<AppIcon>`
This PR can only be merged after [this one](https://github.com/folio-org/stripes-core/pull/567) (since currently there is no `AppIcon` in `stripes-core`, which can also make tests fail)
[JIRA issue link](https://issues.folio.org/browse/STCOM-411)
> STCOM-411: Setup deprecation message for <AppIcon>

- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/tests/interactor.js
Until we're able to import interactors into ui-modules, we have to stick to selecting around in the rendered DOM in order to build tests.
Testing with MCL currently has some challenges due to indistinct classnames making it difficult to select particular elements to assert on. This PR remedies that by prefixing all of the major class names with "mcl".
> ClassNames in MCL use 'mcl' prefix

- lib/MultiColumnList/MCLRenderer.css
I noticed a minor visual bug with selected odd rows. The odd row styles were overwriting the selected-styles.
> Fixed selected styles on odd rows

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
Use columns' static labels, i.e. the keys from `props.columnMapping`,
rather than their translated labels, i.e. the values from
`props.columnMapping`. This means the sort parameter in the querystring
will remain constant regardless of locale.
Refs [STSMACOM-93](https://issues.folio.org/browse/STSMACOM-93), [UIU-479](https://issues.folio.org/browse/UIU-479), [UIU-864](https://issues.folio.org/browse/UIU-864)
Replaces #841
> use static column label for sorting

- CHANGELOG.md
- lib/fonts.css
- lib/global.css
The variable version of our main font "Source Sans Pro" are causing multiple issues.
I have looked into how we could fix this – without completely removing the variable font – but without luck. If anyone has an idea of how we can fix the variable fonts I would appreciate a comment or a PM =)
The main advantage of a variable font is the reduced file size which is great. But if it's at the cost of having multiple issues around the app then I think we should disable it (as my PR suggests) – and maybe get back to it at a later point.
**Issues that I know of:**
- Select fields are crashing in Safari on Mac (https://issues.folio.org/browse/STCOM-434)
- Multiple scrollbars appearing when opening the app list dropdown (PC/Chrome) (https://issues.folio.org/browse/STCOM-461)
- Wrong line heights in …
> Disabled variable fonts

- lib/Accordion/withAccordionSet.js
While working on some things in the `ui-data-import` module I noticed that the accordions were given new incremented ID's every few seconds.
This is caused by the "withAccordionSet" HoC having the automatic generation of accordion ID's (if none is passed a prop) directly in the render which causes it to generate a new ID every time the accordion re-renders.
I fixed this by turning the wrapped component into a class and placed the autogeneration of ID's in the constructor.
> STCOM-475: Fix autogenerated ID's in withAccordionSet()

- lib/FilterGroups/FilterGroups.js
The previous id was similar to `clickable-filter-active-Include inactive users` which is invalid. It's impossible to reference it via dom queries. This PR changes:
`clickable-filter-active-Include inactive users`
to:
`clickable-filter-active-include-inactive-users`
> Fix group filter checkbox id

- lib/Label/Label.js
- lib/Label/readme.md
Addded tagName-prop for `<Label>` – for cases where you want the styles and functionality of the `<Label>` but don't want to render a label-element (for semantic reasons etc.).
I also added some missing propTypes.
> Add tagName-prop for <Label>

- lib/IconButton/IconButton.css
Updated color for IconButtons that renders as anchor tags to prevent the global `:visisted` style from being applied.
> Prevent :visited styles from being applied to IconButton

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
The issue here was the logic we were using with  _moment()_  instead of _moment.tz()_ wasn't considering the timezone while presenting the value. For example: we have numerous sites across users, requests and the checkin app where this wasn't functioning properly:
Example: With me in Eastern time zone and  _America/LosAngeles_ set as my tenant timezone:
In users app: the **userExpirationDate** had different dates showing up on the view vs edit page
Requests app: the **requestExpirationDate** showing the date by 1 day offset similar to the **userExpirationDate**
Also, in the checkin app, the checkin date shows a different day when the **datePicker** is opened up with default as _today_
All of these should be resolved by this PR
> use moment.tz instead of moment to show the presented value

- package.json
This fixes the issue of the RTL toggle showing on all tabs when viewing stories.
> Updated storybook-addon-rtl to the latest version

- CHANGELOG.md
- lib/Selection/SingleSelect.js
Basically, if you vary dataOptions, selectedIndex should be recomputed because the position of currently selected value may be different in the new dataOptions.
@doytch did this work in #901, which also updated the package version to 5.0.3. *But* that version was never formally tagged and released. Here, we're cherry picking it onto the v5.0 release branch so we can formally release v5.0.3 without pulling in additional feature work that was done on master in between 5.0.2 and that PR.
> Selection: Update selectedIndex

- lib/Accordion/Accordion.css
Made sure that the content within the right side of the default accordion header always is centered vertically.
> Added vertical alignment for accordion buttons

- CHANGELOG.md
- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/SelectedValuesList.js
Calling `focus()` prematurely could result in an app crash. This particularly affects small screen widths.
> STCOM-485 Check internal multiselection refs before calling focus

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/Accordion/AccordionSet.js
- lib/Accordion/stories/BasicUsage.js
- package.json
Rendered as part of an `<AccordionSet>` the "useful" `closedByDefault` prop is rendered "useless" since it fails to be considered as part of the `<AccordionSet>`'s initial state.
Pass the `closedByDefault` prop in each `<Accordion>`'s registration function to its `<AccordionSet>` and consider it in the set up of the initial accordion state.
> STCOM-480 `<AccordionSet>` fails to acknowledge 'closedByDefault' prop of child `<Accordions>`

- lib/FilterGroups/FilterGroups.js
The "=" syntax is translated to ~ regex search on database side and is very slow. Since filters search the exact key, we should use "==" syntax that translates to LIKE (equivalent to exact in most cases) and that is way faster. For example in location filtered instance search MODINVSTOR-273, we see performance improved about 30x.
> STCOM-492: change filter search to use == not =

- CHANGELOG.md
- lib/DateRangeWrapper/DateRangeWrapper.js
- lib/DateRangeWrapper/tests/DateRangeWrapper-ReduxForm-test.js
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/stories/BasicUsage.js
- lib/Datepicker/stories/DatepickerDemo.js
- lib/Datepicker/tests/Datepicker-ReduxForm-test.js
- lib/Datepicker/tests/Datepicker-test.js
- lib/Datepicker/tests/DatepickerAppHarness.js
- package.json
Numerous ones within Datepicker... logic that's passed through a few hands without really fixing very much - along with a completely neglected non-redux-form mode.
Changehandlers are now called after the input field is updated. The parameter has similar shape to the event object... this appeases typical changeHandler conventions of accepting an event object with a present `target.value`
Redux-form still receives the ISO formatted value, while non-redux-form receives the input value of the textField.
Additionally - this removed a large chunk from numerous parts of the code, including `handleSetDate()` method, the constructor, ~the entire `gDSFP()` method~. *Edit*: I brought back `gDSFP()` after thinking about it. it's good for handling situations where initial values land after the …
> STCOM-493 Datepicker not working without redux-form

- lib/FilterGroups/FilterGroups.js
Reverts folio-org/stripes-components#925
Given the current state of CQL-to-SQL translation in cql2pgsjon-java, detailed in [CQLPG-81](https://issues.folio.org/browse/CQLPG-81), #925 inadvertently broke searching for array fields. Once query translation is updated, we'll consider reinstating this PR.
> Revert "STCOM-492: change filter search to use == not ="

- lib/ModalFooter/ModalFooter.js
The previous check was failing for me because we can't compare two functions with `===`. This PR uses what react provides for us.
> Improve children prop validation in modal footer

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.css
- lib/AutoSuggest/AutoSuggest.js
- lib/AutoSuggest/tests/AutoSuggest-ReduxForm-test.js
- lib/AutoSuggest/tests/AutoSuggest-test.js
- lib/AutoSuggest/tests/interactor.js
- lib/TextField/tests/interactor.js
Fixed issue with `<AutoSuggest>` improperly accessing refs and adjusted styling.
Added tests for %100 coverage for this component ... bumping us up to 69.25% coverage for the library.
> STCOM-489-AutoSuggest-ref-bug

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
This is a difficult issue to reproduce locally.
Short of a heavier refactor for MCL, an initial approach is to stick to a minimum row-height for rendering rows and determining when more data is needed rather than an averaged row height.
This includes a fix to rowCache logic that might have been the culprit as well as the mentioned minimum row height.
With virtualization, the main goal is to render only a portion of the data in situations where displaying all of the data would be quite slow. Despite the loaded amount being more in some cases due to the height number being lower, it's still in the acceptable realm.
This fix is non-breaking and tests still pass for the component.
> UIIN-319 Potential fix for gap below results list.

- lib/Button/Button.css
- lib/Button/Button.js
I noticed a few minor issues with the button styling that I decided to fix.
This happens because of the way the focus/active/hover styles are made so when there's no inner element of the button that a z-index can be applied to, the label ends up behind the active styles. Wrapping the content in a span fixes this issue.
**Before:**
**After:**
This is fixed by making the active/hover/focus style border-radius overlay 1px smaller (5px) than the button's border-radius (6px).
**Before:**
**After:**
> Minor style updates for button

- CHANGELOG.md
- package.json
- Tested output with simple "hello world" UI app
Before:
After:
> Set sideEffects to false to enable tree-shaking

- lib/Button/Button.css
- lib/Button/Button.js
I noticed that the vertical centering was a bit off after I added the inner-element for the Button-component.
To fix this I added `display: flex;` and `align-items: center;` for the inner element to ensure proper vertical centering of the children of a `<Button>`.
> Fixed vertical centering of a <Button>'s children

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
MCLRenderer did not validate the presence of props.width which would
lead to NaN warnings in the JS console when it was undefined.
Fixes [STCOM-515](https://issues.folio.org/browse/STCOM-515)
> validate props.width

- lib/Checkbox/Checkbox.css
- lib/Checkbox/stories/BasicUsage.js
- lib/RadioButton/RadioButton.css
- lib/RadioButton/stories/BasicUsage.js
In this PR I have made some style improvements for the RadioButton and Checkbox components. The motivation for doing so is related to UIIN-503 because we need to separate the label from a RadioButton while still maintaining a decent layout.
While I was making these updates I decided to do some other improvements as well.
- Removed unnecessary margin from the `<label>`-element applied by the `<Label>`-component but not needed in this component and it was causing misalignment.
- Added a min-height of 24px which matches the min-height of form elements. This improves the layout when various form elements are placed inline with checkboxes/radio buttons
- Adjusted the margin of the labelText element of both components so that it only has margin on one side instead of both (adjusted for RTL as …
> RadioButton and Checkbox style improvements

- CHANGELOG.md
- index.js
- lib/Editor/Editor.css
- lib/Editor/Editor.js
- lib/Editor/index.js
- lib/Editor/readme.md
- lib/Editor/stories/BasicUsage.js
- lib/Editor/stories/Editor.stories.js
- lib/Editor/stories/EditorFormats.js
- lib/Editor/stories/EditorModules.js
- lib/Editor/tests/Editor.js
- lib/Editor/tests/interactor.js
- package.json
The purpose of this PR is to create the reusable  WYSIWYG editor component. 
Currently it is planned to be used in the notes create/update forms.
This component wraps the react-quill library  (see https://github.com/zenoamaro/react-quill#the-unprivileged-editor) with label and validation controls.
The react-quill library was used for the Editor and in the PR wrapped with with label and validation controls.
react-quill was chosen as the base  as is it has good support and stars on gitHub and also iut was used for in the circulation module.
Add the preview functionality to apply it to the circulation module
> STCOM-517: Create common WYSIWYG editor

- lib/MultiColumnList/MCLRenderer.js
Additional changes were made for the EndOfList component within MCL in order to handle the centering issue within data-import app. It turned out that centering feature was worked just fine only for the `SearchAndSort` component, but not just for the MCL outside of `SearchAndSort`.
> UIDATIMP-163: Make `EndOfList` component within MCLRenderer to be centered

- lib/Editor/Editor.js
This small PR fixes a not responding page after blurring the `<Editor />` component.
Now tab bindings are created on component instantiation, not inside of render method
> Fix bug on blurring <Editor /> component

- lib/Paneset/Paneset.js
- lib/Paneset/tests/Paneset-test.js
- lib/Paneset/tests/interactor.js
The paneset container element now spreads `data-*` props.
Refs [STCOM-527](https://issues.folio.org/browse/STCOM-527), [UIORG-166](https://issues.folio.org/browse/UIORG-166)
> spread data- elements onto paneset container

- lib/Paneset/Paneset.js
This component was using the width of window for the original fix, but in reality, it isn't always full-screen - it's often nested or used within a modal. This PR uses the size of the paneset's container for adjusting the child panes.
> Use width of container for sizing panes

- lib/CurrencySelect/tests/CurrencySelect-test.js
- util/currencies.js
Filter out uncommon values like currency-baskets and precious metals
that were removed from the spreadsheet attached to STCOM-532 but which
are, nonetheless, official currencies according to ISO-4217.
Refs [STCOM-532](https://issues.folio.org/browse/STCOM-532)
> filter out uncommon currency values

- lib/PaneHeader/PaneHeader.js
I noticed that the AppIcon in the PaneHeader was shrinking and being cut in half when the title became too big.
Changing the AppIcon tag to a `div` fixes this.
> Minor PaneHeader appIcon tweak to prevent icon from shrinking

- lib/Checkbox/Checkbox.js
The missing prop-type was causing the 'innerClass'-prop to be spread onto the `<input>`.
> Added 'innerClass' to <Checkbox> propTypes

- lib/RepeatableField/readme.md
- lib/RepeatableField/stories/MultipleColumns.js
I thought it would be useful to see how a row could be controlled responsively with the LayoutGrid components so I updated the example and the readme.
> Minor <RepeatableField> multiple columns documentation udpate

- lib/Icon/Icon.css
Added flex-shrink: 0; for svg inside of <Icon> to prevent it from shrinking.
> Prevent <Icon> from shrinking

- lib/Icon/icons.js
Replaced regex that is supposed to get the name of an icon from the path with a simple .slice – 
e.g. ./`my-icon`.svg -> `my-icon`. The regex was not working in Firefox.
> Removed icons regex

- lib/Accordion/Accordion.js
- lib/Accordion/tests/Accordion-test.js
- lib/Accordion/tests/interactor.js
`contentId` was inadvertently initialized to null because `initializeContentId()` set
`this.contentId` and returned undefined, but it was called in a manner
that expected a return value instead. Whoops.
Added some test instrumentation as well.
Fixes [STCOM-551](https://issues.folio.org/browse/STCOM-551)
> STCOM-551 correctly set this.contentId

- lib/FilterGroups/FilterGroups.js
`<FilterGroup>` names prop should be an array of objects not strings.
> Fix proptype for FilterGroup.names

- lib/Datepicker/Datepicker.js
This fixes an issue where `meta.touched` wasn't being set to `true` after a date was set.
> Datepicker: Fixed issue where touched wasn't set

- lib/Datepicker/Datepicker.js
`Datepicker` gets the locale from context or props, it sets its `moment` locale, and `Calendar` sets its `moment` locale, but `Calendar` never _gets_ the tenant locale from `Datepicker` since the props are passed down incorrectly! This fixes that.
> Fixed bug where Calendar days/months weren't i18nd

- lib/AutoSuggest/AutoSuggest.js
* added an optional `placeholder` prop;
* remove console warning of `React repeatable key`, value can't be `key`, since it migth not be unique
> UIORGS-71 use `placeholder`, removed console warning

- lib/Accordion/Accordion.js
- fix incorrect displaying in ui-data-import module
- leave coverage for accordion.js file more than 80%
https://issues.folio.org/browse/STCOM-558
> STCOM-558 - Fix accordion for ui-data-import module

- lib/ModalFooter/tests/ModalFooter-test.js
`ModalFooter` can receive buttons either via `children` or with `primaryButton` and `secondaryButton` props.  `primaryButton` and `secondaryButton` props are deprecated and not covered by tests. If someone is sure that they are not used anywhere and can be removed, please let me know. For now, I'm adding some more tests covering the case when those deprecated props are used.
> STCOM-546: increase ModalFooter code coverage

- CHANGELOG.md
- lib/Pane/Pane.js
- lib/Pane/readme.md
- lib/Pane/stories/Pane.stories.js
- lib/PaneFooter/PaneFooter.css
- lib/PaneFooter/PaneFooter.js
- lib/PaneFooter/index.js
- lib/PaneFooter/readme.md
- lib/PaneFooter/stories/BasicUsage.js
- lib/PaneFooter/tests/PaneFooter-test.js
- lib/PaneFooter/tests/interactor.js
- translations/stripes-components/en.json
Create element with Save and Cancel buttons, fixed to the bottom of a pane containing a form, with styling as shown on [link](https://xd.adobe.com/view/395087a8-d2cf-42cf-643b-e2a5ba6b4728-4f61/?fullscreen) with changes according to [story](https://issues.folio.org/browse/STCOM-429).
> STCOM-429: Fixed footer for Save and Cancel buttons

- lib/Accordion/Accordion.css
- lib/Button/Button.css
- lib/DropdownMenu/DropdownLayout.css
- lib/Headline/Headline.css
- lib/Headline/Headline.js
- lib/Headline/readme.md
- lib/Headline/stories/BasicUsage.js
- lib/Headline/tests/Headline-test.js
- lib/Headline/tests/interactor.js
- lib/MultiColumnList/MCLRenderer.css
- lib/PaneHeader/PaneHeader.css
- lib/global.css
- lib/variables.css
https://issues.folio.org/browse/UX-324
https://issues.folio.org/browse/UX-327
- Updated the bold font-weight variable to `700`
- Added a new black (`900`) font-weight
- Updated various components that still was using a hardcoded font-weight
- Deprecated "bold"-prop on `<Headline>`
- Added `weight`-prop for `<Headline>` with options: regular, medium, bold & black
- Removed unnecessary camelCase function in `<Headline>` code and updated class names accordingly
- Updated `<Headline>` tests
- Update Accordion, filter set and MCL header labels font-weight and text opaqueness (UX-327)
> UX-324 + UX-327: Font-weight updates + minor <Headline> refactor

- lib/Icon/DotSpinner.css
- lib/Icon/Icon.css
- lib/Icon/Icon.js
**Ticket: https://issues.folio.org/browse/STCOM-570**
In this PR I have made some adjustments for the `spinner-ellipsis`-icon because it had some odd flickering. I also increased the size of the icon a little bit.
We should probably extract the spinner icon into its own component later on.
> Fixed 'spinner-ellipsis' icon

- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/MultiSelection.js
When the pane was narrow, the ref was incorrectly created on the component
rather than the DOM element. `<MultiSelectFilterField>` expects to receive
`props.inputRef`, but `<MultiSelectOptionsList>` was passing `props.ref` 
instead.
Refs [STCOM-554](https://issues.folio.org/browse/STCOM-554)
> STCOM-554 apply ref correctly to avoid React stacktrace

- lib/KeyValue/KeyValue.js
- lib/KeyValue/tests/KeyValue-test.js
- lib/KeyValue/tests/interactor.js
It's super helpful to be able to set `data-test-` on KeyValue to avoid having to render unnecessary `<span>`s around the value. I assumed we didn't want to support passing absolutely anything to the children so this PR is tightly scoped.
> KeyValue: Support data-test props

- CHANGELOG.md
- lib/PaneFooter/DefaultPaneFooter.css
- lib/PaneFooter/DefaultPaneFooter.js
- lib/PaneFooter/PaneFooter.css
- lib/PaneFooter/PaneFooter.js
- lib/PaneFooter/readme.md
- lib/PaneFooter/stories/BasicUsage.js
- lib/PaneFooter/tests/PaneFooter-test.js
Support the ability to add CSS properties to the PaneFooter via the parent component according the [story](https://issues.folio.org/browse/STCOM-571).
**Screenshot**
> STCOM-571: Make PaneFooter flexible enough

- CHANGELOG.md
- package.json
Patch release to address failing unit tests in ui-users, e.g. 
```
ItemEditPage
visiting the edit user page
clicking on cancel button
✖ "before each" hook for "should redirect to view users page after click"
Chrome 76.0.3809 (Mac OS X 10.14.6)
Error: unable to find "[data-test-user-form-cancel-button]"
at $ (test/bigtest/index.js:948:11)
at CustomInteractor.get (test/bigtest/index.js:1579:18)
at CustomInteractor.$$$1 (test/bigtest/index.js:1594:31)
at CustomInteractor.<anonymous> (test/bigtest/index.js:992:22)
at CustomInteractor.<anonymous> (test/bigtest/index.js:1208:18)
at loop (test/bigtest/index.js:663:23)
validating user barcode
✖ "before each" hook for "should display validation error"
Chrome 76.0.3809 (Mac OS X 10.14.6)
Error: unable to find "[data-test-user-form-submit-button]" …
```
> Release v5.7.1

- lib/KeyValue/KeyValue.css
- lib/KeyValue/KeyValue.js
*Purpose*:
Fix for https://issues.folio.org/browse/UIOR-387
I think it's a good idea to wrap any long text value
> UIOR-387 wrap long text value

- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
Approach: Only pass defined onClick to rowFormatteron if onRowClick prop is provided.
> Bugfix: non-interactive MCL's rendering with <buttons> for rows

- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- package.json
Overlapping Rows in MCL if results filtered increases the count.
Equality of `contentData` was erroneously passing the equality check, so the check is set up to fail if either item is `undefined`
> STCOM-589 row height issue.

- lib/Editor/Editor.js
- lib/global.css
https://issues.folio.org/browse/STCOM-605
Avoid creation of an empty lines before ordered list in Editor and remove margins between lines appeared after text was created with a help of Editor.
- Add default prop `matchVisual` to Editor component config
- Add global style class `editor-preview` which reset margins of internal elements
- Apply style class on Note view page for details section in stripes-smart-components https://github.com/folio-org/stripes-smart-components/pull/632
- Apply style class on ui-circulation Settings for staff slips description section
Before
After
> STSMACOM-255: Add global class to reset all margins for editor markup in preview mode

- lib/MultiSelection/SelectOption.js
- lib/MultiSelection/ValueChip.js
to clean-up console, because it could be a string and unnecessary warning. I think `node` is more appropriate prop type
> remove warnings

- lib/MultiColumnList/MCLRenderer.js
@JohnC-80 while working on [UIREQ-112](https://issues.folio.org/browse/UIREQ-112) (reorder via drag/drop) I ran into a situation where I need to set the height of the `MCLRenderer` container to match the droppable wrapper's height. 
This PR allows us to pass a string as a height so we can pass other types of values:
https://developer.mozilla.org/en-US/docs/Web/CSS/height
It looks like the `height` inside the `MCLRenderer` already uses `string` in couple places:
https://github.com/folio-org/stripes-components/blob/master/lib/MultiColumnList/MCLRenderer.js#L1196
https://github.com/folio-org/stripes-components/blob/master/lib/MultiColumnList/MCLRenderer.js#L1204
so this just cleans it up a bit to avoid a warning from React.
> Add ability to pass container height as a string. Refs UIREQ-112

- lib/MenuItem/MenuItem.js
`MenuItem.onSelectItem` is required but was not labeled as such.
Refs [STCOM-612](https://issues.folio.org/browse/STCOM-612)
> STCOM-612 add missing prop-type

- lib/SearchField/SearchField.js
- lib/SearchField/readme.md
- lib/SearchField/stories/BasicUsage.js
- lib/SearchField/tests/SearchField-test.js
- translations/stripes-components/en.json
Here are two reasons for this PR:
* to remove default non-translated placeholders for all apps if any search index selected, it's a old known issue;
* feature request in the ticket to make these placeholders custom.
1. if placeholder prop is provided to SearchField - it will be displayed always, no matter of selected index;
2. if placeholder prop isn't provided to SearchField - we look for this prop in selected index config object. If it exists - it will be displayed as is, so any app that needs to use it should apply the same pattern as for translation of labels for SearchAndSort.
Any comments/suggestions are welcome, thank you in advance
> STCOM-613 add placeholder and translate it

- lib/Tooltip/Tooltip.css
- lib/Tooltip/Tooltip.js
- lib/Tooltip/readme.md
- Updated background color and font-size on Filip's request
- Added a console.warn for developers if the <Tooltip> trigger element is missing one or more aria-attributes
- Updated readme to inform about the a11y validation. Removed example for aria-label because we want developers to use the ID so we can ensure that the values in the tooltip are equal to the information that will be announced by the screen reader
I talked to a developer that was a bit confused about the red background color on the trigger element which is why I have updated the readme to inform about this and also added the console.warn to give some useful information.
I am aware that this console.warn will log on every render but I'm assuming that the a11y validation issue is something that you as a developer would fix …
> <Tooltip> updates

- lib/MultiColumnList/tests/interactor.js
Like the definition of `rows` below it, the interactors shouldn't consider the presence of data-loader rows when computing rowCount.
> MCL: Don't include data-loader rows in rowCount

- CHANGELOG.md
- tests/Harness.js
- tests/helpers.js
Provide `mountWithContext` with the ability to include additional
translations to those found locally.
`mountWithContext` is exported as a test helper for use by other
repositories. As such, it should be able to include the translation
strings used by those repositories when running tests in order to avoid
errors like this during testing:
```
ERROR: '[React Intl] Missing message: "ui-circulation.settings.common.delete" for locale: "en-US"'
ERROR: '[React Intl] Cannot format message: "ui-circulation.settings.common.delete", using message id as fallback.'
```
By accepting an additional optional prop, `translations`, containing an
array of `{ translations, prefix }` objects, it can now load arbitrary
translations in addition to those it finds locally.
> mountWithContext accepts translations

- CHANGELOG.md
- lib/Icon/Icon.js
@EthanFreestone found an issue where you couldn't wrap an `<Icon>` in a `<Tooltip>`. 
At first, it crashes due to the lack of a forwarded ref. Once I converted Icon to use `forwardRef`, we still needed some way of setting `aria-labelledby`. I just added support for this via another prop.
**Questions**
- Is this worth it? There is a workaround which is to wrap the `Icon` in a `<span>` and set the ref/aria-labelledby on the span instead.
- Does anyone know of a way we could be breaking a parent's expectations for what `ref` should here? I couldn't find any in the code.
- Should we _not_ add a specific `ariaLabelledBy` prop and instead do some `pickBy(rest, (_, key) => key.startsWith('aria-'))` grouping of props and apply them wholesale instead?
> Icon: Support Tooltips

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
Validate the shape of `groups.cql` before attempting to access it in
order to avoid an NPE when it is not defined.
Fixes [STCOM-623](https://issues.folio.org/browse/STCOM-623)
> STCOM-623 validate args before accessing them

- lib/Select/Select.js
https://issues.folio.org/browse/STCOM-628
Currently, `aria-labelledby` always points to label HTML element. So when there is no label, it points to nonexistent node and it causes an issue for screen readers.
Define `aria-labelledby` parameter only when label is provided.
> STCOM-628: Fix aria-labelledby parameter in Select component

- CHANGELOG.md
- lib/Dropdown/Popdown.js
- util/trapFocus.js
Two fixes:
* resolve behavior: for dropdowns within table rows clicking empty space in menu would propagate the click to the parent row. Resolved with a stopPropagation call passed to the overlay within `<Popdown>`.
* included `header` selector in `trapfocus` exclusions. This will allow the Applist and ProfileDropdown in stripes-core to continue to function if a `<Layer>` is open.
> Dropdown hotfixes

- CHANGELOG.md
- lib/Modal/Modal.js
In relation to https://github.com/folio-org/ui-plugin-find-user/pull/112, we need to have a reference to the Modal so that the condition [here](https://github.com/folio-org/ui-plugin-find-user/pull/112/files#diff-96e3556dd15eba52e6c744f5d35fd2eeR56) would resolve to true if the **X** dismissible button when in focus (when clicked), is still inside the Modal.
Previously, we were just targeting the [modal content](https://github.com/folio-org/ui-plugin-find-user/pull/112/files#diff-96e3556dd15eba52e6c744f5d35fd2eeL56) and due to this the **X** iconButton in the modals header wasn't contained in the element targeted by the modalContent `ref`, and hence the focus on the modal trigger [here](https://github.com/folio-org/ui-plugin-find-user/pull/112/files#diff-96e3556dd15eba52e6c744f5d35fd2eeR57 …
> Support ref in Modal via forwardRef

- lib/ModalFooter/ModalFooter.js
A PropTypes check for a particular component type may fail if that
component is, say, a functional component or one that returns a ref.
`PropTypes.node` allows us to detect that we're getting a renderable
thing without thinking too hard about it.
Why am I doing this? I want a clean console, and you should too.
> do not check component types

- lib/Datepicker/Datepicker.js
Clicking the calendar in the datepicker wouldn't open the calendar the first time it was clicked. The user would have to click it again.
The bug was caused by a conflicting state change - the focus event from the calender button would bubble to the input which would trigger a state change to open the calender... the click event would happen next, which triggered a toggle event - with the open state present, it closed the calender.
I gave the button an onFocus handler that stopped the propagation of the focus.
> STCOM-604 Datepicker calendar button not working the first time

- lib/SRStatus/SRStatus.js
- lib/SRStatus/readme.md
While working on a ticket for ui-users I noticed an issue where messages didn't get read by the mac screen reader utility.
I increased the timeout to 500ms for `<SRStatus>` which fixed it.
**Update:** After talking to @JohnC-80 we decided that it would make sense to make the `aria-live`-attribute controllable by a prop so I updated the component to support this and updated the readme as well.
> Increased <SRStatus> timeout

- lib/Callout/Callout.js
Sometimes it's nice to be able to control exactly when the callout disappears because it becomes no longer relevant. This tweak allows a component to use not just sendCallout but also removeCallout.
This PR lets us do things like:
```
const calloutId = sendCallout({
message: 'Preparing file for download...this may take a few minutes...',
timeout: 0
});
fetchEndpointThatTakesAWhileToGenerateAFileToDownload()
.then(downloadResponseBlob)
.then(removeCallout(calloutId));
```
> Callout: Return callout id from sendCallout

- CHANGELOG.md
- index.js
- lib/NoValue/NoValue.js
- lib/NoValue/index.js
- lib/NoValue/readme.md
- lib/NoValue/tests/NoValue-test.js
- lib/NoValue/tests/interactor.js
- translations/stripes-components/en.json
Provide a "no value" component that shows a `-` on screen and correctly
handles the `aria-label` attribute so that "no value set" is read by
screen readers.
Refs [STCOM-634](https://issues.folio.org/browse/STCOM-634)
> STCOM-634 provide NoValue component

- lib/MessageBanner/MessageBanner.module.css
**Ticket:** https://issues.folio.org/browse/UX-350
> UX-350: Right aligned the contents of <MessageBanner> when direction is RTL.

- lib/ModalFooter/ModalFooter.js
If we pass only one button to ModalFooter it raises a console PropType warning
> fix PropType for ModalFooter to support one button

- lib/MultiSelection/OptionsListWrapper.js
Hey @JohnC-80 and @rasmuswoelk I was seeing over 150 errors in ui-inventory similar to this:
````js
backend.js:6 downshift: The ref prop "ref" from getMenuProps was not applied correctly on your menu element. 
in Downshift (created by MultiDownshift)
in MultiDownshift (created by MultiSelection)
in MultiSelection (created by FormField(MultiSelection))
in FormField(MultiSelection) (created by MultiSelectionFilter)
in MultiSelectionFilter (created by InstanceFilters)
in InstanceFilters (created by SearchAndSort)
in SearchAndSort (created by Context.Consumer)
in Context.Consumer (created by WithStripes(SearchAndSort))
in WithStripes(SearchAndSort) (created by Context.Consumer)
in Context.Consumer (created by WithModule(WithStripes(SearchAndSort)))
in WithModule(WithStripes(SearchAndSort)) …
```
> Fix ref on downshift element

- lib/PaneHeader/PaneHeader.js
Fixed minor issue where we were checking for the presence of an `actionMenu`-prop (function) but not the return value which caused the action button to render even though it shouldn't and the action menu dropdown to be empty.
> Minor actionMenu bug fix

- lib/Button/Button.js
- lib/Button/tests/Button-test.js
Currently, when a `to` prop is used, `<Button>` renders a `<Link>`. `<Link>` in `react-router@v4` is a class component... so a `ref` prop returns an instance of the class. `<Link>` does have an `innerRef` prop that allows you to get to the `<a>` that it renders, which is the expected behavior, seeing as how using a ref on `<Button>` with and `href` prop or just as a `<button>` will get you a DOM node that you can use for focus management.
Break `ref` out of `sharedProps` and apply it as `innerRef` to `<Link>` and a `ref` to `button` and `anchor` rendering. 
Update tests, checking for the `tagName` of the element to be sure.
> STCOM-648 Treat button ref consistently (return a DOM node for Link as well)

- lib/Accordion/Accordion.js
- lib/Accordion/ExpandAllButton.js
- lib/Accordion/readme.md
- lib/Accordion/stories/Accordion.stories.js
- lib/Accordion/stories/ExpandAllWithinSet.js
Some modules are developed with the following pattern:
```
<AccordionSet>
<ExpandAllButton>
...Accordions
</AccordionSet>
```
Which a late change in `<ExpandAllButton>` broke...
This PR resolves that issue...
Call both a setStatus (if it exists) and then onToggle. setStatus trumps in the state update if it's the same state they're updating.
Additionally, child functions for Accordion are also now supported, passing the `open` status as a render prop. 🎉
> Call setStatus *and* onToggle if setStatus is present

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/readme.md
https://issues.folio.org/browse/STCOM-654
This PR introduces a new filter config function called `parse` which can be used to parse given filter value to CQL "by hand". This is required by:
https://issues.folio.org/browse/MODINVSTOR-453
https://issues.folio.org/browse/UIIN-968
An example usage from ui-inventory:
````js
{
name: 'discoverySuppress',
cql: 'discoverySuppress',
values: [],
parse: (values) => {
if (values.length === 2) {
return 'discoverySuppress="*"';
} else if (values.length === 1 && values[0] === 'false') {
return 'discoverySuppress="*" not discoverySuppress="true"';
} else {
return 'discoverySuppress="true"';
}
},
},
````
> STCOM-654: Introduce a new filter config function called parse

- package.json
Seeing some fantanstically false positives for `no-unused-vars` in `for...in` loops.
As mentioned in this issue: https://github.com/babel/babel-eslint/issues/791 ,upgrading `babel-eslint` from "^9" to "^10" resolves.
> Upgrade babel-eslint-dependency

- CHANGELOG.md
- lib/NoValue/NoValue.js
- lib/NoValue/tests/NoValue-test.js
- Give `<NoValue>` component users ability to pass custom text to `aria-label` attribute.
> UIEH-832 Added ariaLabel prop to <NoValue>

- CHANGELOG.md
- lib/Accordion/AccordionSet.js
Bug: initialStatus prop of AccordionSet doesn't work.
Reason: it's not accounted for when the accordion registers with the AccordionSet.
This PR fixes that.
> AccordionSet: registerAccordion should account initialStatus

- CHANGELOG.md
- lib/Datepicker/Calendar.css
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/tests/Datepicker-ReduxForm-test.js
- lib/Datepicker/tests/Datepicker-test.js
- lib/Popper/index.js
- Updated `<Datepicker>` to use `<Popper>` instead of react-tether
- Added deprecation warning for `tether`-prop
- Moved default tether props from Datepicker.defaultProps into the code so we only need to remove the block of code in the render method
- Added `modifier`- and `placement`-props and updated readme
- Fixed tests
- Moved inline styling into the stylesheet instead
> STCOM-382: Updated <Datepicker> to use <Popper> instead of react-tether

- lib/Loading/LoadingPane.js
Usually we have to pass `"fill"` in every place we use `LoadingPane`, so maybe it makes sense to put it as default option
> To avoid warnings in console that defautWidth is required

- lib/Button/readme.md
- lib/Datepicker/readme.md
- lib/MessageBanner/readme.md
@MikeTaylor made me aware of broken links in the Datepicker-readme.
These links were linking to other Storybook stories but this obviously won't work properly when viewing the component documentation directly on Github.
I changed the links to link directly to the Github readmes instead.
> Linking to GitHub readme instead of Storybook stories

- .storybook/webpack.config.js
- lib/Loading/DotSpinner.css
- lib/Loading/Loading.js
- lib/Loading/LoadingPane.js
- lib/Loading/LoadingView.js
- lib/Loading/index.js
- lib/Loading/readme.md
- lib/Loading/stories/Loading.stories.js
- lib/Loading/stories/LoadingPane.story.js
- lib/MultiColumnList/CenteredContainer.js
- lib/MultiColumnList/EndOfList.js
- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/PagingButton.js
- lib/MultiColumnList/readme.md
- lib/MultiColumnList/stories/MultiColumnList.stories.js
- lib/MultiColumnList/stories/PagingType.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- lib/MultiColumnList/tests/interactor.js
- package.json
- translations/stripes-components/en.json
Provide an opt-in path for `<MultiColumnList>` to present a "Load more" button for requesting pages one-at-a-time as an alternative to infinite scroll.
It's a cherry-pick of the commits in #1117 onto a patch branch in order to make that feature, and that feature alone, available as a patch to the [2019-q4 stripes release](https://github.com/folio-org/stripes/releases/tag/v2.12.1).
> STCOM-622 MCL 'Load More' button

- CHANGELOG.md
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/readme.md
https://issues.folio.org/browse/STCOM-662
The PR adds optional operator property that defaults to `=` (to preserve existing filters) but allows the filter to specify an alternative, i.e. `==`
> STCOM-662: Introduce a new filter config property called operator

- CHANGELOG.md
- lib/MultiSelection/MultiSelect.css
- lib/MultiSelection/OptionsListWrapper.js
**Settings --> Users --> Fee/Fine Owners**: Unable to use mouse to set Associated Service Point for Fee/Fine Owner.
Looks like `OverlayContainer` is not a parent for Settings --> Users --> Fee/Fine Owners, so I changed to a parent component `ModuleContainer`.
https://issues.folio.org/browse/UIU-1539
> UIU-1539: Add possibility to click to set Associated Service Point for Fee/Fine Owner

- CHANGELOG.md
- lib/MultiSelection/MultiSelect.css
- lib/MultiSelection/OptionsListWrapper.js
Restore mouse interaction to select items in `<MultiSelection>`. This likely broke
as part of the conversion of the internals to `Popper` from `portal`. 
Refs [UIU-1539](https://issues.folio.org/browse/UIU-1539) AKA STCOM-663
> UIU-1539 restore click interaction to MultiSelection

- package.json
The master branch version must be >= the latest released version in
order for clones in a workspace to be accepted as fulfilling the current
stripes dep on `~6.1.1`.
> bump package patch in concert with latest release

- lib/MultiSelection/MultiSelect.css
`<MultiSelection>` handled long values poorly. Now it looks better. 
Refs [STCOM-665](https://issues.folio.org/browse/STCOM-665), nee UIU-1537
> UIU-1537 MultiSelection style adjustment

- package.json
The version on master should not fall behind that on a release branch. This will cause problems in a workspace environment where `stripes-components` is cloned and checked out out to `master` and another package in the workspace has a dependency on the version in the release branch, causing yarn to see the cloned copy as behind the release branch, thus introducing a second copy into the build. And then The Bad Things happen. stop the an​*̶͑̾̾​̅ͫ͏̙̤g͇̫͛͆̾ͫ̑͆l͖͉̗̩̳̟̍ͫͥͨe̠̅s ͎a̧͈͖r̽̾̈́͒͑e n​ot rè̑ͧ̌aͨl̘̝̙̃ͤ͂̾̆ ZA̡͊͠͝LGΌ ISͮ̂҉̯͈͕̹̘̱ TO͇̹̺ͅƝ̴ȳ̳ TH̘Ë͖́̉ ͠P̯͍̭O̚​N̐Y̡ H̸̡̪̯ͨ͊̽̅̾̎Ȩ̬̩̾͛ͪ̈́̀́͘ ̶̧̨̱̹̭̯ͧ̾ͬC̷̙̲̝͖ͭ̏ͥͮ͟Oͮ͏̮̪̝͍M̲̖͊̒ͪͩͬ̚̚͜Ȇ̴̟̟͙̞ͩ͌͝S̨̥̫͎̭ͯ̿̔̀ͅ. Very Bad Things.
> bump version on master in sync with latest release

- CHANGELOG.md
- index.js
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/index.js
- lib/FilterGroups/tests/helpers/filterGroupsUsageTest.js
https://issues.folio.org/browse/STCOM-670
In order to correctly handle the issue described in: https://issues.folio.org/browse/STSMACOM-329
We need to replace current filter delimiter (`,`) and expose it via stripes-components.
This PR does just that.
> STCOM-670: expose filter delimiter

- lib/NavListItem/NavListItem.css
Changed default background color for NavListItem from transparent to 3% opaque black.
https://issues.folio.org/browse/UX-366
> UX-366: Minor style update for <NavListItem>

- CHANGELOG.md
- lib/MultiColumnList/defaultRowFormatter.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- lib/MultiColumnList/tests/generate.js
The idea is to extend [defaultRowFormatter](https://github.com/folio-org/stripes-components/blob/master/lib/MultiColumnList/defaultRowFormatter.js) to make `to`, `href` also as functions to accept `rowData.id` as a parameter. Usually, upon clicking on row item there is a need to navigate to a specific item route and for this, the `id` is needed. Because of existing limitation, other apps usually need to define their own row formatted. ([example](https://github.com/folio-org/ui-users/blob/master/src/views/UserSearch/UserSearch.js#L217)). Additionally, @doytch suggested having a similar possibility for `labelStrings`.
> STDTC-8: Allowed `to`, `href` and `labelStrings` props to be passed as function to `defaultRowFormatter`

- lib/MultiColumnList/defaultRowFormatter.js
Need to remove this from the object we'll spread onto element we're creating to prevent React from complaining with `console.error`s.
We could do some fancy `filter()` and list of keys that get excluded...but given that it's just the single solitary key for now I wanted to keep it simple and obvious.
> MCL: Remove labelstrings from DOM element

- lib/Paneset/PaneResizeContainer.js
I noticed that randomly I would get an error similar to this:
````js
in PaneResizeContainer (created by Paneset)
in Paneset (created by Context.Consumer)
in WithPaneset(Paneset) (created by ForwardRef)
in ForwardRef (created by UserDetailFullscreen)
in UserDetailFullscreen (created by UserRecordContainer)
in UserRecordContainer (created by WithProxyComponent)
in WithProxyComponent (created by WithTagsComponent)
in WithTagsComponent (created by WithServicePointsComponent)
in WithServicePointsComponent (created by Wrapper)
in Wrapper (created by Context.Consumer)
in WithConnect(Wrapper) (created by Connect(WithConnect(Wrapper)))
in Connect(WithConnect(Wrapper)) (created by ConnectedComponent)
in ConnectedComponent (created by Context.Consumer)
in WithStripes(ConnectedComponent) (created by …
```
> Check if current is present

- CHANGELOG.md
- lib/RepeatableField/tests/interactor.js
When `<ul> <li>` structure are placed inside repeatable field (see screenshot), test couldn't find the right remove item button and fails.
Change selector from `'li'` to `'[data-test-repeatable-field-list-item]'` for getting list of repeatable field to avoid issues, when another `<ul> <li>` structure are placed inside repeatable field.
[UIDATIMP-442](https://issues.folio.org/browse/UIDATIMP-442)
> Fix issue in tests with conflicting lists inside repeatable field

- CHANGELOG.md
- lib/IconButton/tests/interactor.js
- lib/MultiSelection/MultiSelect.css
- lib/Tooltip/Tooltip.js
- lib/Tooltip/tests/Tooltip-test.js
- lib/Tooltip/tests/interactor.js
https://issues.folio.org/browse/STCOM-679
- Added event listener when a tooltip is visible to enable hiding it
- Updated tests
> STCOM-679: Hide tooltip on escape

- CHANGELOG.md
- lib/SRStatus/SRStatus.js
- lib/Selection/SingleSelect.js
- lib/Timepicker/TimeDropdown.js
- lib/Timepicker/Timepicker.js
We know about the need to refactor away from deprecated react methods.
STCOM-649 exists to capture that work, and we'll do it, but for right
now we just need a cleaner console.
Refs [STCOM-649](https://issues.folio.org/browse/STCOM-649)
> STCOM-649 prefix deprecated methods with UNSAFE_

- lib/RadioButton/readme.md
Follow-up to #1282 which documented this need for checkboxes.
@JohnC-80, do you know if we need to do something special/similar when `<Field>` receives `component={RadioButtonGroup}`?
> document final-form's need for type="radio"

- lib/MultiSelection/MultiSelect.css
For `MultiSelection` which size is less than 180px, selectionToggleButton starts to get out from input field block. It's hepend when we try to resize the pane which has `MultiSelection`
or when we add this component on edit page with a small grid layout (example [CustomField - MultiSelect on User record edit page](https://github.com/folio-org/stripes-smart-components/pull/808))
The most accurate way to solve the problem so as not to change the structure of the HTML is to add the css property `max-width`
> Updated MultiSelection css for small size of input field

- CHANGELOG.md
- lib/PasswordStrength/PasswordStrength.js
A promise may return after a component has unmounted. In this case, it
should avoid calling `setState`.
> avoid setState in unmounted components

- lib/NoValue/NoValue.js
- lib/NoValue/tests/NoValue-test.js
- lib/NoValue/tests/interactor.js
- lib/TextArea/TextArea.js
- lib/TextField/TextField.js
Per [ERM-898](https://issues.folio.org/browse/ERM-898) and [ERM-899](https://issues.folio.org/browse/ERM-899), textfields and textareas fail axe a11y checks when an `id` is not provided. 
Use the/create a unique id and use that for the label's `for` and input's `id` attributes.
Per [ERM-900](https://issues.folio.org/browse/ERM-900), axe complains that `NoValue` sets an invalid `role` attribute. The `role` is unnecessary here so I've removed it.
> Ensure TextField and TextArea always have their <label> hooked up to the <input>

- CHANGELOG.md
- lib/MultiSelection/MultiSelect.css
Ticket:  https://issues.folio.org/browse/UIU-1674
> UIU-1674: fix multiselect carat not aligned when there is not enough space

- .storybook/preview-head.html
- lib/Checkbox/Checkbox.css
- lib/Checkbox/Checkbox.js
- lib/Checkbox/readme.md
- lib/Checkbox/stories/BasicUsage.js
- lib/RadioButton/RadioButton.css
- lib/RadioButton/RadioButton.js
- lib/RadioButton/stories/BasicUsage.js
- lib/variables.css
https://issues.folio.org/browse/UX-371
- Updated disabled/read-only styles for RadioButton and Checkbox
- Updated RadioButton error/warning styles to match Checkbox error/warning styles
- Removed the lock icon from read-only RadioButton and Checkbox
I had to disable the `no-descending-specificity`-rule for the CSS for both RadioButton and Checkbox. I tried making it work but it's pretty much impossible to fix the warnings unless you move CSS around in an illogical way that would do more harm than good.
> UX-371: Update disabled/read-only styles for RadioButton and Checkbox

- lib/Accordion/Accordion.js
- lib/Accordion/headers/DefaultAccordionHeader.js
- lib/Accordion/headers/FilterAccordionHeader.js
- lib/Accordion/readme.md
- lib/Accordion/stories/BasicUsage.js
- lib/MetaSection/MetaAccordionHeader.js
- lib/MetaSection/MetaSection.js
- lib/MetaSection/readme.md
- lib/MetaSection/stories/BasicUsage.js
- lib/MetaSection/stories/MetaSection.stories.js
- translations/stripes-components/en.json
https://issues.folio.org/browse/STCOM-686
- Added `headerProps`-prop for `<Accordion>` to enable passing additional props down to the header component. Updated documentation.
- Updated `<MetaAccordionHeader>`, `<DefaultAccordionHeader>` and `<FilterAccordionHeader>` to include a `headingLevel`-prop that allows for changing the header level of the internal `<Headline>`
- Added `headingLevel` for `<MetaSection>` to allow for changing the heading level of the meta section accordion heading.
- Added storybook example for `<MetaSection>`
- Replaced a hardcoded string with a localized string in `<MetaAccordionHeader>`
> STCOM-686: Allow for changing the heading level of the <MetaSection> component

- lib/Checkbox/Checkbox.css
I made a change in a previous PR that made inline checkboxes non-clickable. This update fixes that.
> Fixed an issue with non-clickable checkboxes

- lib/MultiSelection/MultiSelectResponsiveRenderer.js
- lib/MultiSelection/OptionsListWrapper.js
Sure, this looks dumb. 
But @MikeTaylor stumbled onto [this bit of information just now](https://github.com/folio-org/stripes-testing/blob/master/doc/nightmare.md#be-careful-with-multiselection) and I gotta admit, I don't love that [we have to write `:not([hidden])` here](https://github.com/folio-org/ui-inventory/pull/828/files#diff-85c813b2a76a618951639af498e3f0c9R65).
I don't want to break existing functionality obviously, so I'm just adding this attribute to be able to write selectors in a more lexically cogent manner.
> MultiSelect: Add `data-open` attr for ease of testing

- lib/Selection/SingleSelect.js
`cursoredLabel` and `cursoredValue` [here](https://github.com/folio-org/stripes-components/blob/master/lib/Selection/SingleSelect.js#L276-L277) need additional checks in the scenario when the `dataOptions` prop is an empty array. If not `dataOptions[0]` would be undefined and `dataOptions[0].label` crashes the UI currently.
Added similar checks for the `cursorObject` [here](https://github.com/folio-org/stripes-components/blob/master/lib/Selection/SingleSelect.js#L210-L211) as well 
refs STCOM-712
> Add optional chain check on the dataOptions prop, refs STCOM-712

- lib/ConfirmationModal/tests/interactor.js
For the sake of testing the header and body content of the confirmation modal, new fields in the `ConfirmationModal` interactor were added.
Without this change, apps can go with the code below though (ui-data-export uses this approach for now)
```
expect(confirmationModal.$('[data-test-headline]')
expect(confirmationModal.$('[data-test-confirmation-modal-message]')
```
but this is kind of boilerplate to repeat in apps, so it would be great to have it in the interactor here.
> STCOM-710: Extend `ConfirmationModal` interactor

- lib/Tooltip/Tooltip.js
Added proptype:
`PropTypes.shape({ current: PropTypes.instanceOf(Element) })` to triggerRef in Tooltip to stop warnings showing in ERM plugin components.
--Suggested by @aditya-matukumalli
> instanceOf(Element) added to triggerRef for Tooltip

- lib/Popover/Popover.css
https://issues.folio.org/browse/STCOM-698
This bug was introduced after I updated the location and positioning of the overlay container in stripes-core. I played around with different options regarding the CSS for the overlay container but found that while it fixed the issue of the popover, it would mess up the positioning of dropdowns in the main navigation.
Changed Popover position to fixed instead of absolute. This is tested and working. 
This is a quick fix for the bug at hand but we should consider refactoring the Popover component entirely to use the Popper component instead of custom positioning logic. This will most likely be a breaking change though.
> STCOM-698: Fixed <Popover> positioning bug

- util/languages.js
The previous implementation of languages.js included an invocation of `useIntl()` that the linter didn't like. This modifies the function to eliminate that problem.
> UIIN-829: Fix linting error in languages.js

- CHANGELOG.md
- lib/Accordion/Accordion.css
- lib/Accordion/Accordion.js
MultiColumnList has an unneeded horizontal scroll. It happens when MCL set into Accordion which closed by default. MCL row gets width of closed Accordion content which has property `position: fixed`. So in this PR some changes to fix it
- Margin(`margin: 0 0 1em 0`) was moved to `& expanded` selector because it needed only when Accordion is open.
- Position was changed from `fixed` to `static`  and `max-width: inherit` to set a correct width of parent element.
[STSMACOM-360](https://issues.folio.org/browse/STSMACOM-360)
> STCOM-719: Fix layout of inputed MultiColumnList in Accordion

- CHANGELOG.md
- README.md
- index.js
- lib/Link/index.js
- lib/TextLink/TextLink.css
- lib/TextLink/TextLink.js
- lib/TextLink/index.js
- lib/TextLink/readme.md
- lib/TextLink/stories/BasicUsage.js
- lib/TextLink/stories/TextLink.stories.js
- lib/TextLink/tests/TextLink-test.js
- lib/TextLink/tests/interactor.js
Because of potential name conflicts with the react-router-dom `<Link>`-component, we decided to rename our own link component to `<TextLink>`.
> Rename Link -> TextLink

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.js
The root cause is that `Downshift` provides wrong `aria-labelledby` attributes. At the same time we pass `label` to the `AutoSuggest`, and it works well with used textfield.
https://issues.folio.org/browse/STCOM-720
> STCOM-720 Avoid a11y error on AutoSuggest

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.js
- lib/AutoSuggest/readme.md
https://issues.folio.org/browse/STCOM-725
onStateChange is used for redux-from and onInputChange for final-form
> STCOM-725 Support AutoSuggest field in react-final-form

- CHANGELOG.md
- lib/Pane/tests/Pane-test.js
- lib/Pane/tests/interactor.js
Extend `Pane` interactor with `header` field in the scope of the [STCOM-727](https://issues.folio.org/browse/STCOM-727).
> STCOM-727: Extend `Pane` interactor with `header`

- CHANGELOG.md
- lib/SearchField/SearchField.js
- lib/SearchField/tests/SearchField-test.js
- lib/SearchField/tests/interactor.js
@JohnC-80 recently I discovered that user can hit search with some filter entered, but search might take time. So user clears the filter, clicks search again, some results are returned, but first one response comes after and rewrites results with the previous search. So maybe it's a good idea to disable fields until previous request is fulfilled, what do you think?
> disable SearchField if loading is true

- lib/Pane/tests/interactor.js
Use `scoped` for `header` field in `Pane` interactor for correctness in case of multiple instances in the scope of the [STCOM-727](https://issues.folio.org/browse/STCOM-727). Extends the work of #1353.
> STCOM-727: Use `scoped` for `header` field in `Pane` interactor

- CHANGELOG.md
- lib/MultiSelection/MultiSelection.js
- Set correct label for MultiSelection's hidden value input so it no longer violates accessibility guidelines
(STCOM-726)[https://issues.folio.org/browse/STCOM-726]
> STCOM-726: Create/Edit User Record: Multi-select custom field does not have a label

- CHANGELOG.md
- lib/SearchField/SearchField.js
- SearchField component ignores `disabled` prop. Previously `disabled` prop was passed to the input by destructuring `rest` props. Recently there's been an update which added `loading` prop that overrides `disabled`
> STCOM-730: SearchField | Field cannot be disabled

- lib/Datepicker/Datepicker.js
- lib/TextField/TextField.js
- util/nativeChangeFieldValue.js
A tiny bit of cleanup since both TextField and Datepicker manipulate the value of their rendered HTML Input in the same way. 
Additionally: setting autocomplete to 'off' by default on TextField in the hopes that it will resolve some automatic re-filling that we're seeing on iOS.
> Share nativeChangeFieldValue utility function between components

- lib/TextField/TextField.js
- util/nativeChangeFieldValue.js
More efforts to get TextField clearing on iOS... 
This time we update TextField's internal state and use the `input` event vs `onChange`.
> Use input and manually adjust state for clearing TextField

- lib/SRStatus/SRStatus.js
I originally noticed a bug in NVDA/JAWS that caused messages from being read out multiple times because they were being appended and never reset.
Once I fixed this, I noticed that the Mac screen reader did not announce the same message twice. I did some research and found out that it was possible to force this by switching between two aria-live region elements or by changing the root element of the aria-live region which forces a rerender and the Mac screen reader recognizes it as a newly inserted element.
This fixes the issue on the Mac screen reader while fixing the incremental announcement bug in NVDA/JAWS. Tested and working in all 3 screen readers.
> Fixed <SRStatus> issue on Mac screen readers

- lib/Datepicker/Calendar.js
Switch from hyphens to slashes in sample string for months and weekdays.
As we've seen in other stories, it's the formatting separator you feed it that makes all the difference.
> STRIPES-693 Datepicker functionality iOS.

- CHANGELOG.md
- lib/Select/Select.js
- package.json
[[STCOM-742]](https://issues.folio.org/browse/STCOM-742)  Select: missing required attribute after passing required property
Fix `Select` component ignoring  passed `required` property
> [STCOM-742]  Select: missing required attribute after passing required property

- lib/Callout/Callout.css
Changing the height/width to percentages makes the callout container span across the `<OverlayContainer>` instead of the viewport. This fixes the issue of the callout being slightly out of the viewport on iPad and other touch devices.
> Fix <Callout> positioning on iPad and other touch devices

- lib/Modal/Modal.css
Add position: relative; to modal root to fix the issue of non-visible modals when two modals are open at the same time.
> STCOM-733: Fix <Modal> bug

- CHANGELOG.md
- index.js
- lib/FormattedDate/FormattedDate.js
- lib/FormattedDate/index.js
- lib/FormattedTime/FormattedTime.js
- lib/FormattedTime/index.js
- util/iso8601Timestamp.js
- util/tests/iso8601Timestamp-test.js
ISO-8601 is ambiguous about how timezones in timestamps should be
formatted. In short, the spec says a timezone can be formatted as an
offset like `+HHMM` or `+HH:MM`, but the W3C opted to only require
browsers to implement the latter. Unfortunately, our backend APIs chose
to implement the former.
Some browsers handle both, and for them we are grateful. Others, like
Safari, or Chrome on iOS, do not, and for them we provide
`<FormattedDate>` and `<FormattedTime>` to provide that missing colon.
So much work for two little dots, eh? Sheesh.
Refs [STCOM-659](https://issues.folio.org/browse/STCOM-659)
> STCOM-659 provide FormattedDate, FormattedTime

- CHANGELOG.md
- util/languages.js
https://issues.folio.org/browse/STCOM-745
The language name translation code was insufficiently protected against invalid input. This is causing Inventory to crash when viewing details for specific records with bad language codes.
> STCOM-745: Fix a bug in language name translation

- lib/Selection/tests/SingleSelection-test.js
- lib/Selection/tests/interactor.js
`<SingleSelection>`  interactor throws errors when used in tests outside of `stripes-components`. This is caused by options list being rendered outside of component's markup through a portal, which causes app tests to fail when selecting `li:nth-of-child` elements
[UIEH-908](https://issues.folio.org/browse/UIEH-908)
> Fix SingleSelection interactor

- CHANGELOG.md
- lib/MultiSelection/MultiSelect.css
- lib/MultiSelection/MultiSelectValueInput.js
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/readme.md
- lib/MultiSelection/stories/BasicUsage.js
- lib/MultiSelection/stories/CustomAriaLabelledBy.js
- lib/MultiSelection/stories/MultiSelection.stories.js
- lib/MultiSelection/tests/MultiSelection-test.js
- lib/MultiSelection/tests/interactor.js
http://issues.folio.org/browse/STCOM-733
- Updated the `aria-labelledby`-prop implementation to prevent it from being applied to the hidden input and twice on the control element
- Added Storybook example for testing purposes
- Added section in readme about applying external labels for a `<MultiSelect>`
- Added aria-labelledby tests
- Minor style fix for the cursor style (before you couldn't see which option was highlighted when using arrow keys)
- Tested with NVDA, JAWS, and Mac screen reader. It seems to be working fine. The aria-labelledby is being applied to both the container, the control, and the filter input. I'm not sure if it's necessary to have it on all three elements.
You can try it out here:
https://ux.folio.org/storybook/iframe.html?id=multiselect--external-label
> STCOM-733: Fix aria-labelledby prop on <MultiSelect> + docs/examples

- .storybook/webpack.config.js
- package.json
Upgraded `postcss-custom-properties` to the latest version and added automatic CSS variables import in the storybook webpack config. This means that you no longer have to import variables into your CSS file manually. This only affects Storybook development in stripes-components.
The reason for this update is that I'm working on updating stripes-core to automatically import CSS variables from stripes-components into UI modules. For this purpose, I need a newer version of `postcss-custom-properties` and to avoid having multiple versions of this plugin included I decided to upgrade it here first.
Once my PR in stripes-core is merged, it will be possible to use CSS variables in your CSS files without manually importing them within all UI-modules and stripes-related packages.
> Upgrade postcss-custom-properties and add automatic import of CSS variables 

- lib/Datepicker/Calendar.js
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
A few have reported issues with Redux-form/ RFF validation on Datepicker. The new behavior of Datepicker moves focus to the calendar widget when it is summoned. This can cause R-F's `onBlur` handler to trigger unwantedly, causing premature validations and potentially messing up the state of Redux-form.
This PR saves an onBlur trigger for once focus leaves the entire control (setTimeout instanciated on blur, canceled if focus happens within the component)
> Datepicker: delay/cancel blur events

- lib/FormattedUTCDate/FormattedUTCDate.js
- lib/FormattedUTCDate/readme.md
- lib/MetaSection/MetaSection.js
Use the local implementations of `<FormattedDate>` and `<FormattedTime>`
in place of those from `react-intl` to allow the display of values with
non-compliant timezone formats.
Refs [STCOM-659](https://issues.folio.org/browse/STCOM-659)
> STCOM-659 make use of FormattedDate, FormattedTime

- CHANGELOG.md
- lib/MultiSelection/MultiSelectValueInput.js
- lib/MultiSelection/MultiSelection.js
Able to autofocus input in MultiSelection component
Part of [UIEH-959](https://issues.folio.org/browse/UIEH-959)
> UIEH-959: Add autoFocus property to <MultiSelection>

- CHANGELOG.md
- lib/KeyValue/KeyValue.js
- lib/KeyValue/tests/KeyValue-test.js
https://issues.folio.org/browse/STCOM-758
Guys, what do you think of displaying NoValue here? In the ticket we have a requirement to do that and it looks like a FOLIO UX guideline to display no value as hyphen.
> STCOM-758 display KeyValue with NoValue for undefined and empty strings

- CHANGELOG.md
- lib/Accordion/headers/FilterAccordionHeader.js
[STCOM-760](https://issues.folio.org/browse/STCOM-760)
`FilterAccordionHeader` ignored `headerProps` property passed from `Accordion`
> STCOM-760: added headerProps property to FilterAccordionHeader

- CHANGELOG.md
- package.json
`moment` is already provided by the platform as both a dep and in a
resolutions entry so this is a bit of a formality, but it's a good
formality.
Refs [STCOM-761](https://issues.folio.org/browse/STCOM-761), [STRIPES-702](https://issues.folio.org/browse/STRIPES-702)
> STCOM-761 move moment to peerDependencies

- CHANGELOG.md
- lib/Timepicker/tests/Timepicker-test.js
Comparisons between times from a specific timezone and times in UTC must
accommodate DST.
> Handle DST in timepicker tests

- CHANGELOG.md
- lib/Checkbox/tests/interactor.js
[STCOM-777](https://issues.folio.org/browse/STCOM-777)
Add `isDisabled` propery to `CheckboxInteractor`
> STCOM-777: Add isDisabled property to CheckboxInteractor

- CHANGELOG.md
- lib/Dropdown/Popdown.js
- lib/Dropdown/tests/dropdown-test.js
- lib/Dropdown/tests/interactor.js
- lib/Modal/Modal.css
Dropdown would just look at its open prop and feel like it would need to move focus when state changes occurred outside...
Dropdown only moves focus to the menu if the trigger is clicked/focused. The focus changes here were done with the keyboard, so that still works...
> STCOM-778 Dropdown only uses focusHandler.open if trigger is focused

- CHANGELOG.md
- lib/Datepicker/Calendar.js
As the JIRA describes, if the Timezone was at UTC-1, the weekdays would be off. ~The date used to build the week days was at midnight, so it would end up using yesterday's weekday. Displacing the date used by 13 hrs resolved so that in en-US locale, Sunday would consistently be the first day, regardless of OS time zone setting.~
Slightly different approach - rather than offset the time, use a UTC time via Date.UTC... lone strings (previous code i.e. '03/15/2020') will be localized by the browser (which is kindof ugly!) so '2020/03/15' assumed midnight UTC, localized to a time of UTC +1 (which means it ends up -1) and boom, you're into yesterday when you needed to be today... but a Date.UTC is consistent everywhere.. no bones about it - no wiggle room for the browser to manipulate. …
> STRIPES-709 displace date/time used to build weekday array

- lib/Accordion/Accordion.css
- lib/Accordion/Accordion.js
- lib/Accordion/headers/DefaultAccordionHeader.js
- lib/Accordion/stories/BasicUsage.js
- lib/Accordion/tests/Accordion-test.js
- lib/Accordion/tests/interactor.js
Reverts folio-org/stripes-components#1422
This `<Accordion>` update broke the ["should call onToggle" test](https://github.com/folio-org/stripes-smart-components/blob/210a5247caf807cfde315bd961a3731c5dc7687c/lib/CustomFields/pages/ViewCustomFieldsRecord/tests/ViewCustomFieldsRecord-test.js#L89-L91) in stripes-smart-components. Hopefully, there is a simple fix, but it isn't clear to me what it is ATM. 
Ordinarily, I'd take the time to figure out how to patch the test, but this error cropped up in the middle of a set of PRs to update the major version of stripes. @JohnC-80, I will un-revert this as soon as soon as the major version update is complete.
> Revert "STCOM-756 Accordion css implementation"

- lib/Checkbox/tests/Checkbox-test.js
This upgrades the `Checkbox` to work with the new interactors. This requires the new interactor as PRed in https://github.com/folio-org/stripes-testing/pull/78.
/cc @JohnC-80
> STCOM-785: interactors update - checkbox

- lib/RadioButton/tests/RadioButton-ReduxForm-test.js
- lib/RadioButton/tests/RadioButton-test.js
This upgrades the `RadioButton` to work with the new interactors. This requires the new interactor as PRed in https://github.com/folio-org/stripes-testing/pull/79.
/cc @JohnC-80
> STCOM-785: interactors update - radio button

- package.json
Also updating node version runtime to v10 since that is a requirement of postcss-custom-properties v10: https://github.com/postcss/postcss-custom-properties/releases/tag/10.0.0
> Updating postcss-custom-properties to v10 fixing DoS security warning

- lib/Button/tests/Button-test.js
- lib/Select/tests/Select-test.js
- package.json
In order to get this build clean, we need to point to the version of stripes-testing that actually has the interactors we seek.
Also, this keeps the linting clean as well
> STCOM-785 Pin stripes-components dependency to branch with new interactors

- CHANGELOG.md
- lib/Button/tests/interactor.js
Extend `Button` interactor with `isDisabled` field in the scope of the [STCOM-792](https://issues.folio.org/browse/STCOM-792).
> STCOM-792: Extend `Button` interactor with `isDisabled` field

- lib/TextField/tests/TextField-ReduxForm-test.js
- lib/TextField/tests/TextField-test.js
`TextField` is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785.
Depends on: https://github.com/folio-org/stripes-testing/pull/90
Consumed the new interactor and migrated all assertions to the new api.
> STCOM-785: interactors update: text-field

- lib/PasswordStrength/PasswordStrength.css
- lib/PasswordStrength/PasswordStrength.js
* The file `PasswordSrength.css` is misspelled
* The same file incorrectly imports CSS values via a higher-level scope.
While that is appropriate for modules that depend on `@folio/stripes`,
for the modules that _constitute_ `@folio/stripes`, they must use local
references.
Fixes [STCOM-803](https://issues.folio.org/browse/STCOM-803)
> STCOM-803 spell correctly; import correctly

- CHANGELOG.md
- lib/ErrorBoundary/ErrorBoundary.js
- lib/ErrorBoundary/readme.md
Given the callback function `onError` as a prop, call it from
`componentDidCatch` with the same arguments. While this does not
directly address STCOM-753 by logging the errors, it does allow the
component that instantiated this error boundary to provide a callback
that _does_ log the errors.
Refs [STCOM-753](https://issues.folio.org/browse/STCOM-753), [STCOR-455](https://issues.folio.org/browse/STCOR-455), [STCOR-493](https://issues.folio.org/browse/STCOR-493)
> STCOM-753 pass componentDidCatch arguments to a callback

- CHANGELOG.md
- package.json
Build with `@folio/stripes-cli` `v2`, which (huzzah!) does not depend
internally on stripes-core like `v1`, because `stripes-core` depends on
`stripes-components`, which depdends on `stripes-cli`, which depended
on `stripes-core`, which depends on `stripes-components`, which depends
on `stripes-cli`, which depended on `stripes-core`, which depends on
`stripes-components`.
Refs [STCOM-806](https://issues.folio.org/browse/STCOM-806)
> STCOM-806 increment @folio/stripes-cli to v2

- lib/ErrorBoundary/ErrorBoundary.js
- lib/ErrorBoundary/components/ErrorMessage/ErrorMessage.css
Until now, we have only been rendering the component stack, when the `<ErrorBoundary>` catches an error. 
This update includes the error stack as well which makes it a lot easier to pinpoint where an error occurred at first glance without having to look in the console.
The component stack can be made more precise by wrapping each module in an `<ErrorBoundary>`.
> Include error stack in <ErrorBoundary>

- .eslintrc
- CHANGELOG.md
- hooks/tests/useClickOutside-test.js
- hooks/useClickOutside/index.js
- hooks/useClickOutside/useClickOutside.js
- lib/Accordion/Accordion.js
Fix an issue with `<Accordion>` where if you have scrollable content as child of accordion and you try scrolling it using the scrollbar then this content will display below other accordions next to it
This issue is caused by elements losing focus when their content is scrolled using a scrollbar. This is possibly a browser issue - I've found Chromium issue that describes similar behavior with status Won't Fix (https://bugs.chromium.org/p/chromium/issues/detail?id=6759)
The solution that I propose is checking when a user has clicked outside of accordion's component tree using a `click` event listener on the document instead of `blur` event. In the handler of `click` we can check whether the event originated inside the component tree or not. And then based on that we can set `z-index` of …
> STCOM-812 Title Record: Search within Packages Modal. Scrolling list of Packages is overlay with Selection filter

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/Accordion/headers/DefaultAccordionHeader.js
https://issues.folio.org/browse/STCOM-815
- Add `aria-label` attribute to default accordion header of `<DefaultAccordionHeader>` component to fix error about uniqueness of landmarks.
> STCOM-815: Landmarks must have a unique role or role/label/title (AxeDevTools Error)

- lib/Timepicker/tests/Timepicker-test.js
Sync the timezone given to the `<Timepicker>` and used to check its
output. The dates when DST is observed are not consistent across
timezones, e.g. the US starts DST a week before and ends it a week after
most other countries in the world. Thus, this test would fail if it ran
during one of those weeks in an environment where the local timezone is
a non-US timezone.
Refs [STCOM-817](https://issues.folio.org/browse/STCOM-817)
> STCOM-817 sync timezones in timepicker tests

- CHANGELOG.md
- index.js
- lib/ErrorModal/ErrorModal.js
- lib/ErrorModal/index.js
- lib/ErrorModal/readme.md
- lib/ErrorModal/stories/ErrorModalExample.js
- lib/ErrorModal/tests/ErrorModal-test.js
- lib/ErrorModal/tests/interactor.js
- lib/Modal/stories/Modal.stories.js
https://issues.folio.org/browse/STCOM-794
Create `ErrorModal` component.
These changes are made as part of the concept of creating a small, simple, and rather "dumb" (highly specialized) component in order to display the error in a friendly way.
Therefore, the number of passed properties has been minimized. And as a consequence, in this version, there is **no** possibility:
- to pass your own footer;
- to customize the `Close` button (stylize, change its title);
- to make this modal `dismissible`;
- to have the `closeOnBackgroundClick` prop;
- etc...
It’s not claimed that is the only correct approach. Any suggestions and objections are greatly appreciated. As well as suggestions for the naming of some passed props:
`label`: variants - `heading`, `header`, `title` ...
`content`: variants - …
> STCOM-794: Add ErrorModal component

- CHANGELOG.md
- lib/TextArea/TextArea.css
Previously, `max-width` applied only on the container element, not on
the `textarea` element itself. This allowed `textarea`s to be resized
beyond the widths of their containers, which was terrible.
Refs [STCOM-824](https://issues.folio.org/browse/STCOM-824)
> STCOM-824 set max-width for textarea elements

- lib/MultiSelection/SelectedValuesList.js
- lib/Paneset/Paneset.js
- lib/TextField/TextField.js
- lib/Timepicker/TimeDropdown.js
ref to #1541 and #1542 
Addresses timeouts in Paneset, Timepicker, Textfield, and MultiSelection
The change ends up a bit lighter as code isn't being wrapped in conditionals... in class-based components, it ends up being simple - set an instance variable, clear it out on unmount...
```
this.someTO = setTimeout(...
componentWillUnmount() {
if(this.someTO) {
clearTimeout(this.someTO);
this.someTO = null;
}
}
```
in functional components, it's a bit weirder - but yeah, functional be like that... (no functional in this PR, but for future ref)
```
// store a ref to hold it (functional version of instance variables)
let someTO = useRef(null).current;
// useEffect with empty dependency array is equiv of didMount -> willUnmount
useEffect(() => {
return () => {
if (someTO) {
clearTimeout(someTO); …
```
> WIP: Clear timeouts on unmount

- CHANGELOG.md
- lib/IconButton/IconButton.js
`props.aria-label` would inadvertently be copied into a `<span>`
element, an a11y violation, while the companion `props.ariaLabel` would
be siphoned off. Now, both props are siphoned off.
Maybe a replacement for #1546? 
Refs [STCOM-834](https://issues.folio.org/browse/STCOM-834)
> STCOM-834 prevent aria-label from applying on a span

- CHANGELOG.md
- lib/Commander/CommandList.js
- lib/Commander/README.md
There is no need for `<CommandList>` to warn about overriding system
bindings. It is not an actionable warning because there is no way to
remove it without changing the binding, but the decision has already
been made not to change the binding.
Refs [STCOM-836](https://issues.folio.org/browse/STCOM-836)
> STCOM-836 CommandList should not warn about restricted bindings

- CHANGELOG.md
- lib/Selection/SingleSelect.js
- lib/Selection/tests/SingleSelection-test.js
`tether` props are no longer present in `defaultProps`, which
inadvertently caused a deprecation warning to display, even when such
props were not explicitly passed in.
Refs [STCOM-838](https://issues.folio.org/browse/STCOM-838)
> STCOM-838 avoid unnecessary tether deprecation warnings

- CHANGELOG.md
- lib/ErrorModal/ErrorModal.js
- lib/ErrorModal/tests/ErrorModal-test.js
There are some cases where it would be nice to customize the button on the `<ErrorModal>`.
This PR introduces a new prop called `buttonLabel` to allow for that. 
https://issues.folio.org/browse/STCOM-841
> STCOM-841: Add buttonLabel to ErrorModal

- CHANGELOG.md
- index.js
- lib/MultiColumnList/CenteredContainer.js
- lib/MultiColumnList/LoadMorePaginationRow.js
- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/PagingButton.js
- lib/MultiColumnList/PrevNextPaginationRow.js
- lib/MultiColumnList/index.js
- lib/MultiColumnList/readme.md
- lib/MultiColumnList/stories/ItemToView.js
- lib/MultiColumnList/stories/MultiColumnList.stories.js
- lib/MultiColumnList/stories/PrevNextPaging.js
- lib/MultiColumnList/stories/service.js
- lib/MultiColumnList/tests/MCLHarness.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- lib/MultiColumnList/tests/generate.js
- lib/MultiColumnList/tests/interactor.js
- lib/MultiSelection/stories/MultiSelection.stories.js
- translations/stripes-components/en.json
This PR aims to give modules a way to restore their scroll position of a current MCL given an 'itemToView' prop, as well as an 'onMarkPosition' handler. In the example image, it retains the item's vertical position across switches in the MCL's width.
at first, this will only be compatible with non-virtualized lists, but we'll hopefully expand that soon.
> STCOM-830 add 'scroll-to-item' logic

- CHANGELOG.md
- index.js
When we copied `exportToCsv` from `stripes-util` in #780, we forgot to
(or declined to) add it to the list of formal exports here. While this
is primarily a component library, we export plenty of functions in
addition to components.
Refs [STCOM-843](https://issues.folio.org/browse/STCOM-843)
> STCOM-843 formally export exportToCsv

- CHANGELOG.md
- lib/ExportCsv/exportToCsv.js
`exportToCsv` was copied from `stripes-util` in #780 but the
`stripes-util` version was never labeled as deprecated and it was
enhanced with new features:
* support for custom file names
* toggle header rows
and bug fixes:
* correctly support the legacy second-arg-lists-fields implementation
that were never replicated here. Whoops.
Refs [STCOM-844](https://issues.folio.org/browse/STCOM-844)
> STCOM-844 include exportToCsv enhancements from stripes-util

- lib/MetaSection/MetaSection.js
- lib/MetaSection/readme.md
- lib/MetaSection/tests/MetaSection.test.js
- lib/MetaSection/tests/interactor.js
Refs ERM-1230, STCOM-859
MetaSection is currently designed so that if user data is provided, it will display that, and if not then it will display "automated process" as a source. For certain applications, such as the mainly German use of ERM apps, user data is not built into the domain model at this level, and so is not attached to lastUpdated/dateCreated.
A lack of user data here implying "AutomatedSource" is not correct, and in ERM at least the desired outcome is to simply be able to hide these lines.
An alternative use case would be the ability to see the user metadata dependent only on permissions.
> Add hideSource prop to MetaSection

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/tests/Datepicker-ReduxForm-test.js
Correctly format RFC-2822 dates; the format is `ddd, DD MMM...` not
`ddd, MM MMM` (which includes the month in two different formats but
never the day-of-month).
Refs [STCOM-861](https://issues.folio.org/browse/STCOM-861)
> STCOM-861 correctly format RFC-2822 dates

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/tests/Datepicker-ReduxForm-test.js
- lib/Datepicker/tests/Datepicker-test.js
The implied promise of `outputFormatter`, given `backendDateStandard` is
that it will format dates using Arabic numerals (0-9) as this is what
the backend expects. Previously, it handled only for formatting but not
the conversion to Arabic ("Latn") numerals if the current locale used
non-Arabic numerals, which is the case for manu Arabic locales that use
Arabic-Hindi numerals.
Now, `<Datepicker>` delivers on both its promises:
1. it formats the date as expected for the backend
2. it provieds dates in Arabic numerals as expected for the backend
Refs [STCOM-860](https://issues.folio.org/browse/STCOM-860), [FOLIO-3208](https://issues.folio.org/browse/FOLIO-3208)
> STCOM-860 always use Arabic numerals given backendDateStandard

- CHANGELOG.md
- lib/Dropdown/Dropdown.stories.js
- lib/DropdownMenu/DropdownMenu.css
Dropdowns with lots of items/options can leave items unreachable since they cannot scroll.
Set a maxheight on DropdownMenu so that it won't be pushed beyond the height of the viewport.
> STCOM-848 Set max-height on dropdown menu

- lib/SearchField/tests/SearchField-test.js
`SearchField` is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785.
Depends on: folio-org/stripes-testing#93
Consumed the new interactor and migrate all assertions to the new api.
> STCOM-785: interactors update: searchField

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/tests/Datepicker-test.js
The Datepicker's  `inputRef` prop was ignored - it did not reference the input element for real
> STCOM-869 Fix Datepicker inputRef prop

- package.json
The modules composing `stripes` must be singletons within the build. This PR addresses a situation that could easily cause multiple copies of `stripes-components` to be included. Given:
* `stripes-components` `9.2.1` was released on a branch while the version on master remained at `9.2.0`.
* `stripes` `6.2.2` was release _on master_, referencing `9.2.1`.
This will cause build problems if `stripes-components` is cloned into a workspace: the `stripes` dep on `~9.2.1` means the git-clone of `stripes-components`, still at `9.2.0`, doesn't satisfy the dependency and it will pull down an additional copy into its `node_modules`. This means there are now multiple copies of `stripes-components` in the bundle, and Bad Things happen when that occurs.
Moral of the story: the version on `#master` …
> bump version to keep HEAD at/ahead of latest release

- CHANGELOG.md
- lib/Popover/Popover.js
- lib/Popover/tests/Popover-test.js
- lib/Popover/tests/interactor.js
When the popover is closing, if the popover is focused or contains the focused element, the trigger of the popover should be focused.
Covers `<Popover>` and `<InfoPopover>` components.
> STCOM-867 Popover close focus management

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/STCOM-877
The previous version of `react-overlays` was not working correctly with react 17. Root close would fire right after opening a dialog / modal which would close it.
This was fixed in: 
https://github.com/react-bootstrap/react-overlays/pull/880
More discussion with @aditya-matukumalli here:
https://folio-project.slack.com/archives/C210UCHQ9/p1632347078155500
> STCOM-877: Update react-overlays

- CHANGELOG.md
- lib/Popover/tests/Popover-test.js
- lib/RadioButtonGroup/tests/RadioButtonGroup-ReduxForm-test.js
- lib/Select/tests/Select-ReduxForm-test.js
- lib/TextField/tests/TextField-ReduxForm-test.js
Since the `react` `17` (#1615) and `react-overlays` `4` (#1618) PRs
merged, some focus-related tests began failing on master, despited the
fact that they _ran just fine_ on the merged-to-master test branch
during the PR. Ugh, so frustrating, given the reason we have that whole
"run tests on the merged-to-master branch" process is to prevent exactly
this process! Grrrrr. I am both angry and sad about this PR, but the
react-17 work is just too deeply integrated at this point to revert.
It isn't clear if this means we're prepping a release that has known
bugs, or if it just means we have a flaky test suite and IRL everything
works fine.
Refs [STCOM-880](https://issues.folio.org/browse/STCOM-880), [STCOM-797](https://issues.folio.org/browse/STCOM-797), …
> STCOM-880 skip flaky focus tests

- lib/Datepicker/tests/Datepicker-test.js
Adding a dateFormat for tests so that they'll interpret the value correctly rather than defaulting the calendar to 'this month' since we test calendar/weekday alignment with a particular day.
> Add Datepicker dateFormat prop for tests.

- CHANGELOG.md
- hooks/tests/useClickOutside-test.js
- hooks/useClickOutside/useClickOutside.js
Previous fix didn't cover all cases https://github.com/folio-org/stripes-components/pull/1646
A breakdown of what is happening when adding a tag to a record:
1. Click on `<MultiSelection>` search field. This opens up a dropdown with a few existing tags.
2. Either search for a tag that exists but is not visible.
3. Click on the tag in dropdown. At this point `onClick` that is added to the `<MultiSelection>` option is executed and the option disappears (removed from DOM)
4. `useClickOutside` click handler is executed. `ref.current.contains(e.target)` returns false because `e.target` is not in DOM even though that element was inside accordion's content.
We can fix this by handling `useClickOutside` click event in it's capture phase by passing `true` as third argument to `addEventListener`. …
> STSCOM-895: Make useClickOutside catch click event on capture phase

- lib/MessageBanner/MessageBanner.js
- lib/MessageBanner/readme.md
Accept `dismissable` for historical reasons or `dismissible` for correctness reasons. Do not reference `dismissble` for obvious reasons.
> spell check

- lib/Accordion/tests/interactor.js
How did this ever work? There is no `content` class in the imported CSS,
only `content-wrap` and `content-region`. What the ...?
Refs [STCOM-902](https://issues.folio.org/browse/STCOM-902)
> STCOM-902 use correct expanded-accordion selector

- lib/AutoSuggest/tests/interactor.js
- lib/ButtonGroup/tests/interactor.js
- lib/Callout/tests/interactor.js
- lib/ConfirmationModal/tests/interactor.js
- lib/ErrorModal/tests/interactor.js
- lib/Layer/tests/interactor.js
- lib/Pane/tests/interactor.js
- lib/PaneBackLink/tests/interactor.js
- lib/PaneCloseLink/tests/interactor.js
- lib/Paneset/tests/interactor.js
- lib/Timepicker/tests/interactor.js
Clean up imports that I missed in previous PRs (#1671, #1668) because I
am a bad, bad person. The CSS values have been factored out of the
selectors so we no longer need to import the CSS files into the
interactors.
Refs [STCOM-902](https://issues.folio.org/browse/STCOM-902)
> STCOM-902 exclude unused CSS imports in interactors

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
MCL doesn't scroll to the top-most item when result count is decreased. 
Reproducable on folio-testing in ui-users:
Go to ui-uerss https://folio-snapshot.dev.folio.org/users?sort=name
Check the filter for 'Active'
Scroll all the way to the bottom of the results....
Enter 'System' in the search field...
The list will have few results than can fill the frame, but it will not be scrolled completely to the top so that all are visible.
Simple change in the update cycle of MCL - less data should also mean scrolling to top (as does sorting the list)
> STSMACOM-611/STCOM-901 receiving fewer results will have MCL scroll to top

- CHANGELOG.md
- lib/RadioButton/RadioButton.css
- lib/RadioButton/RadioButton.js
Mark-up for Radio buttons had to be corrected for proper accessibility in #1645 This exclusion from the offending wrapping label edit caused the 'button' to no longer be clickable.
Adding click handlers to the button itself is a can of accessibility worms since it's not, technically, an interactive element (it just responds, visually, to the state of the radio button.)
Expanding the label area allows the component to use native click behavior while keeping the nice, consistent graphic style.
**Approach**: Extend clickable area of radio button label to extend over the 'button' via css, accounting for RTL...
> STCOM-910: pseudo-label of button is not clickable with the mouse.

- lib/LayoutHeader/LayoutHeader.js
- lib/LayoutHeader/readme.md
The prop-types and the code didn't agree, so while the documentation was
changed in #1697 it actually made things worse because following it (as
in https://github.com/folio-org/stripes-smart-components/pull/1164)
would not work.
It appears that `AddressView` is the only case where `actions` is passed
to `LayoutHeader`, but leaving the existing implementation as-is and
changing the doc to match still feels like the safest bet.
Refs [STCOM-914](https://issues.folio.org/browse/STCOM-914)
> STCOM-914 REALLY correct LayoutHeader documentation

- CHANGELOG.md
- lib/Selection/SingleSelect.js
The nature of `<button>` elements is that they cannot be invalid. They
are interactive by being clickable but there is no way for their input
to be invalid. This change resolves the following lint error:
> The attribute aria-invalid is not supported by the role button. This
> role is implicit on the element button [jsx-a11y/role-supports-aria-props](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/30deacbf240f8cea7b88a977a72ed54b499c134e/docs/rules/role-supports-aria-props.md)
Refs [STCOM-915](https://issues.folio.org/browse/STCOM-915)
> STCOM-915 do not set aria-invalid on button elements

- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/OptionsListWrapper.js
Some prop-spreading was removed in an earlier refactor (#1663) that now
causes a console warning because the prop is now applied directly to the
underlying DOM element. Restore the spread.
Refs [STCOM-912](https://issues.folio.org/browse/STCOM-912) and [STCOM-883](https://issues.folio.org/browse/STCOM-883) by extension.
> STCOM-912 restore props spread to avoid console warning

- lib/NavList/tests/NavList-test.js
Makes use of new Navlist interactor added to `@folio/stripes-testing`
> STSMACOM-616 - update navlist tests to use new interactor

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/PrevNextPaginationRow.js
Fixes PrevNext buttons return incorrect index.
[STCOM-909](https://issues.folio.org/browse/STCOM-909)
> STCOM-909: MultiColumnList - PrevNext buttons return incorrect index

- CHANGELOG.md
- lib/Layout/stories/classNamePropertiesMapping.js
- lib/Layout/styles/text.css
Adds new `text-start`, `text-end` classNames to `<Layout>` component to support both LTR and RTL languages.
[STCOM-898](https://issues.folio.org/browse/STCOM-898)
> STCOM-898: Layout > Add textStart, textEnd properties

- lib/MultiColumnList/MCLRenderer.css
FINALLY... Focus-styling HAS COME BACK to MCL HEADERS!!!
> Add focus-within styling to MCL header

- CHANGELOG.md
- lib/Pane/Pane.js
This is showing up in settings:
The `onMount` prop just needs to be filtered out before passing props to internally rendered HTML elements.
> STCOM-931 prevent onMount from passing to DOM element

- CHANGELOG.md
- lib/Paneset/Paneset.js
Pane widths using a percentage were not proportionally resized, which would leave them mis-matched if they were in a set with a pixel-based value. Ending panes would end up cut off or falling short (leaving a white space between the pane and the edge of the window)
See https://issues.folio.org/browse/STCOM-927 for the previous case...
If the layout cache uses a percentage-based width, parse the value and perform calculations to increase or decrease the number based on the relative size of the container.
> STCOM-927 Perform proportional resize on panes with percentage-based widths

- CHANGELOG.md
- lib/Pane/Pane.js
- lib/Paneset/Paneset.js
Paneset layout caching is used by panesets to keep track of pane sizes between transitions/changes in the sizes of the panes. This eases the transition between views by retaining the widths that the user had previously set.
the smart component 'PersistedPaneset' pushes the paneset cache up to the browser's local storage, so the user-applied resizing can be applied the next time they log in to FOLIO, or return to an app.
Panes cache their widths based on their id. If an id isn't provided as a prop, one will be generated. A generated id will not be repeated the next time that the pane is rendered, so it will be found as unique and added to the list of caches as-if it were a different paneset.
This can cause the local storage cache to grow every time a Pane is initially rendered.
Check to …
> STCOM-932 Check for stable id's before caching pane sizes

- CHANGELOG.md
- lib/Accordion/AccordionSet.js
purpose:
https://issues.folio.org/browse/STCOM-937
based on doc https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-multiselectable it's used for selects, when accordion is not smth selectable with options, moreover role was removed some time ago
> STCOM-937 AccordionSet has incorrect aria attribute

- lib/MultiColumnList/MCLRenderer.css
- lib/TextLink/TextLink.css
@JohnC-80 , I'm not confident about changing `& .root` to `&.root` in `TextLink`, but I can't get stylelint to be quiet otherwise. Moving that block above the main `.root` block causes even more complaints 😕 .
> lint. it does a body good.

- CHANGELOG.md
- lib/global.css
Refactoring ages ago in #93 led to corruption of a few `font-family`
entries, now repaired.
Refs [STCOM-950](https://issues.folio.org/browse/STCOM-950)
> STCOM-950 correct Arabic, Japanese CSS typos

- CHANGELOG.md
- lib/KeyValue/tests/KeyValue-test.js
- lib/NoValue/readme.md
- lib/NoValue/tests/NoValue-test.js
Leverage the `NoValue` interactor from `@folio/stripes-testing` to
consistently handle no-value elements.
Refs [STCOM-949](https://issues.folio.org/browse/STCOM-949), [STCOM-936](https://issues.folio.org/browse/STCOM-936)
> STCOM-949 leverage stripes-testing NoValue interactor

- CHANGELOG.md
- lib/Callout/Callout.js
- lib/Paneset/Paneset.js
React throws errors if `setState` is called after a component has
unmounted.
Refs [STCOM-952](https://issues.folio.org/browse/STCOM-952)
> STCOM-952 avoid setState in unmounted components

- lib/MultiColumnList/MCLRenderer.css
Fix MCL headings
https://issues.folio.org/browse/STCOM-835
> STCOM-835: Break long words in MCL headings based on zooming 200%

- CHANGELOG.md
- package.json
This dependency caused a great deal of noise in any test run/build. Will investigate upgrades beyond the 12.1.4 in the future (STCOM-957).
Refs [STCOM-956](https://issues.folio.org/browse/STCOM-956)
> STCOM-956 Lock off postcss-custom-properties to 12.1.4

- CHANGELOG.md
- package.json
When we upgraded postcss in #1680, we missed an update to autoprefixer
that should have been made to maintain compatibility. Whoops.
This should be merged in concert with folio-org/stripes-webpack/pull/57 ([STRWEB-46](https://issues.folio.org/browse/STRWEB-46)).
Refs [STCOM-963](https://issues.folio.org/browse/STCOM-963), [STCOM-892](https://issues.folio.org/browse/STCOM-892)
> STCOM-963 maintain autoprefixer/postcss compatibility

- CHANGELOG.md
- lib/Datepicker/staticFirstWeekDay.js
The `es-419` locale expects the first day of the week to be Monday. Make
it so.
Refs [STCOM-985](https://issues.folio.org/browse/STCOM-985)
> STCOM-985 correctly set first-day-of-week for es-419

- README.md
- lib/Icon/readme.md
Adds a link to the storybook icon list to Icon component documentation as well as a link to storybook in our top-level readme.
> Add storybook links

- CHANGELOG.md
- lib/Paneset/Paneset.js
- lib/Paneset/tests/Paneset-test.js
Currently, the percentage-based panes are always resized to full screen width. This can be strange in cases where there are only 2 panes (like settings) that are not full width. 
The logic in this PR modifies this so that 
- panesets where ALL of the panes are percentage -based are only resized by adjusting the last pane (percentages, for the most part can be left alone, but this takes care of some oddness when the window is resized)
- only panesets with 3 or more panes are held to this percentage resizing.
> STCOM-983 Selectively resize percentage-width panesets

- lib/Paneset/Paneset.js
See https://issues.folio.org/browse/STCOM-987
Currently, after their 'calcWidths' process, panes will store their width for re-use in future recalculations. 
If the window has been resized, then this static width no longer applies and the pane should be re-measured.
> STCOM-987 Check for window resize in calcWidths

- lib/Paneset/Paneset.js
Bug: Panesets are inserting nested objects into the cache rather than values. Only the affected layout object should be returned rather than the whole cache as nested objects.
> Pane percent bugfix

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/LayoutHeader/LayoutHeader.js
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/readme.md
- lib/Select/Select.js
Purpose:
- add `PropTypes.func` for accordion children for `Open` render-prop usage
- add `PropTypes.node` for `LayoutHeader` actions title to use `<FormattedMessage>` as prop ([AddressView](https://github.com/folio-org/stripes-smart-components/blob/master/lib/AddressFieldGroup/AddressView/AddressView.js#L82))
- introduce new MCL `pagingType` `none` for custom pagination
- add `PropTypes.bool` as one of value type for `Select` option
> STCOM-994 Extend proptypes for avoiding errors

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
The format of `_auth` in `.npmrc` has changed to
`npm config set //repo_path/:_auth TOKEN` instead of `npm config _auth TOKEN`.
This PR updates it to:
`npm config set //repository.folio.org/repository/npm-folio/:_auth $NODE_AUTH_TOKEN`
It also bumps actions/setup-node to a newer version `v3` compatible with node 16.
> STCOM-996: Adjust _auth path

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/PrevNextPaginationRow.js
paginationBoundaries - this property is no longer needed, since by using activeNext and activePrevious we can achieve the same goals and disable the next and prev buttons.
> STCOM-999 Remove paginationBoundaries prop from MCLRenderer and PrevNextPaginationRow components

- package.json
- Upgrade is needed in scope of [UIDATIMP-1152](https://issues.folio.org/browse/UIDATIMP-1152). We migrated from `react-highlighter` library to `<Highlighter />` because the library is not maintained since 2018 and giving warnings when installed. `react-highlight-words` which `Highlighter` component uses is also outdated and has `react: "^0.14.0 || ^15.0.0 || ^16.0.0-0"` peerDeps and giving also warnings. This change updates it to the latest `v0.18.0` which is compatible with react-17/18 and has `"react": "^0.14.0 || ^15.0.0 || ^16.0.0-0 || ^17.0.0-0 || ^18.0.0-0"` peerDeps.
- https://issues.folio.org/browse/STCOM-1005
> STCOM-1005: Update react-highlight-words library to compatible version with react-17/18

- CHANGELOG.md
- lib/MultiSelection/MultiDownshift.js
Fix an issue in `<Multiselection>` when searching for options - first option wasn't being highlighted
Issue was in `<MultiDownshift>` component. If you hover over an option - then index of that option is saved in state `highlightedIndex` and doesn't change until user clicks on an option, or arrow keys to navigate the list.
This causes a behaviour when a user hovers over a 3rd item, then searches for something that gives only result - this result is not highlighted because `highlightedIndex` is still 2.
Fixed by handling `changeInput` event and setting `highlightedIndex` to 0
https://user-images.githubusercontent.com/19309423/174973507-863dd166-6092-415c-9824-d8889fbc73d4.mp4
[STCOM-1015](https://issues.folio.org/browse/STCOM-1015)
> STCOM-1015 Fix Multiselect element lose focus when user typing name of option

- CHANGELOG.md
- lib/Pane/Pane.css
- lib/Paneset/Paneset.css
- lib/global.css
- lib/variables.css
https://issues.folio.org/browse/STCOM-975
This bug is the result of an attempt to fix a bug related to an extra blank page ([STCOM-872](https://issues.folio.org/browse/STCOM-872)). Trying to set `height: auto` for the `body` resulted in it collapsing due to absolutely positioned children having no explicit height.
Initial issue with extra blank page can be resolved by using `@media print` media query, where margins for `html` and `body` are cleared and page's margins regulated by `@page` at-rule. In this case, the reason for the content collapsing is eliminated and the problem with the empty page is solved.
<details>
<summary>How it looks locally</summary>
</details>
---
**NB:** But there is a question about how the pane should be printed. For now it's just one page with visible data - …
> STCOM-975 Record detail panes are empty when printed

- CHANGELOG.md
- lib/Modal/Modal.css
**Refs**: [STCOM-1020](https://issues.folio.org/browse/STCOM-1020)
https://user-images.githubusercontent.com/85172747/176164183-129952d8-b442-4b61-b93e-67e8f18881ba.mp4
> STCOM-1020: Long titles do not fit in the confirmation modal window header

- CHANGELOG.md
- lib/Callout/Callout.css
- Break long words in Callout message
- Refs: https://issues.folio.org/browse/STCOM-1023
> STCOM-1023: Break long words in Callout message

- CHANGELOG.md
- lib/Button/Button.css
https://issues.folio.org/browse/STCOM-1007
This PR adds `text-decoration: underline` to focused buttons as well as applying a thickness of 2px to the underline.
Standard buttons
With buttongroups
> STCOM-1007 - improve focus indicator for buttons

- CHANGELOG.md
- lib/TextField/TextField.js
- lib/TextField/tests/TextField-test.js
Textfield still displays clear icon/focus state when 'disabled' is set.
See https://issues.folio.org/browse/STCOM-818
Approach - caught the disabled prop in gDSFP and set the focused state to false.
> STCOM-818 Textfield retains focused 'state' when disabled.

- CHANGELOG.md
- lib/IconButton/IconButton.css
- lib/IconButton/IconButton.js
- lib/IconButton/readme.md
Provide ability to disable an Icon Button
Issue: [STCOM-1028](https://issues.folio.org/browse/STCOM-1028)
It is possible to accept the disabled props already through the props. 
But, it is still useful to 
1. update the propTypes
2. story book with the disabled prop
3. IconButton Styles
> STCOM-1028 - Provide ability to disable an Icon Button

- CHANGELOG.md
- lib/AdvancedSearch/tests/AdvancedSearch-test.js
- lib/AdvancedSearch/utilities/splitQueryRows.js
Fix incorrect splitting of rows in `<AdvancedSearch>` when using `Identifiers (all)` option
Issue was caused by a `.` inside `identifiers.all` option value. Fixed it by including `.` alongside `\w` inside regex segment `[\w.]+==.+`
https://user-images.githubusercontent.com/19309423/181472066-0faaf8d8-78ea-4b69-aa8a-10178a26c761.mp4
[STCOM-1031](https://issues.folio.org/browse/STCOM-1031)
> STCOM-1031: Selected search option changes to query search when user reopened advanced search modal.

- CHANGELOG.md
- lib/Button/Button.css
Remove `min-height` from link type button to allow it to have the same height as text around
[STCOM-1039](https://issues.folio.org/browse/STCOM-1039)
> STCOM-1039 Button: Buton link style has a min-heigt which can offset it from text

- lib/List/List.js
- lib/List/tests/list-test.js
This PR based from the way that the stripes-testing interactor is setup to work (locating via an id.) This component has been around a while, and could fairly be accomplished directly in app code with a simple `map` call, but nevertheless, we want to add this slight degree of versatility/ambiguity to this component's rendered instance...
> STCOM-1040  Expose id prop in List component

- CHANGELOG.md
- lib/ConfirmationModal/ConfirmationModal.js
- lib/ConfirmationModal/stories/ConfirmationModalExample.js
- lib/ConfirmationModal/tests/ConfirmationModal-test.js
- lib/Modal/Modal.js
- lib/Modal/readme.md
- lib/Modal/tests/Modal-test.js
[JIRA](https://issues.folio.org/browse/STCOM-1041)
Users requested that focus be automatically placed on the 'confirm' button of `ConfirmationModal`s. This moves focus beyond read-only content that probably contains important information. The solution is to include the message in the labeling of the modal so that it will automatically be announced when focus enters the modal. This will have it behave in a similar way to Javascript alerts.
Other explored approaches: `aria-describedby` - this attribute has varying degrees of functionality between browsers. It would be nice if this just worked in JAWS, but the current `aria-labelledby`-based implementation will have to do for now.
`aria-live` region - this rather-forceful approach always created a double announcement somewhere. Since it's …
> STCOM-1041 A11y labeling, focus management for modals.

- .github/workflows/build-storybook.yml
- .github/workflows/main.yml
This PR addes a github action to automate storybook updates. 
Stripes-components' storybook is hosted through github.io pages from its own `storybook` branch.
The action, upon a merge to master, will checkout the storybook branch, merge master into it, run the storybook build command, commit and push the changes back to the storybook branch.
This does sync up the branches better as the storybook branch had a slightly different build setup (building to the `.out` directory rather than the `docs` folder) and pushes the docs folder specifically to the ci action with a slightly more granular approach to the history management of it.
> STCOM-1050 Publish storybook in CI with PR merge

- CHANGELOG.md
- lib/Paneset/Paneset.js
In production, we saw that `this.state.layoutCache.findIndex(...)` was sometimes throwing an NPE on `layoutCache`.
```
Uncaught TypeError: Cannot read properties of null (reading 'findIndex')
at t.hasCachedLayout (Paneset.js:667:48)
at Paneset.js:534:32
```
It isn't totally clear how this happens since it's initialized from a prop with valid default value. Maybe sometimes the prop is present but `null`? Dunno, but in any case the `...findIndex()` code is now more cautious.
Aside: renamed `hasCachedLayout` to `cachedLayoutIndex` since the previoius name gives the impression it returns a boolean when what it actually returns is an array index, i.e. an int >= -1.
Refs [STCOM-1056](https://issues.folio.org/browse/STCOM-1056)
> STCOM-1056 avoid Paneset NPE when evaluating cached layouts

- CHANGELOG.md
- lib/Paneset/Paneset.js
Yeah it's pretty clear, can't have no nulls, fool! 
So I can index, index, like I'm supposed to do
Can't have no boom boom when changing column spaces 
I need all the right punc in all the right places
I see the state init, it reads initial props
But it don't check for null, so reading dot-paths stops 
If you got braces braces, just post 'em up
So you can index an array and you don't ever have to stop
Yeah John Coburn, he told me, "You got to initialize!" 
Be like, "If props come in null then defaults will not override." 
And so when props come in empty we add our own brand new stash 
So traversing the state doesn't blow up on null layoutCache
Because you know it's all about that brace
Supercedes #1095, which was insufficient.
Refs [STCOM-1056](https://issues.folio.org/browse/STCOM-1056), …
> STCOM-1056 prevent null in state.layoutCache

- package.json
Breaking changes in `stripes-testing` were committed under the auspices of a bug fix (PR #572, though only noted as breaking in the PR it replaced, PR #439) on master after the previous release (`4.3.0`) but before the minor was bumped for the next release to `4.4.0`. The effect of this is that a typical version constraint like `~4.3.0` will not work for npm-folioci builds where that commit exists in build/release `4.3.1000004620`.
This illustrates why it is important to bump the minor version at the time a new feature is added, or the major version at the time a breaking change is added, rather than waiting until publishing the release: waiting makes it impossible to publish a patch release that relies on those changes _not_ being included in the previous version.
CC: @JohnC-80 , …
> limit stripes-testing to ~4.3.0 <4.3.1000004620

- CHANGELOG.md
- lib/ConfirmationModal/ConfirmationModal.js
- lib/ConfirmationModal/readme.md
- lib/ConfirmationModal/tests/ConfirmationModal-test.js
[STCOM-1058](https://issues.folio.org/browse/STCOM-1058)
https://user-images.githubusercontent.com/85172747/203316697-4bb00270-d015-4082-b97f-bdc314e93020.mp4
> STCOM-1058: After click submit button disable the confirmation button in ConfirmationModal component

- CHANGELOG.md
- lib/Layer/Layer.css
This was happening due to a global style on the body element with `overflow: hidden`
These styles were in use 5 years ago, prior to using flexbox for the outer DOM hierarchy (root, nav, module-container) when there was some risk of introducing a new hierarchical 'layer' causing overflow to occur on the body element and a vertical scrollbar to appear.
Approach: remove the offending global style. The `root` element is rendered as a flex column with its height at `100%` - removing this flex *will make a browser scrollbar appear, but since it's there, the `root` does not become taller than the viewport, which renders the removal of body overflow as unnecessary.
> STCOM-1059 Login screen missing scrollbar.

- .github/dependabot.yml
- CHANGELOG.md
Enable dependabot. This is a POC. This is only a POC. If this turns out to be overwhelming, we'll turn it off.
See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates for configuration options, including ignoring certain libraries and automatically tagging certain contributors for review, among many other options.
Refs [STCOM-1068](https://issues.folio.org/browse/STCOM-1068), [FOLIO-3664](https://issues.folio.org/browse/FOLIO-3664)
> STCOM-1068 enable dependabot

- CHANGELOG.md
- lib/sharedStyles/interactionStyles.css
Prevent row-level css from capturing pointer-events
`before` pseudo-elements on MCL row elements are covering the whole row and catching click events.
https://user-images.githubusercontent.com/19309423/211005916-42c0c9da-448e-4758-a252-5b725a60c1e7.mp4
[STCOM-1066](https://issues.folio.org/browse/STCOM-1066)
> STCOM-1066 User can't click on the link if focus (highlighting) is on the row with link

- CHANGELOG.md
- package.json
Bump the major version to accommodate breaking changes, i.e. the removal of many long-deprecated props across several components.
> this one goes to 11

- CHANGELOG.md
- lib/TextLink/TextLink.js
`<TextLink>` may spread its props onto `<Link>`, which also accepts an object for `to`, hence the PropType here must also be less restrictive.
Refs [STCOM-1076](https://issues.folio.org/browse/STCOM-1076)
> STCOM-1076 loosen prop-types for TextLink

- lib/AutoSuggest/tests/AutoSuggest-test.js
- lib/Datepicker/tests/Datepicker-test.js
- lib/Dropdown/readme.md
- lib/MenuSection/stories/DropdownExample.js
- lib/Selection/Selection.js
- package.json
`tether` was removed in #1926 but we missed a few related tests and examples, as well as the prop on `<Selection>`.
Refs [STCOM-1067](https://issues.folio.org/browse/STCOM-1067)
> STCOM-1067 purge tether-related tests, props, examples

- package.json
Reverts folio-org/stripes-components#1947
We were not prepared for the numerous warnings our present code generates after applying this update.
> Revert "Bump stylelint-config-standard from 18.3.0 to 29.0.0"

- CHANGELOG.md
- lib/TextArea/TextArea.js
- lib/TextArea/stories/BasicUsage.js
- lib/TextArea/tests/TextArea-test.js
- package.json
Add `rootClass` prop to be able to define custom styles for `<TextArea>` wrapper element
Add `fitContent` prop to be able to set initial width of `<TextArea>` to fit content
https://user-images.githubusercontent.com/19309423/215756427-29c7e504-0572-4010-b9b6-fb439c73b15e.mp4
[STCOM-1101](https://issues.folio.org/browse/STCOM-1101)
> STCOM-1101 Add `rootClass` and `fitContent` props to `<TextArea>`

- CHANGELOG.md
- lib/Timepicker/Timepicker.js
- lib/Timepicker/readme.md
- lib/Timepicker/tests/Timepicker-test.js
https://issues.folio.org/browse/STCOM-1103
Approach - removed the range of formats for checking validity of value. The component will only format once a full string matching the `H:MM` or `H:MM A` format is entered (corresponding with the time format of the ui locale.)
> STCOM-1103 Timepicker too aggressive in formatting user input.

- CHANGELOG.md
- lib/Timepicker/TimeDropdown.js
- lib/Timepicker/tests/Timepicker-test.js
https://issues.folio.org/browse/STCOM-1104
Currently, the time values can go into negative or well beyond the 59 minute mark...
The Timepicker spinners should function within the ranges of their particular hour format, with a range of 0 - 59 for minutes and 0-23 for 24 hour format , 1-12 in 12 hour format.
This PR focuses on that logic to ensure a value within the ranges is set.
The main issue was a mistake in trying (and failing) to mutate a value.
Tests are added for both 12 and 24 hour modes.
> STCOM-1104 Timedropdown spinners not respecting ranges.

- lib/MultiColumnList/CenteredContainer.js
- lib/MultiColumnList/LoadMorePaginationRow.js
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/PrevNextPaginationRow.js
- lib/MultiColumnList/stories/MaxHeightVirtualized.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- util/getFocusableElements.js
TLDR, MCL's that use links within the cells rather than row-level anchors perform fine with assistive technology. Axe-core has a couple of rules that seem to work in opposition to eachother given recent updates >=4.5.0. 
The axe rules themselves affecting this case are too generic and potentially wide sweeping to just turn off. `aria-required-children` checks for proper parent/child structure of elements with aria roles. It's a very important test to have for libraries that export complex widgets.
Maintainers of `axe-core` understand that their library [needs work with these detections](https://github.com/dequelabs/axe-core/issues/3888). There has been some work around the approach for `aria-required-children` but [suggesting an attribute such as …
> STCOM-1074: MCL - Axe error... 'required children' 

- lib/Datepicker/readme.md
- lib/Timepicker/TimeDropdown.js
- lib/Timepicker/Timepicker.js
- lib/Timepicker/tests/Timepicker-reduxform-test.js
- lib/Timepicker/tests/Timepicker-test.js
- lib/Timepicker/tests/timepicker-interactor-bt.js
- util/dateTimeUtils.js
Fixes https://issues.folio.org/browse/STCOM-1119
Datepicker stumbled this issue when it went through its own refactor. It's the same case with timepicker - ugly as it is, it needs to conform to react-final-er-um.. redux-form's [behavior of an `onChange` event being triggered  onBlur](https://github.com/redux-form/redux-form/blob/master/src/ConnectedField.js#L176). Someone please bury it under its pile of open github issues.
Approach - handle blurs internally in the component where  `redux-form` is appeased with an event-shaped sacrifice so that it won't blank out the value or just give up and swallow any triggered error.
> STCOM-1119 Timepicker vs React-fin- er, um Redux-form (aka stsmacom's ChangeDueDateDialog)

- CHANGELOG.md
- lib/Timepicker/Timepicker.js
- lib/Timepicker/tests/Timepicker-reduxform-test.js
- lib/Timepicker/tests/Timepicker-test.js
Problem: When hours format is 12-hour, confirming a time (12+ PM) in the `<TimeDropdown>`, "Invalid Date" appears in the input. 
Approach - the "invalid date" message appeared as a result of faulty logic in a 24-hr conversion project for moment/date library parsing. The logic was revised to perform correctly, and tests written to uphold the behavior.
> STCOM-1120 Timepicker - Refactor convert 24hr function

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.css
No more blind pressing of the 'tab' key when focus reaches this part....
Refs [STCOM-1105](https://issues.folio.org/browse/STCOM-1105)
> STCOM-1105 - MCL sortable header focus styles.

- CHANGELOG.md
- lib/Timepicker/Timepicker.js
- lib/Timepicker/stories/BasicUsage.js
- lib/Timepicker/tests/Timepicker-test.js
- lib/Timepicker/tests/TimepickerHarness.js
Problem: time should convert to utc for backend values in respect to the provided timezone.
This PR includes a call to moment.tz in case the timezone is something besides `utc` and still uses `moment.utc()` for cases where it doesn't receive a timezone (rare) instead of always using utc.
> STCOM-1128 Handle timezone conversion with defaultOutputFormatter

- lib/Dropdown/readme.md
- lib/Popper/Popper.js
- lib/Popper/readme.md
- lib/Tooltip/readme.md
This change allows `auto` to be specified for popper component placements; this is a valid placement based on the [popper documentation](https://popper.js.org/docs/v1/#Popper.placements).
> STCOM-1137: Add auto placement to <Popper> component

- CHANGELOG.md
- lib/Timepicker/Timepicker.js
- lib/Timepicker/tests/Timepicker-test.js
Previous default parsing behavior in timepicker was to use `moment.utc(value).local()` - this isn't adequate if you want to parse a value into a tenant-set timezone as local will parse based on the users' browser timezone vs the timezone set in the system.
Approach
Use `moment.tz(value, timezone)` to build the client timezone into the moment object... output via `format` 
Additionally, no longer using `local()` made `removeDST` problematic, as expected values would end up off by 1 if a value re-circulated the logic during internal parsing (a utc-0 value to start being changed by the user through the time dropdown to a localized timestring).
Time transitions from read-only to edit with varying timezone settings.... (from the Organizations app)
> STCOM-1141 - timepicker - consider timezone when parsing time value

- .storybook/stcom-webpack.config.js
- lib/Icon/Icon.js
- lib/Icon/icons.js
- package.json
Jest tests fail if `stripes-components` Icon isn't mocked - this was originally due to usage of webpack 'require.context' api to dynamically load all of the contents of the `icons` directory without having to manually maintain a list.
This PR 
- removes the dependency `react-svg-loader`
- replaces it with `@svgr/webpack`
- sets up a 'default' for Icon to render in JSDOM...
- falls back to the default if the provided 'icon' prop cannot be found.
- removes the local webpack loader override.
- The specific behavior from the override is now accomplished through resourceQueries. Built-in icon SVG imports will use the `?icon` query in their import path... all other SVG's will be inlined via stripes-webpack's configuration.
This PR depends on https://github.com/folio-org/stripes-webpack/pull/92 …
> STCOM-1144 use svgr instead of react-svg-loader, jestify hopefully

- lib/CurrencySelect/tests/CurrencySelect-test.js
- package.json
PR #1971 doppelgänger
Bumps [currency-codes](https://github.com/freeall/currency-codes) from 1.5.1 to 2.1.0.
- [Release notes](https://github.com/freeall/currency-codes/releases)
- [Commits](https://github.com/freeall/currency-codes/compare/v1.5.1...v2.1.0)
---
updated-dependencies:
- dependency-name: currency-codes dependency-type: direct:production update-type: version-update:semver-major ...
> Bump currency-codes from 1.5.1 to 2.1.0

- CHANGELOG.md
- lib/Pane/Pane.css
[STCOM-1148](https://issues.folio.org/browse/STCOM-1148)
*Problem* -  absolutely positioned content such as smart-components' NoResultsMessage will bust right out of Pane's content div, despite it having `overflow: hidden` applied in its CSS. In order to cull the overflow of non-static elements, the content containing div should be 'positioned' as well.
Approach - 
Set `position: relative` on pane's content div's class.
hooray, action dropdowns now work when results are empty.
> STCOM-1148 absolutely positioned content can block pane header.

- CHANGELOG.md
- lib/TextArea/TextArea.js
- lib/TextArea/tests/TextArea-test.js
To provide **onChange**, **value**, and **ariaLabel** prop to **TextArea** component as it's done for TextField component e.g. to make it possible to provide a callback on textaria change and set ariaLabel (although it's possible to set it as 'aria-label' but added it for consistency)
https://issues.folio.org/browse/STCOM-1154
> STCOM-1154: Provide onChange and ariaLabel props to TextArea component

- CHANGELOG.md
- lib/global.css
https://issues.folio.org/browse/STCOM-1157
These styles went away when we recently upgraded the `normalize.css` dependency. This PR simply re-adds them in our global styles.
Before:
After:
> STCOM-1157 Two X's displayed on search fields

- package.json
- util/tests/dateUtils-test.js
`webpack` was unlocked from `~5.68.0` in tip-of-master branches which are leveraged here in CI, so even though the correct value is in place in `devDependencies`, newer versions are sneaking in via the CI builds of `stripes-cli` and `eslint-config-stripes`.
Refs [STCOM-1153](https://issues.folio.org/browse/STCOM-1153)
> STCOM-1153 re-lock webpack to ~5.68.0

- CHANGELOG.md
- index.js
- lib/AdvancedSearch/AdvancedSearch.js
- lib/AdvancedSearch/hooks/useAdvancedSearch/useAdvancedSearch.js
- lib/AdvancedSearch/index.js
- lib/AdvancedSearch/readme.md
- lib/AdvancedSearch/utilities/defaultRowFormatter.js
Return formatted `filledRows` and `query` from `useAdvancedSearch` hook to be used for initial search on page load without needing to open Advanced Search modal
Export `useAdvancedSearch` from `stripes-components`
https://github.com/folio-org/stripes-components/assets/19309423/43adc3b9-c1bd-43d2-bfb0-51e77e6433e3
[STCOM-1156](https://issues.folio.org/browse/STCOM-1156)
https://github.com/folio-org/stripes-authority-components/pull/80
> STCOM-1156 Return filled rows and query from `useAdvancedSearch` hook

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Dropdown/Dropdown.js
- lib/Dropdown/Popdown.js
- lib/FocusLink/FocusLink.js
- lib/FocusLink/tests/FocusLinkHarness.js
- lib/FocusLink/tests/FocusLinkWithoutTarget.js
- lib/Layer/Layer.js
- lib/MultiSelection/MultiSelection.js
- lib/Selection/SingleSelect.js
- package.json
- util/getFocusableElements.js
- util/trapFocus.js
After seeing how wack that repo is, (Changelog: `Feature: 'remove alot of code'`... `Feature: publish dir ` (not in a breaking version!))I decided it's time to just eliminate it, as all functionality we used from it is now provided by browsers - `element.contains()` and `element.matches()`... um... JSDOM, hold on to your butt!
Probably pending some jest tests to see if this is an issue.... if it is, maybe we can just polyfill these guys for that environment somehow rather than re-introducing this dependency.
~~Bumps [dom-helpers](https://github.com/react-bootstrap/dom-helpers) from 3.4.0 to 5.2.1.~~
~~updated-dependencies:~~
> Depbot_dup:  Remove dom-helpers dependency

- CHANGELOG.md
- lib/TextLink/TextLink.css
Problem:
The `:active` state of `interactionStyles` turns elements completely primary blue by default. This has the sideffect of hiding anchor text as it blends in perfectly with the background color. This PR adds a selector/style to `<TextLink>` to account for that styling.
Data-import before change:
From Data-import after change:
> STCOM-1159 - TextLink styles within ':active" interactive elements.

- CHANGELOG.md
- lib/SearchField/SearchField.js
- lib/SearchField/readme.md
- lib/SearchField/tests/SearchField-test.js
Provide the `searchableOptions` prop to the `SearchField` component to use it as `children` for options in the `Select` component to be able to utilize the `<optgroup>` tag and not just the `<option>`.
[STCOM-1183](https://issues.folio.org/browse/STCOM-1183)
[ui-inventory/pull/2195](https://github.com/folio-org/ui-inventory/pull/2195)
[stripes-acq-components/pull/710](https://github.com/folio-org/stripes-acq-components/pull/710)
https://github.com/folio-org/stripes-components/assets/77053927/d7f78f3c-cef9-4aa4-a502-1d42580fb705
> STCOM-1183: Provide the searchableOptions prop to the SearchField component to use it as children for options in the Select component.

- CHANGELOG.md
- lib/RepeatableField/RepeatableField.js
- lib/RepeatableField/readme.md
https://issues.folio.org/browse/STCOM-1186
Since the React library insists that keys must be unique and not change during rendering, the ability to specify a key for each element should prevent possible bugs.
Basically, this improvement is meant to help fix [UISACQCOMP-154](https://issues.folio.org/browse/UISACQCOMP-154): changing the order of items in an array (deleting, adding) causes an incorrect display of them, which is associated with using the index of this field as a `key` prop.
Why it's not OK to use an item's index as key - https://react.dev/learn/rendering-lists#why-does-react-need-keys
Provide `getFieldUniqueKey` as a prop for the `<RepeatableField>` component. This function accepts `field`, `index`, and `fields` as arguments.
Set the default `getFieldUniqueKey` prop which …
> STCOM-1186 Provide the `getFieldUniqueKey` prop to define a key for the list items in the `<RepeatableField>` component

- CHANGELOG.md
- package.json
Unpin moment from v2.24; [STRIPES-678](https://issues.folio.org/browse/STRIPES-678) was resolved long long ago and moment < 2.29 suffers from CVE-2022-24785.
> CVE-2022-24785 unpin moment from v2.24

- CHANGELOG.md
- lib/TextField/stories/BasicUsage.js
- lib/global.css
This symptom is present in Chrome, but not Firefox.
Default behavior in Chrome is to only display spinner buttons on number inputs when the input is hovered or focused.
The approach: add a global style to always set the opacity of the `-webkit-inner-spin-button` to `1`, making it visible.
> STCOM-1185 Number spinners are missing from input[type=number]

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- .github/workflows/build-storybook.yml
In CI, bump NodeJS from v16 to v18.
Refs [STCOM-1190](https://issues.folio.org/browse/STCOM-1190)
> STCOM-1190 use NodeJS v18 in CI

- package.json
Remove unused SVG dependencies. We missed this in the scope of the previous PR #2115.
Refs [STCOM-1144](https://issues.folio.org/browse/STCOM-1144)
> STCOM-1144 remove unused svg-related deps

- CHANGELOG.md
- lib/Selection/SingleSelect.js
Add `current` for `selectList` and `container` refs due to the removal of dom-helpers dependency.
[STCOM-1199](https://issues.folio.org/browse/STCOM-1199)
https://github.com/folio-org/stripes-components/assets/77053927/43542479-715d-4812-ba3c-389838332f3e
> STCOM-1199: Add current for selectList and container refs due to removal of dom-helpers dependency.

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
1. Focus the first row after the pagination button is clicked ([screencast](https://github.com/folio-org/stripes-components/assets/77053927/bd73ab5c-0169-451e-8fe0-b390cdd41301)).
2. Focus happens more than once and `handleRowFocus` fires multiple times ([screencast](https://github.com/folio-org/stripes-components/assets/77053927/468c99bb-7616-4437-a909-625c98cf1962)).
1. We wait for the loading to complete so that to have the correct `isSparse` state, since empty items are only added to the `contentData` array after new data has been loaded, which is how it works in [stripes-connect](https://github.com/folio-org/stripes-connect/blob/8714d76a24af275527edc34a3e020f8fbd4d179e/RESTResource/reducer.js#L62). E.g. when we go from the first page to the second, `isSparse` will be false during …
> STCOM-1202: Fix focus of first row and prevent multiple focus calls in MCLRenderer.

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/PrevNextPaginationRow.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- package.json
MCL is moved outside of the scroll container, so the mark-up no longer has to result to any tricks to be a row - and no more having to scroll in order to reach pagination actions!
Since the Prev/Next pagination is no longer rendered within the `renderRows()` function, it isn't able to grab the `rowIndex` from that function's scope, so the value is stored in a variable that the `renderRows()` function now just returns as part of an object, so it gets passed to the pagination in the outer scope (JSX of the `render()` function)
Height of the pagination is measured via a ref, but defaults to 40px in case the ref is unavailable. This is used to affect the height of the scrollable container.
> STCOM-1115 Pin prev/next pagination to bottom of search results.

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
Reset the loading state for the sparse array in MCLRenderer, not just the non-sparse. It currently [disables the Next](https://github.com/folio-org/stripes-components/assets/77053927/dd680d5a-e948-4419-b2fb-4eefa7f7bf49) button.
[STCOM-1203](https://issues.folio.org/browse/STCOM-1203)
https://github.com/folio-org/stripes-components/assets/77053927/72c6009d-74d0-4c52-a8cc-f8d5bfeab52d
> STCOM-1203: Reset the loading state for the sparse array in MCLRenderer, not just the non-sparse.

- lib/MultiColumnList/tests/MultiColumnList-test.js
- package.json
Tests added to make use of interactor filters that were previously unused.
> STCOM-1204 add tests for id and rowcount to MCL tests.

- CHANGELOG.md
- package.json
This appears to be an update in name only. From what I can tell by looking at the release notes, the 7 to 8 bump is a side-effect of changes elsewhere in its monorepo, i.e. there are no actual changes here, but it would be nice to keep the version current in case of future development on the 8.x line.
This work must be done after folio-org/stripes-webpack/pull/122.
> Bump @svgr/webpack from 7.0.0 to 8.1.0

- CHANGELOG.md
- lib/Accordion/tests/AccordionStatusHarness.js
- lib/Accordion/tests/ExpandAllButton-test.js
- lib/Commander/keyboardShortcuts.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
Numerous modules experiencing difficulty with keyboard shortcuts for expandAll/Collapse all not working.
As part of updates for Reactv18, the state of accordions had to change, pushing status to its own key rather than being the whole state. The connected parts that were the cause of this bug, untested at the time, were the centralized keyboard shortcut handlers (`expandAllSections`, `collapseAllSections`) so those were broken, as they were expecting the previous shape of AccordionStatus state.
> STCOM-1207 - fix incorrect accordion keyboard handler, add tests

- CHANGELOG.md
- lib/Callout/Callout.js
Correctly handle callout-removal when multiple callouts are added in quick succession.
Previously, callouts were stored in an array in state and removal was handled by iterating through the list to find an item given its id and then removed via Array.splice on a cloned copy of state. When multiple callouts were added in quick succession, this could lead to the wrong callout being removed because of changes in the underlying state array.
Given callouts have a unique `id` property, storing them by `id` in an object/set, instead of on a list, allows them to be correctly and consistently manipulated.
h/t @usavkov-epam for precisely describing the problem, and proposing a solution, in [UIOR-1145](https://issues.folio.org/browse/UIOR-1145).
Refs …
> STCOM-1209 correctly handle multiple callouts

- CHANGELOG.md
- translations/stripes-components/it_IT.json
The value for `NL` (Netherlands) in the Italian locale was incorrectly copied from `AN` (Netherlands Antilles).
Refs [STCOM-1216](https://issues.folio.org/browse/STCOM-1216)
> STCOM-1216 provide correct Italian value for NL country code

- CHANGELOG.md
- package.json
At present, the `npm-build` job always installs dependencies from the `npm-folioci` repo, even when the build is taking place on a release branch named like `b12.0`. This is problematic because the PR merge will succeed, but the `npm-build-release` job that runs when the tag is applied will fail. I thought we had a Jira for this but cannot find it now.
Anyway, this should resolve several test failures in the v12.0.0 build-npm-release job:
```
FAILED TESTS:
AdvancedSearch
when resetting advanced search
✖ "before each" hook for "should clear rows"
Chrome 117.0.0.0 (Linux x86_64)
NoSuchElementError: did not find text field with label "Search for" within advanced search row with index 0
at throwNoSuchElementError (/tmp/_karma_webpack_142962/commons.js:60996:15)
at findMatchesNonEmpty …
```
> bump @folio/stripes-testing to 4.6.0 for new interactors

- CHANGELOG.md
- lib/AdvancedSearch/AdvancedSearch.js
- lib/AdvancedSearch/components/AdvancedSearchRow/AdvancedSearchRow.js
- lib/AdvancedSearch/readme.md
- lib/AdvancedSearch/tests/AdvancedSearch-test.js
Add `hasMatchSelection` to `<AdvancedSearch>` to hide/show search match selection dropdown.
https://github.com/folio-org/stripes-components/assets/19309423/384fac79-3725-41d7-9422-5ba1d6172021
[STCOM-1211](https://issues.folio.org/browse/STCOM-1211)
https://github.com/folio-org/stripes-authority-components/pull/116
https://github.com/folio-org/stripes-testing/pull/1821
> STCOM-1211 Add `hasMatchSelection` to `<AdvancedSearch>` to hide/show search match selection dropdown.

- CHANGELOG.md
- lib/AdvancedSearch/AdvancedSearch.js
- lib/AdvancedSearch/components/AdvancedSearchRow/AdvancedSearchRow.js
- lib/AdvancedSearch/readme.md
- lib/AdvancedSearch/tests/AdvancedSearch-test.js
(#2141)
* STCOM-1211 Add `hasMatchSelection` to `<AdvancedSearch>` to hide/show search match selection dropdown.
* STCOM-1211 Added tests for hiding AdvancedSearch match selector
* STCOM-1211 Updated AdvancedSearch match select data-test ids
(cherry picked from commit 9afa4ee8ca8eaa8b87c24decada3864e1ff86a69)
> STCOM-1211 Add `hasMatchSelection` to `<AdvancedSearch>` to hide/show search match selection dropdown

- CHANGELOG.md
- lib/Datepicker/Calendar.css
We display the spinner on all `input[type="number"]` in our global styles. Recently I discovered some global styles (soon to be remedied in `ui-plugin-query-builder`). The changes in this pr isolate and specify to datepicker's year input so that it we can prevent this from happening again in the future.
> STCOM-1225 Spinner button hidden in datepicker calendar.

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
Subtract pagination row height from MCL row container to not show scrollbar when there are fewer rows than what can be displayed.
[STCOM-1224](https://issues.folio.org/browse/STCOM-1224)
> STCOM-1224 Include pagination height in MCL container height calculation

- CHANGELOG.md
- lib/SearchField/SearchField.js
- lib/SearchField/readme.md
Added `indexRef` and `inputRef` props to `<SearchField>`
[STCOM-1231](https://issues.folio.org/browse/STCOM-1231)
https://github.com/folio-org/stripes-smart-components/pull/1413
https://github.com/folio-org/ui-inventory/pull/2335
> STCOM-1231 Added `indexRef` and `inputRef` props to `<SearchField>`

- CHANGELOG.md
- lib/Pane/Pane.css
Printing with a detail pane open should print only the detail pane, without printing the others. The before state is captured in the associated JIRAs.
Adjusted the styles of panes to have only the last pane visible and at 100% width when the page is printed.
Used a combination of hiding panes in print mode, and displaying the last pane via a higher specificity pseudo-selector (`nth-last-of-type(1)`)
The `flex` property is `!important` in this case in order to override the inline `flex` styling that is applied to the element.
Two stories, https://issues.folio.org/browse/STCOM-1228 and https://issues.folio.org/browse/STCOM-1229 are covered by this...
After:
Inventory:
Users:
> STCOM-1228 Print styling of panes (users want to print the detail pane, but full screen display is printed)

- CHANGELOG.md
- lib/MessageBanner/MessageBanner.module.css
- lib/PaneHeader/PaneHeader.css
All changes agreed with **Kimie Kester** (check comment section of [STCOM-1222](https://issues.folio.org/browse/STCOM-1222))
After this PR is resolved, we will fix the following accessibility issues:
1. In Pane's subtitle, the contrast and line-height will be increased, which will make the text more readable
2. The text color in the MessageBanner component has been changed to increase contrast (previously it was green on green)
> STCOM-1222 Accessibility Issues - stripes components

- lib/Editor/readme.md
Remove the extraneous newline after `formats` so the following lines are correctly formatted.
> Editor: correctly format "Basic props" table

- CHANGELOG.md
- lib/AdvancedSearch/AdvancedSearch.js
- lib/AdvancedSearch/hooks/useAdvancedSearch/useAdvancedSearch.js
- lib/AdvancedSearch/tests/AdvancedSearch-test.js
Use the default search option instead of an unsupported one in Advanced search.
[STCOM-1242](https://issues.folio.org/browse/STCOM-1242)
https://github.com/folio-org/stripes-components/assets/77053927/ee8c4f8b-a8a8-4fb2-b312-29e257032de1
> STCOM-1242: Use the default search option instead of an unsupported one in Advanced search.

- lib/Timepicker/tests/Timepicker-test.js
Looks like moment got a bit more strict when handling single digit vs double digit parsing of time values, https://github.com/moment/moment/pull/5592
Tests, in this case, were testing with a value that didn't exactly match the format anyhow, so they were a bit unrealistic to start with.
If this causes more grief than this, we might have to consider locking to moment v2.29.4 :/
> Fix timepicker tests

- lib/InfoPopover/readme.md
The props `buttonProps` and `popperProps` are undocumented; this adds them to the README.
> Add missing InfoPopover props

- lib/MetaSection/readme.md
Add undocumented props `inlineLayout`, `noBackGround`, and `useAccordion` to the `<MetaSection>` README.
> Document undocumented props within MetaSection README

- lib/Popover/readme.md
This prop is required, as denoted by the component's prop-types.  The README should denote this requirement.
> Document Popover children prop as required

- lib/ConfirmationModal/ConfirmationModal.js
- lib/ConfirmationModal/readme.md
This fixes the following:
- button labels allow `node`s (via prop-types and the code itself defaults to `<FormattedMessage>` nodes), so the README must be updated
- `heading` is limited to a `string` since it's used as an aria-label; the prop-types must be updated
- `buttonStyle` and `cancelButtonStyle` were undocumented.
> Update ConfirmationModal prop types/documentation

- lib/TextArea/TextArea.js
- lib/TextArea/readme.md
- lib/TextArea/stories/TextArea.stories.js
This adds a README for the `<TextArea>` component.  It also removes the `type` prop, as it is unused and does not exist on `<textarea>`, only `<input>`.  My hunch is that it was accidentally copied from `TextField`.
> Add README for TextArea

- lib/TextLink/readme.md
This adds a new example and a few missing props to the readme of `<TextLink>`
> Update TextLink README

- lib/Popper/Popper.js
- lib/Popper/readme.md
There are several props available to the `Popper` component which were not documented in the README.
Additionally, the placements `auto-start` and `auto-end` were missing from the `AVAILABLE_PLACEMENTS` array, despite being valid (looks like I missed these in https://github.com/folio-org/stripes-components/pull/2004, whoops).
> Fix Popper documentation consistency

- lib/Checkbox/readme.md
The `label` prop accepts a node in the prop-types and [the usage concurs](https://github.com/folio-org/stripes-components/blob/master/lib/Checkbox/Checkbox.js#L157); this brings the README in line with this.
> Update Checkbox label prop documentation

- lib/RadioButtonGroup/RadioButtonGroup.js
- lib/RadioButtonGroup/readme.md
`warning` and `error` can be nodes, too!
Even though `PropTypes.node` contains `PropTypes.node`, I listed both for consistency with the others.
- added more examples to the README
> Update RadioButtonGroup prop types

- lib/FilterControlGroup/FilterControlGroup.js
- lib/FilterGroups/FilterGroups.js
- lib/FilterGroups/readme.md
This updates the FilterGroups README to list properties in tables, consistent with most other component documentation in FOLIO, and increasing readability.  It also restricts the `prop-types` of `label` to a `string`, which is required due to its usage as an ARIA label.  Finally, it also adds a few undocumented props (one of which is required!)
> Cleanup FilterGroups README

- lib/MessageBanner/MessageBanner.js
- lib/MessageBanner/readme.md
- lib/MessageBanner/stories/Dismissible.js
- lib/MessageBanner/stories/MessageBanner.stories.js
- lib/MessageBanner/tests/MessageBanner-test.js
This prop has been replaced by `dismissible` and the code accounts for both spellings; we should document the mispelled one as deprecated.
> Deprecate <MessageBanner> dismissable prop

- CHANGELOG.md
- lib/Icon/Icon.js
- lib/Icon/tests/Icon-test.js
[STCOM-1165](https://issues.folio.org/browse/STCOM-1165)
We have ensured that aria attributes are rendered correctly by formation via the util function.  All other components that were in the list in that story are working correctly since it pass `aria-label ` directly.
> STCOM-1165: Format aria attributes in `<Icon>`

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/Accordion/AccordionSet.js
Toggling accordions with open overlay components can cause z-index fighting of content and subsequent accordion headers.
Render the content of accordions with stepping z-index - top accordion gets the highest and the last gets a z-index of 1. This keeps the content rendered in front of headers and content from subsequent accordions.
Accordions do *usually get registered in `BoundingClientRect.top` order with standard registration - but if any similar problem does re-appear, we can apply some more intensive sorting logic on the accordions.
Bonus points - we lose some state tracking/updating with the 'focus' events, which were inadequate for maintaining a dynamic z-index.
Before:
After:
> STCOM-1238 Accordions - apply content  z-index in reverse-registration order

- lib/AdvancedSearch/AdvancedSearch.js
- lib/AdvancedSearch/readme.md
- Children is not required (listed as optional in README and the code performs a ternary to fail-safe if it's missing)
- `hasMatchSelection` and `hasQueryOption` both have default props, so should be denoted as optional in the README
> Update AdvancedSearch prop documentation

- CHANGELOG.md
- lib/sharedStyles/interactionStyles.css
Show action buttons in correct color
https://issues.folio.org/browse/STCOM-1256
Revert removing comma that was removed by mistake in https://github.com/folio-org/stripes-components/pull/2212/files#diff-a346a5e30d164673f59d1283343c9ba1b507f01e94e09b325ad2ac4fffedc6e6L29
> STCOM-1256: Show action buttons in correct color

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/stories/service.js
- lib/MultiColumnList/tests/MCLHarness.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- lib/Timepicker/tests/Timepicker-test.js
This PR resolves an issue with MCL not restoring it's loading state to false with non-sparse `contentData`. It cherry picks from changes merged to master in https://github.com/folio-org/stripes-components/pull/2223 
As well as an update for the Timepicker tests  (remove leading 0's on time strings - who types those anyway?) from https://github.com/folio-org/stripes-components/pull/2201 in order for those to pass.
> CSP2 - cherry-pick mcl fix from master/STCOM-1262

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/FilterControlGroup/FilterControlGroup.js
- lib/FilterGroups/FilterGroups.js
https://folio-org.atlassian.net/browse/STCOM-1192
Related inputs are commonly group within a `<fieldset>` element or a `div` element using `role=group`. Both do similar things, assigning a top-level label. The downside to fieldset is that it has a built-in styling that has to be overridden and `<legend>` elements can also be stubborn for styling, although that is less of a matter. A `div[role="group"]` with an `aria-label` suffices.
`<Filtergroups>` often wouldn't be able to render a decent unique id due to objects (`<FormattedMessage>`) being passed as the label to the groups, despite propTypes dictating it be a `string`.  A small utility function was used to derive the string from a passed `FormatMessage` instance, converting it to a call to `formatMessage` fron `Intl` contenxt. …
> STCOM-1192 Group checkboxes in FilterGroups (a11y)

- CHANGELOG.md
- package.json
Includes: 
* MCL loading bugfix - Refs [STCOM-1262](https://folio-org.atlassian.net/browse/STCOM-1262).
> Release v12.0.5

- CHANGELOG.md
- lib/Accordion/headers/FilterAccordionHeader.js
Fix `<FilterAccordionHeader>` does not have correct `aria-label` when `label` prop type is string
[STCOM-1271](https://folio-org.atlassian.net/browse/STCOM-1271)
> STCOM-1271 Fix `<FilterAccordionHeader>` does not have correct `aria-label` when `label` prop type is string

- .storybook/stcom-webpack.config.js
- CHANGELOG.md
- lib/Accordion/Accordion.js
Accordions with overlay components could have their overlays overlapped by other accordions due to z-index issues.
What we've previously done...
Accordions content would overlap overlays/dropdowns from previous accordions... (render with reverse z-index order to accordion index)
fixed, but..
Accordions content would overlap overlays/dropdowns from the following accordions...(have the focused accordion assume highest zindex from the set)
fixed, but
Accordions/overlays would go back to being overlapped if focus left the accordion or went to another pane...
In this PR, when focus moves to the accordion, it will find/assume the highest z-index among other accordions. It will retain this same z-index after it is blurred. If an accordion already has the highest z-index among accordions, it will …
> STCOM-1238 Accordion vs overlay z-index issues.

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/Selection/SelectList.js
https://folio-org.atlassian.net/browse/STCOM-1238
One culprit for z-index fighting in Orders is late-game calls to `focus()` - `<Selection>` code contains a late-game focus where the control of the list is always re-focused after the list is closed. This isn't always necessary - especially in cases where the user has intentionally focused somewhere else. When the control of one accordion A was open, and a control in a accordion B was clicked, accordion B's z-index logic would fire, giving it the highest value, but the control in accordion A would execute its `focus()` logic - causing the z-index logic to fire yet again and place Accordion A back at the top of the z-index stack so that it would overlap the control of Accordion B.
The fix here ensures that focus is only moved back to the …
> STCOM-1238v2 - reduce 'focus()' calls within SelectList/Selection

- lib/ConfirmationModal/ConfirmationModal.js
- lib/ConfirmationModal/readme.md
Fixes a regression in #2193. The documentation was incorrect: the `heading` is used as the `label` on our `<Modal>` component, but the `label` prop accepts nodes and is not used as part of the ARIA label in any way.
> Allow nodes for ConfirmationModal heading

- CHANGELOG.md
- lib/Paneset/insertByClientRect.js
Avoid an NPE in `Paneset` by null-checking a ref before dereferencing it.
Refs [STCOM-1235](https://folio-org.atlassian.net/browse/STCOM-1235)
> STCOM-1235 validate refs before dereferencing them

- CHANGELOG.md
- lib/sharedStyles/form.css
Problem
Form control styles for `:focus`, and validation feedback are not showing up in the UI. Recently the postcss-nesting plugin was removed from our CSS pipeline, which caused the problem to reveal itself. 
`form.css` contained a nested **prefixed** pseudo-element selector for getting rid of the native 'clear X' that Microsoft Edge renders within text inputs. Moving this nested pseudo-selector to the end of the child declarations resolved the issue. Native `clear X`'s are still hidden as well.
Before:
After
> STCOM-1284 BUG- form control highlights not rendering.

- CHANGELOG.md
- lib/TextArea/TextArea.js
- lib/TextArea/readme.md
- lib/TextArea/tests/TextArea-test.js
`<textarea>`, as opposed to `<input>`, doesn't by default place the cursor at the end of the value when mounting. When we don't want the default behavior, we can pass the `isCursorAtEnd` property and place the cursor at the end.
[STCOM-1289](https://folio-org.atlassian.net/browse/STCOM-1289)
https://github.com/folio-org/stripes-components/assets/77053927/12d3ecfd-c0f3-42c9-a48e-71f137d31526
> STCOM-1289: Add `isCursorAtEnd` property to `TextArea` to place the cursor at the end of the value.

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/readme.md
https://folio-org.atlassian.net/browse/STCOM-1297
Add `react-beautiful-dnd` placeholder support to enhance the drag-and-drop experience. The placeholder ensures that the layout remains stable and consistent during drag actions by temporarily occupying the space of the dragged element. This prevents content shifts or collapses, providing a smoother and more visually consistent user interface. Currently, the absence of a placeholder causes the list height to jump by the height of the dragged element, leading to a jarring user experience.
FOLIO uses the `react-beautiful-dnd` library to implement DnD, which operates with `<Draggable>` and `<Droppable>` entities. The Droppable context provides the `provided` object as a render prop, which contains a placeholder for the draggable element. …
> STCOM-1297 Add 'dndProvided' prop for MCLRenderer to support DND placeholder

- CHANGELOG.md
- lib/MultiSelection/MultiSelect.css
- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/SelectOption.js
- lib/MultiSelection/readme.md
- lib/MultiSelection/tests/MultiSelection-test.js
Instance records have Optimistic Locking so we need to prevent users from editing tags while Instance is being updated
Add `inputRef` and `showLoading` props to `<MultiSelection>`
https://github.com/folio-org/stripes-components/assets/19309423/d9f0f116-1c8e-4ba9-ac93-9172199212ec
[STCOM-1299](https://folio-org.atlassian.net/browse/STCOM-1299)
> STCOM-1299 Support Optimistic Locking in Tags - allow disable and show loading indicator in `<MultiSelection>`.

- CHANGELOG.md
- lib/MessageBanner/MessageBanner.module.css
- lib/MessageBanner/stories/BasicUsage.js
[STCOM-1276](https://folio-org.atlassian.net/browse/STCOM-1276)
After changes:
focused:
> STCOM-1276 Contrast of links within default MessageBanner

- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/tests/MultiSelection-test.js
- lib/Selection/Selection.js
- lib/Selection/utils.js
- Update `<MultiSelection>` tests/interactor
- Only execute filtering logic in `<Selection>` when the filter has a value - this caused a handful of issues with initial rendering of pages throwing errors - but it does appear there are some ui-modules that pass components directly to dataOption labels vs the strings that those components might render via `react-intl`
- Properly send `<Selection>` value string to its `onChange` handler.
- Wrap `<Selection>` in `formField` HOC so that it can conform to React-Final-Form's expectations.
Will open a corresponding PR in stripes-testing. ~These tests will not pass without it.~ Locally patching interactors to get this PR over the hump and hopefully fix the major functional issues.
> STCOM-1304 - Selection/MultiSelection bugfix

- lib/Selection/Selection.js
- lib/Selection/tests/Selection-ReduxForm-test.js
Selection needed to have `onBlur` and `onFocus` passed to its control in order to correctly validate/display validations methods, update `meta.touched` through `redux-form`.
> STCOM-1304v2 - redux-form compatibility - Selection.

- CHANGELOG.md
- lib/MultiSelection/MultiSelectOptionsList.js
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/tests/MultiSelection-test.js
- lib/Selection/Selection.js
- lib/Selection/tests/Selection-ReduxForm-test.js
- lib/Selection/tests/Selection-test.js
- translations/stripes-components/en.json
https://folio-org.atlassian.net/browse/FAT-14783
With a handful of automated tests still failing, mark-up adjustments needed to be made for `<Selection>` and `<MultiSelection>`. Mostly these were omissions from the original rewrite of the component. Changes include:
- Wrapping `<Selection>`'s value in its own exclusive element.
- Applying the `name` attribute correctly within `<Selection>`
- Correctly labeling the dropdown trigger in in `<MultiSelection>`
- Correcting the implementation of `aria-labelledby` application in `<MultiSelection>`
Tests were updated to broaden their range of interactor usage.
This includes an additional bugfix cited in [STCOM-1308](https://folio-org.atlassian.net/browse/STCOM-1308) cited in the Automated tests issue. The fixed involved swapping the results on a …
> FAT-14783 Fixes to align with interactor/automated tests.

- CHANGELOG.md
- lib/SearchField/SearchField.js
Pass the `isCursorAtEnd` property to the textarea props in the `SearchField` component to have a cursor at the end of the entered search term.
[STCOM-1307](https://folio-org.atlassian.net/browse/STCOM-1307)
> STCOM-1307: Pass the `isCursorAtEnd` property to the textarea props in the `SearchField` component.

- CHANGELOG.md
- lib/MultiSelection/MultiSelection.js
Changed the default popper modifiers to use `viewport` for overflow avoidance rather than `scrollparent` - short list problems!
Before:
After:
> STCOM-1309 MultiSelection menu overlaps input when rendered within an Editable List.

- CHANGELOG.md
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/tests/MultiSelection-test.js
Not always, but some instances of multiselect are effected by this... all storybook examples work. The refactor of Multiselection used `===` to dedupe its selected items list. This code has been updated to use `isEqual` to check the values held within the object for equality.
Additionally, this PR changes the internally generate label id to match that used in testing, and reflects changes in the Multiselect interactor within the test suite. (`fillin === filter`)
I also discovered that `htmlFor` wasn't properly assigned in MultiSelect, so that is resolved. Clicking the label text will now focus the filter field.
> STCOM-1311 User can select an item multiple times in MultiSelect

- CHANGELOG.md
- lib/Selection/Selection.js
- lib/Selection/tests/Selection-test.js
- lib/Selection/tests/SingleSelectionHarness.js
If the component's `value` is set externally, the component would need to update its own internal state and call any coordinating change handlers. Added tests for this scenario.
> STCOM-1312 Update Selection with value from external changes.

- CHANGELOG.md
- lib/Selection/Selection.js
- lib/Selection/tests/Selection-test.js
- lib/Selection/tests/SingleSelectionHarness.js
- lib/Selection/utils.js
https://folio-org.atlassian.net/browse/STCOM-1313
Since the `selectedItem` was originally determined early on, it formed a race condition if `dataOptions` still had yet to populate since they were being obtained dynamically. This PR makes it so that when the `dataOptions` do load, the state will be updated and the component will make another attempt to find the selected item.
Additionally - there as an error message mentioning that `selectedItem` was transitioning from 'uncontrolled' to 'controlled' - I believe this was due to the `getSelectedItem` code returning undefined (er, something that amounted to `undefined` like `arrayVar[-1]`) instead of `null` - let's not talk about the overbearing error messages... like it has an `onChange`, whadayawant?
Additionally, fixed a minor but very …
> STCOM-1313 Update Selection internal state when dataOptions are received

- CHANGELOG.md
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/SelectOption.js
- lib/MultiSelection/tests/MultiSelection-test.js
- lib/MultiSelection/tests/MultiSelectionHarness.js
https://folio-org.atlassian.net/browse/STCOM-1311
Round one of fixes addressed deduplication of selected items by using `isEqual` when determining if the chosen item is already selected or not, then it called downshift's own state management functions to handle addition or removal of the chosen item.
These problems (Multiselect not removing items, not resetting) ran a bit deeper.
Item removal was calling downshift's own 'removeSelectedItem', but the function within that was using strict equality against the result of a utility function (`itemToKey`) that needed to be overridden - otherwise it amounts to `object === object` which can be true but rarely and odd because all keys/values would be equal - so not intuitive for this. The override of `itemToKey` to use `itemToString` bakes the …
> STCOM-1311 MultiSelection setting value prop after render should be reflected in component state.

- lib/MultiSelection/tests/MultiSelection-test.js
- lib/MultiSelection/tests/MultiSelectionHarness.js
- lib/Selection/Selection.js
- lib/Selection/tests/Selection-test.js
- lib/Selection/tests/SingleSelectionHarness.js
With these changes, the component will wait for a value prop to release its internal sentinel instead of releasing after `onChange` is called. Instead of hastily updating based on the value prop that its getting.
The component can be optimistic, but it should definitely be provided with a value prop.
> STCOM-1318 Selection regains optimism for indicating selected item.

- lib/Selection/Selection.js
- lib/Selection/tests/Selection-test.js
- lib/Selection/tests/SingleSelectionHarness.js
Since the implemenation for handling value props from outside of the component, we notice instances of `onChange` handlers happening multiple times as per [STCOM-1319](https://folio-org.atlassian.net/browse/STCOM-1319) where a query search will remain intact after `resetAll` is pressed once. This was due to a new render cycle happening even prior to the updated state of the component landing. In class-based react implementation, we had a callback for `setState` so that we could run logic in a space where we were assured that state had updated. It's possible for us to write a hook that could accomplish something like, but I decided to try and revisit the usage of downshift's state within the component, and if we could solely rely on that state, we could consolidate the onChange calls …
> STCOM-1319 Selection - consolidate/reduce onChange calls

- lib/Selection/Selection.js
- lib/Selection/tests/Selection-test.js
- lib/Selection/tests/SingleSelectionHarness.js
Problem: Selection won't set update its internal value if if it has a non-null `selectedItem`.
Approach: append the conditional to support value changes if either the `selectedItem` is null *or* if the incoming `value` is a valid value by checking the outcome of `getSelectedObject`.
> STCOM-1320 - Selection needs to conform its state when an item is selected. 

- lib/Selection/Selection.js
- lib/Selection/tests/Selection-ReduxForm-test.js
Prior to refactor, `Selection` provided no `onBlur` _event_ to its supplied handler: https://github.com/folio-org/stripes-components/blob/b55b8c0449490be4c91e050fa3b7e5aa8ada0ea7/lib/Selection/SingleSelect.js#L504
This is dishonest, but it got us by.
Love it or hate it, Redux Form/react-final form perform an under-the-hood change to the value when the element is blurred. This change event is even outside of the realm of the component's own 'onChange' handler. Adding the value to a `value` attribute on the rendered control keeps the blur event honest and allows the component to retain its value.
As per usual, tests are expanded slightly to address the case.
> STCOM-1320 Selection should maintain its value as far as redux-form is concerned.

- lib/MenuSection/MenuSection.js
[STCOM-1191](https://folio-org.atlassian.net/browse/STCOM-1191)
Updated MenuSection component to have visual headings be designated as such in the markup by changing base MenuSection labelTag designation from `div` to `h1`.
> STCOM-1191

- CHANGELOG.md
- lib/MultiColumnList/MCLRenderer.css
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/readme.md
- lib/MultiColumnList/stories/BasicMCL.js
MLC: show the sort indicator next to the names of sortable columns, but don't show it for the currently sorted column.
Add the optional `showSortIndicator` property, which will enable a CSS pseudo-class containing the necessary icon in the `background`. Enabling also takes into account whether the column is sortable or not currently sorted.
[STCOM-1328](https://folio-org.atlassian.net/browse/STCOM-1328)
https://github.com/user-attachments/assets/12212e48-e4e9-4ab8-937a-50105c518336
> STCOM-1328: Add the `showSortIndicator` property to MLC to display a sort indicator next to the sortable column names.

- CHANGELOG.md
- lib/Datepicker/Datepicker.js
- lib/Datepicker/readme.md
- lib/Datepicker/tests/Datepicker-test.js
Add the `hideCalendarButton` property to hide the calendar icon button in `Datepicker`.
[STCOM-1342](https://folio-org.atlassian.net/browse/STCOM-1342)
> STCOM-1342: `Datepicker` - add the `hideCalendarButton` property to hide the calendar icon button.

- lib/Modal/Modal.js
Because jest/jsdom seems to want to mark all `<dialog>` elements as `display: 'none'` which doesn't allow interactors to find things, no way, no how unless `{visible: false}` is specified.
> Modal: Use div[role=dialog] instead of dialog element

- CHANGELOG.md
- lib/Accordion/headers/FilterAccordionHeader.js
- translations/stripes-components/en.json
- translations/stripes-components/en_US.json
`FilterGroups` renders its heading fine, just doesn't provide a string to the tiny `clear` X button for resetting the filters for the group. This PR moves a static string to the translations and calculates the proper string before applying it to the button.
The logic within `filtergroups` was potentially allowing a raw component/an instance of  `<FormattedMessage>` through to the aria label. The new logic just generates a string to supply to the aria-label instead of passing the `<FormattedMessage>` directly. 
The old aria-label: "Clear selected filter for [Object object]'
The new aria-label: 'Clear selected Status filters'
> STCOM-1337 properly render string for filterGroups' clear button aria-label

- CHANGELOG.md
- lib/Accordion/Accordion.js
- lib/Accordion/headers/DefaultAccordionHeader.js
- lib/Accordion/headers/FilterAccordionHeader.js
- lib/AdvancedSearch/components/AdvancedSearchModal/AdvancedSearchModal.js
- lib/Commander/CommandList.js
- lib/MetaSection/MetaAccordionHeader.js
- lib/MultiColumnList/CellMeasurer.js
- lib/MultiColumnList/MCLRenderer.js
- lib/MultiColumnList/RowMeasurer.js
- lib/MultiColumnList/tests/MultiColumnList-test.js
- package.json
- yarn.lock
This touches Accordion (including MetaSection), MCL, and AdvancedSearch so far...
This goes in-hand with https://github.com/folio-org/stripes-react-hotkeys/pull/44 (Merged!)
Summary of changes:
- In general, Instances of Hotkeys are provided with a ref to a wrapping element.
- AdvancedSearch Modal: wrapping div added.
- MCL components for dom-measuring refactor to contain their rendered elements/implement as a child function providing the necessary ref as opposed to using `findDOMNode`
- Accordion headers wrapped in a div with a ref to that div provided to HotKeys.
> STCOM-1343 refactor away from `findDOMNode`

- CHANGELOG.md
- hooks/tests/useOverlayContainer-test.js
- hooks/useOverlayContainer/index.js
- hooks/useOverlayContainer/useOverlayContainer.js
- lib/Modal/Modal.js
- lib/Modal/WrappingElement.js
- lib/MultiColumnList/MCLRenderer.js
- lib/Popper/Popper.js
- tests/helpers/getHookExecutionResult.js
- util/StripesOverlayContext.js
- util/useOverlayContainer.js
We've seen a common issue with 'Overlay' components (`Selection`, `Datepicker`, etc) where they end up overlapped by the boundaries of their scrollable containers. Common among these, a `usePortal` boolean prop can be used to render them into the centralized 'OverlayContainer' element, but it isn't always so ergonomic to add or to know when it should be added.
The functionality in this PR adds a context to common containers where overflow can be problematic: Modals and MCL's. The main implementation exists within the `Popper` component, which is consumed and used by all of the 'Overlay' components. When any of the 'Overlay' components are used within a Modal or an MCL, they will automatically behave as thought a `usePortal` prop is applied.
Wrap `Popper` in an HOC (it's still a …
> STCOM-1335 add `StripesOverlayContext` to Modal, MCL... implement in Popper

- CHANGELOG.md
- lib/Selection/Selection.js
For cases where the supplied `dataOptions` are checked/could change their internal values after being provided, without the count itself changing, `<Selection>` is not updating.
Approach:
Pass the whole options array rather then only the length of the array as memoization dependency so that changes will be picked up.
> STCOM-1346 Selection not reflecting changes in `dataOptions`.

- CHANGELOG.md
- lib/Commander/CommandList.js
To refactor away from `findDOMNode` usage, `<CommandList>`'s internally rendered `<HotKeys>` instance has to be provided with an element or a ref to an element. This was originally implemented with a wrapping `<div>`, but this proved problematic when the element was nested as a flexbox child/within a paneset (See the ugly JIRA above).
This PR removes the offending wrapping div, resolving any style issues that would rise from it. Since `CommandList` is commonly used at the top level of an App, a default binding of `document.body` should be adequate to use. If this proves problematic, a ref to an existing element can be provided.
> STCOM-1351 Scope `<CommandList>` to `document.body` by default rather that wrapping div.

- CHANGELOG.md
- lib/Modal/Modal.js
During refactor of our modals, an inline style was added, hiding the overflow of the content div. This PR just removes that inline style. Tested with the `ui-plugin-find-users` modal as well as the applicable keyboard shortcuts modal.
> STCOM-1348 Keyboard shortcut modal missing scrollbar.

- package.json
- yarn.lock
When the dependencies were last updated, my fingers got lazy and only bumped the minor version rather than resetting the patch number.... chaos ensued in a platform build as the correct version wasn't able to be found :(
> Use proper stripes-react-hotkeys version - 3.1.5 -> 3.1.0

- CHANGELOG.md
- lib/RadioButton/RadioButton.js
Instances where a user *can affect the read-only status of a radio button in the UI warrant a visible indication of the read-only state - the lock icon. The more common case is that a user cannot affect this status - in which case, rendering interactive controls should be avoided in the first place. Rendering of the lock icon is handled by our `<Label>` component - internally rendered by RadioButton.
Looking at the history to this, the lock icon was displayed/not displayed without a great deal of reason provided. The change only happens now that we have a specific use-case for this feature. The lock icon apparently still exists in visual designs from `ux.folio.org`. Kimie has also included it in mock-ups.
I'm for the existence of the icon, as it provides a good 'at-a-glance' discernment …
> STCOM-1367 - RadioButton - pass readOnly prop to internal Label

- CHANGELOG.md
- lib/TextArea/TextArea.js
- lib/TextArea/tests/TextArea-test.js
`TextArea` - move focus to the field after clearing the field by clicking on the `x` icon. The same approach is applied as in the `TextField`.
[STCOM-1369](https://folio-org.atlassian.net/browse/STCOM-1369)
https://github.com/user-attachments/assets/8e180e7e-86c7-4a1c-9b59-46512182552e
> STCOM-1369: `TextArea` - move focus to the field after clearing the field by clicking on the `x` icon.

- CHANGELOG.md
- lib/Selection/Selection.css
- lib/Selection/SelectionList.js
- lib/Selection/tests/Selection-test.js
Problem - when the scroll bar of a long list was clicked with the mouse, it would close the list.
Upon deeper inspection, when the scroll bar is clicked, focus would travel outside of the list - to the element in behind the list - typically to the pane content div - causing the menu to close.
Approach: 
Adding `tabIndex="-1"` to the options list allows it to catch focus so that focus can stay within the dropdown, keeping it open.
> STCOM-1371 Selection Bug - scrollbar not working with mouse for long lists.

- CHANGELOG.md
- lib/Selection/Selection.js
- lib/Selection/stories/BasicUsage.js
- lib/Selection/tests/Selection-test.js
Conditional rendering logic within Selection is currently implemented for truthy/false-y values - but false-y includes `''` empty strings, so empty string values/labels were improperly rendered, keeping them from being selected.
Approach: switched to checking for `undefined` rather than truthiness or falsey-ness.
Test added for selecting an empty string value.
> STCOM-1373 - Selection - blank options are not selectable.

- CHANGELOG.md
- lib/RepeatableField/RepeatableField.js
- lib/RepeatableField/RepeatableFieldContent.js
This is cited in a hanful of issues.... [STCOM-1372](https://folio-org.atlassian.net/browse/STCOM-1372) is the first. This solution uses a useEffect/MutationObserver combination for focus management in repeatable field.
Since state for RepeatableField is kept outside of the component, DOM state is the main way we have to control this behavior at the component level.
Pseudo-logic for this is as follows:
Manage focus only if the user has already interacted with the list (via `onFocus` handler)
When an item is added, move focus to the first focusable element within that item.
If items are removed from the list, focus the first focusable element within the item's previous sibling.
> STCOM-1372 Use mutationobserver for focus management in repeatable field

- CHANGELOG.md
- translations/stripes-components/en.json
- util/countries.js
Add Kosovo to the list of countries and translations. Codes pulled from https://en.wikipedia.org/wiki/Country_codes:_J%E2%80%93K#_Kosovo.
Refs [STCOM-1354](https://folio-org.atlassian.net/browse/STCOM-1354)
> STCOM-1354 add Kosovo to country list

- CHANGELOG.md
- package.json
- yarn.lock
Bump `stripes-react-hotkeys` to `v3.2.1` for compatibility with the changes it made in STCOM-1285 to maintain compatibility.
Refs [STCOM-1343](https://folio-org.atlassian.net/browse/STCOM-1343)
> STCOM-1343 bump stripes-react-hotkeys for compatibility

- CHANGELOG.md
- lib/CurrencySelect/tests/CurrencySelect-test.js
- package.json
- yarn.lock
Data that was uniquely keyed up through `v2.1.0` is not so in `v2.2.0` (there are multiple entries for the currency `Bolívar Soberano`). It is not clear if the uniqueness property was intentional or incidental (see https://github.com/freeall/currency-codes/issues/46).
Since we have tests that directly rely on the data we import, we should _always_ depend on a specific version in order to avoid this kind of problem, and so we can choose when to address it instead of being forced to address it whenever the third-party dependency happens to publish a new release.
Refs [STCOM-1379](https://folio-org.atlassian.net/browse/STCOM-1379)
> STCOM-1379 pin currency-codes to avoid unexpected dupes

- CHANGELOG.md
- lib/Selection/Selection.css
- lib/Selection/Selection.js
Prior to refactor, the outer element for selection had an inline style that set the width to `100%`  https://github.com/folio-org/stripes-components/blob/4b25bb96a529c2b75091a127232791bef244e3e8/lib/Selection/SingleSelect.js#L675-L678
This change re-applies that style as a CSS class.
> STCOM-1332 Selection should occupy the full width of its container.

- CHANGELOG.md
- lib/Modal/WrappingElement.js
See [UIQM-732](https://folio-org.atlassian.net/browse/UIQM-732) for the module-level bug.
Modal hangs its escape key listener on the `document` rather than one of its owned elements. this can be problematic if an app has a `escape` shortcut key that's set up the same way. See the UI-QuickMarc bug for details. TLDR: `escape` key in dirty form should trigger the confirmation modal, but instead it opens the modal and immediately closes it, exiting the form without any confirmation.
> STCOM-1382 Assign modal escape key handler to modal element rather than document

- CHANGELOG.md
- lib/Card/Card.js
Module-level bug featuring card: [STCOM-1381](https://folio-org.atlassian.net/browse/STCOM-1381)
As with the inclusion in `<Modal>` and `<MCL>`, `<Card>` is another container where including a `<StripesOverlayContext>` can be helpful. Card container styling is overflow: hidden so portal usage is necessary here.
> STCOM-1384 Wrap Card render output with StripesOverlayContext

- CHANGELOG.md
- lib/MultiSelection/MultiSelection.js
- lib/MultiSelection/tests/MultiSelection-test.js
Known locations affected: Tags (linked in main JIRA), [Agreements->Settings ->Supplementary properties](https://folio-org.atlassian.net/browse/STSMACOM-877) (closed as duplicate)
Multiselection needs to reset the filter value when an option's `onSelect` handler is called (actions API for Multiselection) Otherwise, the filter value will not be reset as it usually is through typical value selection logic.
> STCOM-1385 Clear filter value after an action is chosen from MultiSelection

- .github/CODEOWNERS
Refs [STCOM-1389](https://folio-org.atlassian.net/browse/STCOM-1389)
> STCOM-1389 implement CODEOWNERS

- CHANGELOG.md
- lib/MenuSection/MenuSection.js
We saw it coming. We did. Zak should've pressed me. We should have changed the default `labelTag` back then, in [STCOM-1191](https://folio-org.atlassian.net/browse/STCOM-1191). Despite so much documentation around the internet regarding the `<section>` tag and its contained heading supporting `h1-h6`, etc... there's a scarce amount of connection to the safety-first best-and-long-practiced pattern of ONE SINGLE H1 PER-PAGE! (regardless of visiblity status.) Regardless of what apparent outcome of articles like this ([`h2`  is the apparent ceiling for `sections`, period](https://www.webucator.com/article/html-heading-levels-and-sectioning-content/)) Having multiple `<H1>`'s show up to any validator and expecting validators/audit tools of any kind to read the minds of browsers/browser …
> STCOM-1392 Use `h3` instead of `h1` for menu.

- package.json
- yarn.lock
Bump `@folio/stripes-testing` from `^4.7.0` to `^4.9.0` (follow-up). More [details.](https://github.com/folio-org/stripes-components/pull/2409#pullrequestreview-2532057330)
[STCOM-1195](https://folio-org.atlassian.net/browse/STCOM-1195)
> STCOM-1195: Bump '@folio/stripes-testing' from ^4.7.0 to ^4.9.0 (follow-up).

- CHANGELOG.md
- lib/Datepicker/Calendar.css
- lib/variables.css
These particular changes targeted the calendar UI. The thickness of text was increased as well as colors of inactive days to improve contrast to acceptable levels (4.5:1 minimum).
Additionally, changed the hover bg for days during the month.
> STCOM - 1390 improve text contrast of disabled text, adjust calendar colors

- CHANGELOG.md
- lib/MessageBanner/MessageBanner.js
- lib/MessageBanner/MessageBanner.module.css
- lib/MessageBanner/readme.md
- lib/MessageBanner/tests/MessageBanner-test.js
Introduce the marginTop0 class to the MessageBanner component to remove the default top margin.
https://folio-org.atlassian.net/browse/STCOM-1408
> STCOM-1408: Add marginTop0 class to MessageBanner component

- CHANGELOG.md
- lib/Popper/Popper.css
Popper already adds an attribute (via its default set of modifiers) - the hiding outcome just has to be connected via CSS. If the anchoring element control is visible within the view, then the popper/overlay will be visible as well. If not, it disappears.
> STCOM-139 - Popper - hide popper overlay when target element is scrolled outside of the view.

- CHANGELOG.md
- lib/AuditLog/AuditLogCard.js
- lib/AuditLog/AuditLogModal.js
- lib/AuditLog/AuditLogPane.js
- lib/AuditLog/readme.md
- lib/AuditLog/tests/AuditLogPane-test.js
1. Card fields should be displayed grouped if the action and tag match. The "Field" prefix should only be on the card, not the modal.
2. Increase the size of the card modal.
3. The history pane header should display the total number of versions.
1. Use `modalFieldChanges` to display fields in the modal if they should be different from card fields.
2. `size="large"`
3. Use`totalVersions` for `AuditLogPane`.
[STCOM-1419](https://folio-org.atlassian.net/browse/STCOM-1419)
https://github.com/user-attachments/assets/8486c35c-7a54-461e-9b34-22faf92f4281
> STCOM-1419: `AuditLog` - add `modalFieldChanges` to display field change in card modal window, make modal large, add `totalVersions`.

- CHANGELOG.md
- util/dateTimeUtils.js
`moment.contains` included start and end dates by default, so 01/01/2025 would be considered included in 01/01/2025-12/31/2025 range
`dayjs` needs some additional configuration to replicate this behaviour
https://day.js.org/docs/en/plugin/is-between
[STCOM-1421](https://folio-org.atlassian.net/browse/STCOM-1421)
> STCOM-1421 Make `dayjs.contains` include start end end dates

- CHANGELOG.md
- lib/AuditLog/AuditLogPane.js
- lib/AuditLog/readme.md
- lib/AuditLog/tests/AuditLogPane-test.js
When `versions` data is initially loading - display `Loading` component in `AuditLogPane` component, otherwise display `Loading` as a label of `Load more` button when it it clicked.
> STCOM-1422: Add loading indicator to `AuditLogPane` when data is initially loading

- CHANGELOG.md
- lib/AuditLog/AuditLogModal.js
- lib/AuditLog/changedFieldsFormatter.js
- lib/AuditLog/tests/AuditLogModal-test.js
[STCOM-1427](https://folio-org.atlassian.net/browse/STCOM-1427)
* Currently `changedFieldsFormatter` displays all `false` values as `-`
* If we set the checkbox then we should display `Changed from - '-'` and `Changed to - 'true'`
* If we set the checkbox for the second time then we should display `Changed from - 'true'` and `Changed to - 'false'`
> STCOM-1427: Display `Changed from - '-'` and `Changed to - 'false'` values for boolean fields in `AuditLogModal`

- CHANGELOG.md
- lib/AdvancedSearch/AdvancedSearch.js
- lib/AdvancedSearch/components/AdvancedSearchModal/AdvancedSearchModal.js
- lib/AdvancedSearch/hooks/tests/useAdvancedSearch-test.js
- lib/AdvancedSearch/hooks/useAdvancedSearch/useAdvancedSearch.js
- lib/AdvancedSearch/tests/AdvancedSearch-test.js
- translations/stripes-components/en.json
Add the ability to reset Advanced search input from modal
Expose the `isPristine` property that compares the initial state of rows with the current one and use it to enable the `Reset all` button. Use the existing `resetRows` function to reset all states.
[STCOM-1424](https://folio-org.atlassian.net/browse/STCOM-1424)
https://github.com/user-attachments/assets/04f0d79d-126c-4dba-9bfb-c6f487299ca9
> STCOM-1424: `AdvancedSearch` - replace `Cancel` button with `Reset all` in modal window.

- CHANGELOG.md
- lib/AutoSuggest/AutoSuggest.css
- lib/AutoSuggest/AutoSuggest.js
purpose: https://folio-org.atlassian.net/browse/STCOM-1426
description: `useCombobox` doesn't support onSelect option (that was supported by previous AutoSuggest implementation), instead they have `onSelectedItemChange` https://github.com/downshift-js/downshift/blob/master/src/hooks/useCombobox/README.md#onselecteditemchange
The downshift upgrade for AutoSuggest switched from a component implementation to the `useCombobox` hook from `downshift` - The API change - as mentioned is covered in this change and kept the `onSelect` API intact. Additionally, I was unable to click on the option in the dropdown with the mouse - this is due to the way our `div#OverlayContainer` is setup when the dropdown is rendered it via React portal. Any element rendered directly there needs `pointer-events: all` …
> STCOM-1426 Restore onSelect support for AutoSuggest component

- CHANGELOG.md
- lib/AuditLog/AuditLogCard.js
- lib/AuditLog/AuditLogPane.js
- lib/AuditLog/readme.md
- lib/AuditLog/tests/AuditLogPane-test.js
- translations/stripes-components/en.json
Display "Shared" instead of "Original version" for the original card when the record was shared from a local one.
Add the `showSharedLabel` property.
[STCOM-1430](https://folio-org.atlassian.net/browse/STCOM-1430)
> STCOM-1430: `AuditLog` - add `showSharedLabel` property to display `Shared` instead of `Original version` in the original card.

- CHANGELOG.md
- util/dateTimeUtils.js
[`dayjs` requires loading the `LocalizedFormat` plugin](https://day.js.org/docs/en/display/format#localized-formats) in order to use localized formats such as `L`, which [we use in
`getDayJSLocalizedFormat()`](https://github.com/folio-org/stripes-components/blob/71463007efee7f89dabbae2f3cb1951a00ab9812/util/dateTimeUtils.js#L145).
Refs [STCOM-1437](https://folio-org.atlassian.net/browse/STCOM-1437)
> STCOM-1437 load dayjs' LocalizedFormat plugin

- lib/AdvancedSearch/components/AdvancedSearchModal/AdvancedSearchModal.js
- lib/AdvancedSearch/components/AdvancedSearchRow/AdvancedSearchRow.js
- lib/AdvancedSearch/hooks/useAdvancedSearch/useAdvancedSearch.js
- lib/AdvancedSearch/tests/AdvancedSearch-test.js
1. The `Reset all` and `Search` buttons should be disabled with no values/selections in the advanced search modal.
2. A clear icon should be added for text fields.
[STCOM-1424](https://folio-org.atlassian.net/browse/STCOM-1424)
https://github.com/user-attachments/assets/0de86b8f-8736-4bfb-b153-6cf08f86ace1
> STCOM-1424: Use empty rows state for `isPristine` and for resetting rows state; add clear icon for inputs; disable search button (follow-up PR).

- CHANGELOG.md
- lib/NavListSection/NavListSection.css
- lib/Pane/Pane.css
This PR makes the vertical borders of `<Panes>` match the horizontal borders.
Before:
After:
> STCOM-1423 Unify pane border colors.

- CHANGELOG.md
- util/languages.js
- util/tests/languages-test.js
1. Return "undetermined" from `formattedLanguageName()` given an empty code. Previously, empty codes matched the first value in the languages table that lacked a two-character code. Whoops!
2. Correctly sort entries according to current locale in `languageOptions()`. The previous implementation used `lodash.sortBy`, an implementation that does not correctly handle localized data.
Refs [STCOM-1451](https://folio-org.atlassian.net/browse/STCOM-1451)
> STCOM-1451 correctly handle empty codes in formattedLanguageName

- index.js
In https://github.com/folio-org/stripes-components/pull/2495 some exports have changed - `<ConfirmationModal>` used to be a default export, but became named
But the root index.js still referenced it as a default export, which caused build issues
[STCOM-1460](https://folio-org.atlassian.net/browse/STCOM-1460)
> STCOM-1460 fix export of confirmation modal

- lib/ConfirmationModal/SessionConfirmationModal.js
- lib/ConfirmationModal/stories/ConfirmationModalExample.js
- package.json
- yarn.lock
If we're lucky, updates #2495; replaces #2497
`rehooks-ts` blows up in CI in other repos when their tests that leverage stripes-components claim not to be able to find `rehooks-ts`. Maybe this is a jest hiccup tripped by the fact that `rehooks-ts` claims to export `dist/index.cjs`, a file that does not exist. So that's ... odd.
`usehooks-ts` appears to offer a hook that offers the same API. So that's ... convenient!
~@JohnC-80, I was hoping for a silver bullet here but, alas, didn't find one. With stripes-components pinned to this branch in other repos, I still see test failures, but not so many and none that relate to being unable to find the import. I don't know if that's better or worse :/~
Refs STCOM-1460
> STCOM-1460 s/rehooks-ts/usehooks-ts/g

- CHANGELOG.md
- lib/ErrorBoundary/ErrorBoundary.js
- lib/ErrorBoundary/components/ProductionError/ProductionError.js
- lib/ErrorBoundary/tests/ErrorBoundary-test.js
- package.json
- yarn.lock
If a sourcemap can be loaded and parsed, show the mapped stacktrace instead of the original (pretty much useless) stacktrace. 
* March 2021: We merged #1512 even though the reporting wasn't great 😑 
* ... ~200 "Something went wrong" tickets are filed 😱 
* October 2024: Ugh, STCOM-1355, we should purge the useless reporting 😢 
* ... ~70 more "Something went wrong" tickets are filed 🙀 
* September 2025, [WOLFCon's "How do we figure out what the problem is?"](https://wolfcon2025.sched.com/event/25ldl/how-do-we-figure-out-what-the-problem-is) reminds me how annoying it is that we couldn't do better, which led to more searching, which led to https://github.com/novocaine/sourcemapped-stacktrace, which has been around since 2018 so I don't know why we didn't find it earlier, but we didn't, and …
> STCOM-814 Leverage sourcemaps in ErrorBoundary
