package.json
Do we need this dep in stripes-component?
=> Add react-flexbox-grid dependency for AddressList

lib/Button/Button.js, lib/Button/index.js, lib/Checkbox/Checkbox.js, lib/Checkbox/index.js, lib/DropdownMenu/DropdownMenu.js, lib/FilterPane/FilterPane.js, lib/FocusLink/FocusLink.js, lib/HotKeys/HotKeys.js, lib/Icon/Icon.js, lib/IfInterface/IfInterface.js, lib/IfPermission/IfPermission.js, lib/Layer/Layer.js, lib/Layout/Layout.js, lib/List/List.js, lib/MultiColumnList/Autosizer.js, lib/MultiColumnList/MCLRenderer.js, lib/MultiColumnList/MultiColumnList.js, lib/MultiColumnList/defaultRowFormatter.js, lib/NavList/NavList.js, lib/NavListSection/NavListSection.js, lib/Pluggable/Pluggable.js, lib/RadioButton/RadioButton.js, lib/RadioButtonGroup/RadioButtonGroup.js, lib/RadioButtonGroup/index.js, lib/TextArea/TextArea.js, lib/TextField/TextField.js
Clean up semicolons to appease ESLint. Offered un-squashed just in case a change causes a glitch that we need to revert.
=> Strpcomp 21 semicolon

lib/Button/Button.js, lib/Checkbox/Checkbox.js, lib/FilterPane/FilterPane.js, lib/FocusLink/FocusLink.js, lib/HotKeys/FocusTrap.js, lib/HotKeys/FocusTrap.old.js, lib/HotKeys/HotKeyMapMixin.js, lib/HotKeys/HotKeys.js, lib/Icon/Icon.js, lib/Layer/Layer.js, lib/MultiColumnList/Autosizer.js, lib/MultiColumnList/MCLRenderer.js, lib/MultiColumnList/defaultRowFormatter.js, lib/NavListSection/NavListSection.js, lib/RadioButton/RadioButton.js, lib/RadioButtonGroup/RadioButtonGroup.js, lib/TextField/TextField.js
Clean up commas to appease ESLint. Offered un-squashed just in case a change causes a glitch that we need to revert.
=> Strpcomp 21 comma

lib/Button/Button.js, lib/Checkbox/Checkbox.js, lib/FilterPaneSearch/FilterPaneSearch.js, lib/FocusLink/FocusLink.js, lib/Icon/Icon.js, lib/Layout/Layout.js, lib/List/List.js, lib/MultiColumnList/MCLRenderer.js, lib/TextField/TextField.js
Clean up quotes to appease ESLint. Offered un-squashed just in case a change causes a glitch that we need to revert.
=> Strpcomp 21 quotes

lib/Checkbox/Checkbox.js, lib/FilterGroups/FilterGroups.js, lib/FocusLink/FocusLink.js, lib/HotKeys/HotKeys.js, lib/Layer/Layer.js, lib/MultiColumnList/Autosizer.js, lib/MultiColumnList/MCLRenderer.js, lib/Pluggable/Pluggable.js, lib/TextArea/TextArea.js
Clean up imports to appease ESLint.
=> import cleanup. see STRPCOMP-21

CHANGELOG.md, lib/Checkbox/Checkbox.js, lib/FilterControlGroup/FilterControlGroup.js, lib/FilterPaneSearch/FilterPaneSearch.js, lib/IfInterface/IfInterface.js, lib/IfPermission/IfPermission.js, lib/Layer/Layer.js, lib/MultiColumnList/MCLRenderer.js, lib/NavListSection/NavListSection.js, lib/RadioButtonGroup/RadioButtonGroup.js
Clean up ESLint complaints about how arrow functions are used. See STCOM-21.
=> Stcom 21 arrow functions

lib/MultiColumnList/MCLRenderer.js, lib/MultiColumnList/defaultRowFormatter.js
Second attempt at mitigating the lint errors in MultiColumnList, this
time without completely sucking, breaking the layout, throwing console
errors all over the place etc etc etc.
=> Lint: MultiColumnList. See STCOM-21

CHANGELOG.md, lib/Settings/Settings.js
This PR takes care of UIU-182 and UIIT-57
=> Fix selected item in Settings. Fixes STCOM-37

lib/MultiColumnList/MCLRenderer.js
There is no need to issue a warning when displaying a React component as
it will be properly rendered.
=> do not warn on component display. Fixes STCOM-36

.eslintrc, CHANGELOG.md, lib/Checkbox/Checkbox.js, lib/Datepicker/Datepicker.js, lib/FilterGroups/FilterGroups.js, lib/FilterPaneSearch/FilterPaneSearch.js, lib/FocusLink/FocusLink.js, lib/HotKeys/index.js, lib/Icon/Icon.js, lib/Modal/Modal.js, lib/MultiColumnList/MCLRenderer.js, lib/MultiColumnList/defaultRowFormatter.js, lib/NavList/NavList.js, lib/RadioButton/RadioButton.js, lib/RadioButtonGroup/RadioButtonGroup.js, lib/Settings/Settings.js, lib/structures/AddressFieldGroup/AddressEdit/AddressEdit.js, lib/structures/AddressFieldGroup/AddressEdit/AddressEditList.js, lib/structures/AddressFieldGroup/AddressList/AddressList.js, lib/structures/AddressFieldGroup/AddressView/AddressView.js, lib/structures/EditableList/EditableListForm.js, package.json
Lots of linting, including updates to some of the config/rules packages to pull in some bug fixes. With the exception of two accessibility warnings we're still discussing and the `<Notes>` structure that is still just a stub, this is the end my beautiful friend. This is the end my only friend, the end of our elaborate plans, the end.
=> Stcom 21 still linting after all these years

Jenkinsfile
configuration file, Jenkinsfile
=> migrate to Jenkins Pipelines

.babelrc, babel-test-hook.js, package.json
Remove babel transform runtime dependency and babelrc file and add the babel hook for tests.
=> add babel hook

CHANGELOG.md, index.js, lib/Badge/Badge.css, lib/Badge/Badge.js, lib/Badge/index.js
@JohnC-80 I moved this out of `ui-users`. This is very basic for now.
=> Add Badge component. Fixes STCOM-90.

CHANGELOG.md, lib/Button/Button.css, lib/Checkbox/Checkbox.css, lib/Dropdown/Dropdown.js, lib/DropdownMenu/DropdownMenu.css, lib/DropdownMenu/DropdownMenu.js, lib/MenuItem/MenuItem.js, lib/Pane/Pane.js, lib/Pane/readme.md, test/Dropdown/Dropdown-test.js, test/eventHelpers.js
Fix issues with Dropdown component and associated components (<MenuItem>, <DropdownMenu>) and add appropriate classes to Button (dropdownActive, dropdownItem).
Additionally, add props to <Pane> component to set overflow and padding of the Pane's content `<div>`.
=> STCOM-40, STCOM-68 enabler

CHANGELOG.md, lib/EntrySelector/EntrySelector.js, lib/EntrySelector/index.js
Copied from ui-circulation so it can also be used in other modules.
Fixes STCOM-92.
=> Add <EntrySelector>

CHANGELOG.md, lib/EntrySelector/EntrySelector.js
This PR refactors `EntrySelector` to support UICIRC-15 and UIU-276.
=> Refactor EntrySelector. Fixes STCOM-97

CHANGELOG.md, README.md, lib/Callout/readme.md, lib/MenuItem/readme.md, lib/RadioButtonGroup/readme.md, lib/SegmentedControl/readme.md, lib/Settings/readme.md, lib/structures/ConfirmationModal/readme.md
=> FOLIO-398 doc tweaks 1

CHANGELOG.md, lib/EntrySelector/EntrySelector.js
Hey I just clicked you
And this is crazy
But here's a callback
So call it maybe
=> Add onClick callback to EntrySelector. Refs UICIRC-20

CHANGELOG.md, lib/Datepicker/Datepicker.js
Fixes issue with datepicker miss-handling dates for non-US locales.
=> Stcom 110 datepicker non us

CHANGELOG.md, lib/Datepicker/Calendar.js
Calendar-rendering fix. Fixes STCOM-115 and it's clones.
=> Stcom 115 datepicker non us

lib/Modal/Modal.stories.js, lib/TextField/TextField.stories.js
Sets up Storybook stories for variants of `Modal` and `TextField`.
=> Create Storybook stories for Modal and TextField

lib/Accordion/Accordion.stories.js
The purpose of writing these stories is to provide a visual example for components' props.  With the storybook, you can see the way individual prop work by itself.
To create my stories, I followed the README.md to determine most of the desired functionality and provide results accordingly. You can view these stories in the storybook after running `yarn storybook`.
Writing stories: https://storybook.js.org/basics/writing-stories/
Accordion README.md: https://github.com/folio-org/stripes-components/blob/master/lib/Accordion/readme.md
=> Create stories for the Accordion component

lib/KeyValue/KeyValue.css, lib/KeyValue/readme.md, lib/KeyValue/stories/BasicUsage.js, lib/KeyValue/stories/KeyValue.stories.js
Added a story and some slightly different styling to the KeyValue component. Will probably be updated later on.
=> Styling and story added to KeyValue

lib/Checkbox/Checkbox.stories.js, lib/Pane/Pane.js, lib/Pane/readme.md, lib/PaneSubheader/PaneSubheader.css, lib/PaneSubheader/PaneSubheader.js, lib/PaneSubheader/index.js, lib/PaneSubheader/readme.md, lib/structures/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js
Upcoming features present a need for static content to be displayed just below a Pane's header, but outside of the actual flow of the Pane's content.
=> Stcom 140 pane subheader

lib/MultiColumnList/MCLRenderer.css
https://issues.folio.org/browse/UIU-345
=> Minor padding change that fixes UIU-345

lib/Checkbox/Checkbox.css, lib/Checkbox/Checkbox.js, lib/RadioButton/RadioButton.css, lib/RadioButton/RadioButton.js
On the request of Filip I have updated the checkboxes and radio buttons styling (made them smaller)
=> Fix checkbox radio button sizes

lib/Button/stories/Button.stories.js, lib/Checkbox/Checkbox.stories.js, lib/Dropdown/Dropdown.stories.js, lib/Dropdown/stories/index.js, lib/Dropdown/stories/toggleable.js, lib/FilterGroups/FilterGroups.stories.js, lib/Icon/stories/Icon.stories.js, lib/MultiColumnList/MultiColumnList.stories.js, lib/RadioButton/RadioButton.stories.js
Created storybook stories for the Dropdown component to demonstrate the component itself. 
The purpose of writing these stories is to provide a visual example for components' props. 
This will show the dropdown as it appears when opened, closed, and how it looks when toggled.
To create the stories I went along with desired functionality as outlined in the readme.
Open display:
Closed display:
Toggle:
=> Create Dropdown Story

lib/Accordion/Accordion.js, lib/MetaSection/MetaAccordionHeader.js, lib/MetaSection/MetaSection.css, lib/MetaSection/MetaSection.js, lib/MetaSection/index.js, lib/MetaSection/readme.md
Metasection component - this component will be the temporary home for "last-updated" information on a record's detail view.
=> STCOM-145 Add MetaSection component

README.md
Use a table to list all components.
Link to each one’s doc if available.
Start to categorise.
=> STCOM-170 Use table to list all components

lib/structures/EditableList/EditableList.css, lib/structures/EditableList/EditableListForm.js
I added a bit of CSS and a Headline to shine the EditableList up a bit.
**Before:**
**After:**
=> Updated EditableList

lib/NavList/readme.md, lib/NavList/stories/BasicUsage.js, lib/NavList/stories/NavList.stories.js, lib/NavListSection/NavListSection.css, lib/NavListSection/NavListSection.js
Updated stylng and added a story for NavList.
=> Navlist styling and story

lib/Datepicker/Calendar.js
Something must have removed this change somewhere so I re-added it.
=> [Fix] Update Calendar icons

README.md, lib/NavList/readme.md
Minor text edits.
Link to new lib docs.
=> FOLIO-398 doc tweaks 3

README.md, lib/structures/RepeatableField/readme.md
Link to new lib docs.
Whitespace fixes.
=> FOLIO-398 doc tweaks 4

CHANGELOG.md, lib/FilterPaneSearch/FilterPaneSearch.js, lib/Select/Select.js
=> `<FilterPaneSearch>` supports `searchableFields` and `onChangeField` properties

util/makeQueryFunction.js
=> Field-specific search is right-truncated

README.md, lib/Select/readme.md
Link to new lib docs.
Whitespace fixes.
=> FOLIO-398 doc tweaks 6

CHANGELOG.md, lib/FilterControlGroup/FilterControlGroup.js, lib/FilterGroups/FilterGroups.js
=> `<FilterGroups>` implements the new `disableNames` property

CHANGELOG.md, lib/FilterPaneSearch/FilterPaneSearch.css, lib/FilterPaneSearch/FilterPaneSearch.js
facilitates JIRA UISE-2 with appropriate styling for components.
=> STCOM-177 search select styles

lib/Accordion/headers/FilterAccordionHeader.js, lib/Checkbox/Checkbox.css, lib/Checkbox/Checkbox.js, lib/FilterControlGroup/FilterControlGroup.css, lib/FilterControlGroup/FilterControlGroup.js, lib/FilterGroups/FilterGroups.js
Functionally disable the filter checkboxes in a disabled filter group.
=> STCOM-175 actually disable filters

lib/Button/Button.css, lib/List/readme.md, lib/sharedStyles/form.css
- Updated border radius to 4px instead of 6px on form elements
- Updated background and border colors on form elements
- Added semi-bold text to primary buttons
- Fixed a small spelling error in the List-component
=> Quick fix form styling updates

CHANGELOG.md, lib/TextField/TextField.js, lib/structures/RepeatableField/FieldRow.js, lib/structures/RepeatableField/RepeatableField.css, lib/structures/RepeatableField/RepeatableField.js, lib/structures/RepeatableField/readme.md
Updating this new component for integration with ui-inventory.
=> Stcom 143 repeatable field update

lib/global.css, lib/variables.css
Adds two new variables, based on the naming from https://codepen.io/filipjakobsen/pen/46d486a57a085f7319f42fee524119de.
With only a single theme for FOLIO at the moment, visited links will now be #4f2bbb (analogous to the primary link color, #2b75bb).
=> Create visited link color

lib/KeyValue/KeyValue.js
For to pass other things with.
=> KeyValue label prop accepts node

lib/Accordion/Accordion.js
Fix issue with accordion not checking/updating its content height before expansion.
=> STCOM-186 Accordion updates height on expansion

CHANGELOG.md, lib/FilterGroups/FilterGroups.js
=> The `handleFilterChange` and `handleFilterClear` functions return the modified filter state

CHANGELOG.md, lib/structures/EditableList/ItemView.js
Fixes [STCOM-189](https://issues.folio.org/browse/STCOM-189).
=> invert test in delete-suppression function. Fixes STCOM-189

lib/MetaSection/MetaAccordionHeader.js, lib/MetaSection/MetaSection.js
Updated MetaSection accordingly to what was discussed in: 
https://vimeo.com/249838257#t=45m55s
=> Removed strong text and reversed chevron

lib/Icon/Icon.js, lib/Select/Select.js, lib/Select/readme.md, lib/Select/stories/BasicUsage.js, lib/TextField/TextField.js, lib/TextField/TextFieldIcon.js, lib/TextField/index.js, lib/structures/SearchField/SearchField.css, lib/structures/SearchField/SearchField.js, lib/structures/SearchField/index.js, lib/structures/SearchField/readme.md, lib/structures/stories/SearchFieldUsage.js, lib/structures/stories/Structures.stories.js
The SearchField component is an universal component that will be used in different places across the application to prevent duplicate code. It's simple for now but can be updated later on with more functionality if needed.
**Changes:**
- Added SearchField component and story under "structures"
- Updated Icon component with id prop. Made it a stateless component.
- Added new props to TextField (ariaLabel) and TextFieldIcon (id)
=> Added SearchField-component

lib/Accordion/Accordion.css, lib/Accordion/headers/DefaultAccordionHeader.js, lib/Accordion/headers/FilterAccordionHeader.js, lib/Checkbox/Checkbox.js, lib/Checkbox/Checkbox.stories.js, lib/Headline/Headline.css, lib/Icon/Icon.js, lib/IconButton/IconButton.css, lib/IconButton/IconButton.js, lib/IconButton/readme.md, lib/IconButton/stories/BasicUsage.js, lib/MetaSection/MetaAccordionHeader.js, lib/MultiColumnList/MCLRenderer.css, lib/Select/Select.js, lib/TextArea/TextArea.js, lib/TextField/TextField.js, lib/TextField/TextFieldIcon.js, lib/sharedStyles/form.css, lib/structures/SearchField/SearchField.js, lib/structures/SearchField/readme.md, lib/structures/stories/SearchFieldUsage.js
=> Feedback changes misc 26 01 18

lib/Checkbox/Checkbox.css, lib/Checkbox/Checkbox.js, lib/Checkbox/Checkbox.stories.js
https://issues.folio.org/browse/STCOM-195
=> Fixed undefined checked property. Updated example. Minor style update.

lib/Headline/Headline.js, lib/Headline/readme.md, lib/Headline/stories/BasicUsage.js
Fixed wrong path in readme, added so that the rest of props added is spread and minor example change.
=> <Headline> changes

CHANGELOG.md, lib/Button/Button.js
=> Omit "hollow" prop from those passed to `<button>`

README.md
Fix text typos.
Did high-level review of “categories” #218 for STCOM-170
=> FOLIO-398 doc tweaks 9

README.md
@JohnC-80, I've read the updated top-level README. It's a big improvement and very useful. I've suggested a bunch of further tweaks, which you will find in this PR. Hope they're useful.
One other change I would make would be to pull out the `structures` components into their own table. As things are now, they are an odd violation of the otherwise consistent ordering.
=> Doc updates for JohnC to review

lib/MultiColumnList/MCLRenderer.js
gives access to a "backToTop()" method.
=> STCOM-201 add instanceRef prop to MCL

CHANGELOG.md, lib/structures/EditableList/EditableListForm.js
Fixes [STCOM-203](https://issues.folio.org/browse/STCOM-203).
=> Adjust EditableListForm setup. Fixes STCOM-203.

CHANGELOG.md, lib/FilterGroups/readme.md
=> Update `<FilterGroups>` documentation for recent API changes

lib/structures/SearchField/SearchField.js
Needed for ui-search testing, UISE-61.
=> Set id for query-index selector

lib/Datepicker/Datepicker.js
[STCOM-210](https://issues.folio.org/browse/STCOM-210)
=> Remove unused refs from Datepicker buttons. Fixes STCOM-210.

lib/Accordion/readme.md, lib/FilterGroups/readme.md
=> FOLIO-398 doc tweaks 11

CHANGELOG.md, util/README.md
=> Proper documentation for makeQueryFunction

lib/AppIcon/AppIcon.css, lib/Pane/Pane.js, lib/Pane/readme.md, lib/PaneHeader/PaneHeader.css, lib/PaneHeader/PaneHeader.js
This PR adds the option to show an AppIcon in the PaneHeader.
**Result:**
=> Adding AppIcon-feature to PaneHeader

lib/structures/SearchField/SearchField.js
-> searchableIndexes Select field.
=> Removed default placeholder from SearchField 

lib/Selection/Selection.js, lib/Selection/SingleSelect.js
=> <Selection> - apply name attribute to control

CHANGELOG.md, lib/structures/AddressFieldGroup/AddressList/AddressList.js
[https://issues.folio.org/browse/STCOM-230](https://issues.folio.org/browse/STCOM-230)
=> Fix multiple addresses displaying side by side. Fixes STCOM-230.

lib/Timepicker/TimeDropdown.js, lib/Timepicker/Timepicker.js
- support 'now' value.
- id's for testing.
- dropdown properly uses locale format to display time.
=> Timepicker integration fix

lib/Selection/SingleSelect.js
- Substring matching of options when control focused /list closed
- arrow keys open list/focus filter field - subsequent presses move cursor.
- filter list clears and list resets when list is closed/blurred.
=> STCOM-231 <Selection> behavior update

lib/Icon/Icon.css, lib/Icon/Icon.js, lib/IconButton/IconButton.css, lib/PaneHeader/PaneHeader.css, lib/sharedStyles/form.css, lib/structures/EditableList/EditableListForm.js
Minor tweaks here and there.
See commits for information.
=> Minor changes 03-27-18

lib/MetaSection/MetaSection.js, lib/Timepicker/Timepicker.js
- Timepicker now returns time UTC time considering the tenanst timezone
- MeatSection displays info based on the timezone of the tenant
=> Refine stripes components to handle timezone refs UIORG-55

CHANGELOG.md, lib/Selection/SingleSelect.js, lib/Selection/readme.md
https://issues.folio.org/browse/STCOM-251
=> Add ability to pass custom filter to Selection component. Fixes STCOM-251.

CHANGELOG.md, lib/structures/ConfirmationModal/ConfirmationModal.js
https://issues.folio.org/browse/STCOM-255
=> Fix ConfirmationModal scope. Fixes STCOM-255.

CHANGELOG.md, README.md, lib/ErrorBoundary/ErrorBoundary.js, lib/ErrorBoundary/index.js, package.json
Made this a more generic component and moved it into stripes-components. You can use it to wrap any component to display a fallback UI. [More info on the React site.](https://reactjs.org/docs/error-boundaries.html)
=> Added ErrorBoundary component

lib/Selection/SelectList.js
https://issues.folio.org/browse/STSMACOM-82
=> Fix label. Refs STSMACOM-82

CHANGELOG.md, lib/Settings/Settings.js, package.json
Refs [UIORG-75](https://issues.folio.org/browse/UIORG-75)
=> settings page sections. Refs UIORG-75

CHANGELOG.md, lib/EntrySelector/EntrySelector.js
https://issues.folio.org/browse/STCOM-262
=> Pass parent's resources to EntrySelector. Fixes STCOM-262

lib/PaneHeader/PaneHeader.css, lib/PaneHeader/PaneHeader.js
Added universal interaction styles and flipped the caret icon.
=> Pane Header Menu updates

lib/Paneset/Paneset.css
Add overflow:hidden to paneset css.
=> STCOM-264 double scrollbars on edit views.

lib/Accordion/Accordion.js, lib/Accordion/headers/DefaultAccordionHeader.js, lib/Accordion/tests/Accordion-test.js, lib/Datepicker/Calendar.js, lib/Datepicker/Datepicker.js, lib/Modal/Modal.js, lib/PaneHeader/PaneHeader.js, lib/Selection/SelectList.js, lib/Timepicker/Timepicker.js, translations/en.json
https://issues.folio.org/browse/STCOM-253
Follow up to #365, #368
=> STCOM-253 additional translations

lib/IconButton/IconButton.css
Added pointer-events:none; to IconButton inner element to prevent it from trying to capture focus
=> Minor interaction styles fix

lib/Accordion/AccordionSet.js, lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js, lib/Datepicker/Calendar.js, lib/Datepicker/Datepicker.js, lib/TextField/TextField.js, package.json
Code changes reflect new styles from the `react/sort-comp` rule. 
With https://github.com/folio-org/eslint-config-stripes/pull/30, future rule changes should be less surprising.
=> Update to eslint-config-stripes 2.0.0

lib/MultiColumnList/MCLRenderer.js
https://issues.folio.org/browse/STCOM-288
=> STCOM-288 MCL: Fixed error when rendering sparsely populated datasets

package.json
New release: https://github.com/folio-org/stripes-cli/blob/master/CHANGELOG.md#120-2018-06-07
=> Use stripes-cli 1.2.0

.storybook/addons.js, .storybook/config.js, package.json
Adds a toggle to the storybook tools to easily switch between LTR and RTL.
=> Install storybook RTL addon

CHANGELOG.md, README.md, lib/Accordion/readme.md
* Fixed a few text typos.
* Verified the table against the lib directory using sed and stuff.
=> FOLIO-398 doc tweaks 18

lib/Datepicker/stories/BasicUsage.js, lib/Datepicker/stories/Datepicker.stories.js, lib/Timepicker/stories/BasicUsage.js, lib/Timepicker/stories/Timepicker.stories.js
Will make debugging and styling much faster.
=> Create Datepicker and Timepicker stories

.eslintrc, lib/Pluggable/Pluggable.js, package.json
Reverts folio-org/stripes-components#451
=> Revert "Pluggable: use new ModulesContext"

lib/Pane/tests/Pane-test.js, lib/Pane/tests/interactor.js
Renders a `Pane` inside a `Paneset`.
=> Implement basic Pane rendering test

README.md
I was a little too quick to merge #448 and the README link was in error
=> Fix README testing link

lib/InjectIntl/readme.md
Content added to address discussion from https://github.com/folio-org/stripes-components/pull/441.
=> Clarify injectIntl() docs

.storybook/webpack.config.js
=> Turn on CSS source maps in Storybook

lib/Modal/Modal.js, lib/Modal/tests/Modal-test.js, lib/Modal/tests/interactor.js
I added some tests for the Modal. I think the coverage is pretty good but let me know if you guys have ideas for more tests for the Modal.
Here's the output of the tests:
=> Added test coverage for Modal

lib/Pane/Pane.js
PR to mitigate this error:
```
Cannot read property 'removePane' of undefined
```
https://issues.folio.org/browse/FOLIO-1339
=> check for paneset before calling its method

lib/Pane/Pane.js
Reverts folio-org/stripes-components#488
=> Revert "check for paneset before calling its method"

lib/IconButton/stories/BasicUsage.js, lib/IconButton/stories/IconButton.stories.js
Made this change to test the "disabled" state so I figured I'd push it back up in case it's of use in the future to others. 😄
=> IconButton: Added 'disabled' knob to story

lib/MultiColumnList/MCLRenderer.js, lib/Paneset/Paneset.js, lib/Popover/Popover.js, lib/RepeatableField/FieldRow.js
These popped up in SonarCloud "Reliability" reports: https://sonarcloud.io/component_measures?id=folio-org%3Astripes-components&metric=reliability_rating
=> Fix unused parameter issues

lib/Button/stories/Button.stories.js, lib/Modal/Modal.css, lib/Modal/Modal.js
I added a very subtle open/close transition to the Modal-component.
Check out the transition here: http://ux.folio.org/storybook-draft/?selectedKind=Modal
=> Added open/close transition to Modal

util/makeQueryFunction.js
(I think this must be the intent od the commit that introduced the
STCOM-321 regression.)
=> Remove unnecessary backslash-quote, for ESLint

lib/List/List.js, lib/List/tests/interactor.js, lib/List/tests/list-test.js
Adding test coverage for the `<List>` component. 100% :raised_hands:
=> List tests

lib/ModalFooter/tests/ModalFooter-test.js, lib/SegmentedControl/tests/SegmentedControl-test.js, lib/SegmentedControl/tests/interactor.js, package.json, yarn.lock
Chai 4 is stricter about a couple syntactical things.
=> Upgrade chai to 4.x

package.json, yarn.lock
Should get some (probably tiny for this repo) performance enhancements.
=> Upgrade mocha to 5.x

util/makeQueryFunction.js
Tied to https://github.com/folio-org/stripes-smart-components/pull/244
=> STCOM-332 Introduce deprecation warnings for makeQueryFunction move

lib/Pluggable/Pluggable.js
Tied to https://github.com/folio-org/stripes-core/pull/403
=> STCOM-331 Introduce deprecation warnings for Pluggable move

lib/Settings/Settings.js
Tied to https://github.com/folio-org/stripes-smart-components/pull/243
=> STCOM-330 Introduce deprecation warnings for Settings move

lib/AddressFieldGroup/AddressEdit/AddressEditList.js, lib/AddressFieldGroup/AddressEdit/EmbeddedAddressForm.js, lib/AddressFieldGroup/AddressList/AddressList.js
Warnings for https://github.com/folio-org/stripes-smart-components/pull/240
=> STCOM-327 Introduce deprecation warnings for AddressFieldGroup move

lib/EditableList/EditableListForm.js
Tied to https://github.com/folio-org/stripes-smart-components/pull/242
=> STCOM-328 Introduce deprecation warnings for EditableList move

.circleci/config.yml, karma.conf.js, lib/Datepicker/tests/Datepicker-ReduxForm-test.js, lib/MultiSelection/tests/interactor.js, lib/Selection/tests/interactor.js, package.json, yarn.lock
Updates lock file to bring in changes from https://github.com/folio-org/stripes-cli/pull/109 and https://github.com/folio-org/stripes-cli/pull/110.
=> Upgrade stripes-cli

lib/MultiSelection/MultiDownshift.js, lib/MultiSelection/MultiSelection.js, lib/MultiSelection/SelectedValuesList.js, lib/MultiSelection/tests/MultiSelection-test.js, lib/MultiSelection/tests/MultiSelectionHarness.js
Fixed issues with updating values. Values are now stored in external state. We can add an "uncontrolled" wrapper if the case warrants.
Code for actions is now in-line with documentation. (`filterText` vs `filterValue`);
API remains the same (and now performs closer to expectations)
=> MultiSelection bugfix

package.json, yarn.lock
Don't use any snapshot tags from the `npm-folioci` registry.
=> Only use npm-folio registry in lockfile

lib/FilterGroups/FilterGroups.css, lib/FilterGroups/FilterGroups.js
Applied CSS class to overwrite existing interaction styles on checkbox in Filter Group checkbox
=> Minor style change for Filter Group checkbox

.storybook/config.js, .storybook/webpack.config.js, package.json, yarn.lock
Fixes https://issues.folio.org/browse/STCOM-346
=> STCOM-346 Fix Source Sans Pro loading in storybook

util/isStatefulComponent.js
Added an extra conditional in isStatefulComponent helper function to avoid `Cannot read property render of undefined` error that I encountered while working with the Dropdown-component.
=> Added extra condition to isStatefulComponent-helper

CHANGELOG.md, lib/global.css, util/isStatefulComponent.js
https://issues.folio.org/browse/STCOM-348
=> STCOM-348 Change global base font size from 14px to 16px

docs/CSSinStripes.md, lib/Accordion/Accordion.css, lib/AddressFieldGroup/AddressEdit/AddressEdit.css, lib/AddressFieldGroup/AddressView/AddressView.css, lib/Badge/Badge.css, lib/Button/Button.css, lib/Checkbox/Checkbox.css, lib/Dropdown/Dropdown.css, lib/DropdownMenu/DropdownMenu.css, lib/IconButton/IconButton.css, lib/KeyValue/KeyValue.css, lib/LayoutHeader/LayoutHeader.css, lib/Modal/Modal.css, lib/ModalFooter/ModalFooter.css, lib/MultiSelection/MultiSelect.css, lib/NavListItem/NavListItem.css, lib/Pane/Pane.css, lib/Paneset/Paneset.css, lib/RadioButtonGroup/RadioButtonGroup.css, lib/Select/Select.css, lib/Selection/Selection.css, lib/Settings/Settings.css, lib/TextField/TextField.css, lib/sharedStyles/form.css, lib/variables.css
Standardizes all CSS variables to use `kebab-case` instead of `camelCase`.
This is definitely a breaking change - PR opened against `v4.0.0` branch.
=> Kebab case all css variables

index.js
Missed in https://github.com/folio-org/stripes-components/pull/641
=> Export RepeatableField

CHANGELOG.md, lib/EntrySelector/EntrySelector.js, translations/stripes-components/en.json
https://issues.folio.org/browse/STCOM-364
=> Add clone option to EntrySelector. Fixes STCOM-364

lib/MultiSelection/MultiSelect.css, lib/Select/Select.css, lib/Selection/SingleSelect.js, lib/TextArea/TextArea.css, lib/TextField/TextField.css, lib/sharedStyles/form.css, lib/sharedStyles/sharedInputStylesHelper.js, lib/variables.css
Should help to alleviate the specificity problems we've been experiencing with the `form.css` styles.
=> Decouple form element styles

CHANGELOG.md, lib/EntrySelector/EntrySelector.js
https://issues.folio.org/browse/STCOM-367
=> Add ability to filter items in EntrySelector. Fixes STCOM-367

lib/ConfirmationModal/ConfirmationModal.js, lib/Datepicker/Calendar.js, lib/Datepicker/Datepicker.js, lib/EntrySelector/EntrySelector.js, lib/MetaSection/MetaSection.js, lib/Modal/Modal.js, lib/MultiColumnList/MCLRenderer.js, lib/MultiColumnList/readme.md, lib/MultiSelection/MultiSelection.js, lib/MultiSelection/SelectedValuesList.js, lib/PaneHeader/PaneHeader.js, lib/Selection/SelectList.js, lib/Selection/SingleSelect.js, lib/TextField/TextField.js, lib/Timepicker/Timepicker.js
Matches conventions in https://github.com/folio-org/stripes-smart-components/pull/312
=> Always destructure intl

lib/Checkbox/Checkbox.css
Prevents checkboxes from becoming circular.
=> Updated border-radius on .labelCheck to 25% 

lib/EntrySelector/EntrySelector.js, translations/stripes-components/en.json
This PR adjusts the clonable/duplicate option based on the feedback from @filipjakobsen on https://issues.folio.org/browse/UIORG-117
=> Adjust clonable option. Part of STCOM-364

translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/es.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/pt_BR.json
=> Update translation strings as of 20181026T143111

lib/RadioButton/RadioButton.css
Requested by @filipjakobsen: https://issues.folio.org/browse/UIORG-115?focusedCommentId=38409&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-38409
=> Changed active radio button to white bg/black dot

lib/Badge/Badge.css, lib/variables.css
Updated --bg variable to #fff. 
Updated <Badge> default bg color to --color-fill.
=> Minor color variable changes

CHANGELOG.md, index.js
Not sure how this snuck by without being exported.
=> Export NavListItem

lib/Badge/Badge.css, lib/IconButton/IconButton.js
The conditional that determines whether or not to apply the "hasBadge" className needed to be updated since it wasn't working in some cases.
=> Minor icon button fix

lib/Button/Button.css
Updated disabled button color to `--color-text-p2` (62% black)
=> Updated <Button> disabled state to fix contrast ratio

README.md
Missed in https://github.com/folio-org/stripes-components/pull/696
Thanks @julianladisch for the spot.
=> Remove InjectIntl link from readme

lib/NavListSection/NavListSection.css, lib/NavListSection/NavListSection.js
The styling of the Headline in a NavListSection was a bit off. I made some minor changes in this PR.
=> Updated styling of Headline in NavListSection. Updated margins to rem.

CHANGELOG.md, lib/Callout/Callout.js
=> cancel Callout's timers on unmount

lib/ExportCsv/ExportCsv.js
Reverts folio-org/stripes-components#724
=> Revert "Stcom csv export"

lib/PasswordStrength/PasswordStrength.js
Same as https://github.com/folio-org/stripes-smart-components/commit/2172e85ae8880a4b17de3dbd8fbeafe2c549618b
=> UIU-689: Move PasswordStrength component to stripes-components.

CHANGELOG.md, lib/EntrySelector/EntrySelector.js
See https://github.com/folio-org/stripes-smart-components/pull/349
=> Deprecate EntrySelector

CHANGELOG.md, lib/MetaSection/MetaSection.js, lib/MetaSection/readme.md
https://issues.folio.org/browse/STCOM-357
Add `showUserLink` prop to `<MetaSection>`. Defaults to false.
=> STCOM-357 Introduce showUserLink prop on MetaSection

lib/Callout/Callout.js, lib/Callout/CalloutElement.js, lib/Callout/readme.md, lib/Callout/stories/BasicUsage.js, lib/Callout/stories/Callout.stories.js, lib/Callout/tests/Callout-test.js, lib/Callout/tests/interactor.js
We have some design changes coming for the `<Callout>` component so I added some examples and a few tests for it.
Still needs some work on the tests part but it's a start.
You can check out the example in the storybook draft here:
https://ux.folio.org/storybook-draft/?selectedKind=Callout
=> Add tests and examples for <Callout>

lib/NavList/NavList.js, lib/NavList/tests/NavList-test.js, lib/NavList/tests/interactor.js
The `handleNavigationClick` method and functionalty was not having any effect anymore so I removed 
it from the component and converted it to a functional component instead.
Added tests for the component as well. One step closer to 100% coverage 😀
=> Minor refactor and added tests for NavList

lib/global.css
Resolves https://issues.folio.org/browse/STCOM-412
=> STCOM-412 Change base font size to 100%

index.js
Forgot to include in https://github.com/folio-org/stripes-components/pull/772
=> STCOM-387 Export Pane link button components

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/es.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json
=> Update translation strings as of 20181228T143605

lib/Accordion/Accordion.css, lib/AutoSuggest/AutoSuggest.css, lib/Button/Button.css, lib/Callout/Callout.css, lib/EmptyMessage/EmptyMessage.css, lib/KeyValue/KeyValue.css, lib/List/List.css, lib/MultiColumnList/MCLRenderer.css, lib/NavListItem/NavListItem.css, lib/NavListSection/NavListSection.js, lib/PaneHeader/PaneHeader.css, lib/Select/Select.css, lib/TextArea/TextArea.css, lib/TextField/TextField.css, lib/sharedStyles/form.css
According to [STCOM-414](https://issues.folio.org/browse/STCOM-414), some font sizes should be changed
=> STCOM-414: adjust font sizes

lib/Select/Select.css
https://issues.folio.org/browse/STCOM-450
=> STCOM-450: Updated <Select> icon to ensure RTL compatibility

lib/Pane/Pane.js, lib/PaneHeader/PaneHeader.js
**Ticket:** https://issues.folio.org/browse/STCOM-405
**Note:** I did not remove the prop from `<EntrySelector>` since it will be removed in the next release anyway.
=> Removed actionMenuItems prop completely

CHANGELOG.md, package.json, yarn.lock
Cleans up:
```warning @folio/stripes-components > memoize-one@4.1.0: New custom equality api does not play well with all equality helpers. Please use v5.x```
=> Release v5.0.2

CHANGELOG.md, lib/MultiColumnList/MCLRenderer.css, lib/MultiColumnList/MCLRenderer.js
To be able to add `EndOfList` component when the user indeed have all the items scrolled to the bottom. The component is shows when the `totalCount` property is provided and greater or equal to the `contentData.length` value.
=> UIDATIMP-105: Add EndOfList component below the MLC component.

lib/Accordion/withAccordionSet.js
Reverts folio-org/stripes-components#881
A bug got introduced with this change. I'm reverting for now until I figure out how to fix this issue.
=> Revert "STCOM-475: Fix autogenerated ID's in withAccordionSet()"

lib/Popper/Popper.js, lib/Popper/readme.md, lib/Popper/stories/Popper.stories.js, lib/Popper/stories/PopperDemo.js, lib/Popper/tests/Popper-test.js, lib/Popper/tests/interactor.js, package.json, yarn.lock
https://issues.folio.org/browse/STCOM-370
Create a component with a basic mechanism for popups.
1) Create a component using 3-rd party library Popper.js
2) Create a storybook
3) Write tests
=> STCOM-370: Add popper component

lib/MenuSection/MenuSection.css
Minor update for MenuSection to ensure RTL compatibility.
=> Fix MenuSection RTL issue

CHANGELOG.md, lib/Datepicker/Datepicker.js, lib/Datepicker/tests/Datepicker-ReduxForm-test.js, lib/Datepicker/tests/Datepicker-test.js
=> STCOM-484 consider timezone when parsing datestring that includes an offset

README.md
I went looking for the documentation for these and couldn't find it until I did some detective work that should not really have been necessary. To save those who follow from going through the same dance, I added redundant entries to the contents table.
=> Add entries for <Col> and <Row>

lib/ExportCsv/exportToCsv.js, lib/ExportCsv/tests/ExportCSV-test.js, lib/ExportCsv/tests/export.json, lib/ExportCsv/tests/interactor.js
=> Export csv tests

lib/Datepicker/Datepicker.js, lib/Datepicker/tests/Datepicker-ReduxForm-test.js
Datepicker is now outputing an object with all the things `redux-form` expects to resolve a value from the midst of.
=> STCOM-494 Datepicker returning current date

lib/Icon/icons.js
**Ticket:** https://issues.folio.org/browse/STCOM-511
=> Added 'select-all' and 'deselect-all' icons

lib/Layout/styles/flexbox.css
Fixed some minor CSS declaration bugs in the `<Layout>`-component.
=> Fixed <Layout> align items classes

lib/Paneset/tests/Paneset-test.js
Every time. Srsly I do this every time.
=> don't call describe.only

lib/FilterGroups/FilterGroups.js, lib/FilterGroups/readme.md
original ticket
https://issues.folio.org/browse/UIOR-206
approach:
introduce new attributes to support ranges in cql, it shouldn't break current behavior
Documentation updated
=>  UIOR-206 range query support

CHANGELOG.md, lib/MultiColumnList/MCLRenderer.css
https://issues.folio.org/browse/STCOM-530
https://issues.folio.org/browse/UIIN-512
=> STCOM-530: Fix blocking scrollbars in MultiColumnList

index.js, lib/CurrencySelect/CurrencySelect.js, lib/CurrencySelect/index.js, lib/CurrencySelect/tests/CurrencySelect-test.js, lib/CurrencySelect/tests/interactor.js, package.json, util/currencies.js
Refs [STSMACOM-205](https://issues.folio.org/browse/STSMACOM-205)
=> implement currency select menu

CHANGELOG.md, lib/Modal/Modal.js, lib/Modal/tests/Modal-test.js
https://issues.folio.org/browse/STCOM-460
=> STCOM-460: Fixed "closeOnBackgroundClick" behaviour for <Modal> 

lib/Button/Button.css
Loans ellipsis menu has different styling for some linked text.
=> STCOM-496: Change styles.

index.js
Realised I forgot to do this literally as I merged the PR... 🤦‍♂
=> Export Card component from top-level

CHANGELOG.md, lib/CurrencySelect/tests/CurrencySelect-test.js, util/currencies.js
Refs [UIU-1076](https://issues.folio.org/browse/UIU-1076)
=> UIU-1076 exclude additional currencies

lib/Icon/icons.js
=> Add 'combine'-icon

CHANGELOG.md, lib/Accordion/ExpandAllButton.js
It'd be nice from a testing POV to be able to target this button directly!
=> ExpandAllButton accepts id prop

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/zh_CN.json
=> Update translation strings as of 20190718T013203

translations/stripes-components/zh_CN.json
=> Update translation strings as of 20190718T220243

lib/KeyValue/KeyValue.js, lib/KeyValue/tests/KeyValue-test.js, lib/KeyValue/tests/interactor.js
Increase KeyValue testing coverage to 80%
https://issues.folio.org/browse/STCOM-524
=> STCOM-524 - Increase stripes-components|key value testing to 80%

lib/Accordion/Accordion.js, lib/Accordion/tests/Accordion-test.js
To increase coverage for Accordion component.
Seems we have duplicated code which can be refactored in order to increase coverage up to 87%
https://issues.folio.org/browse/STCOM-526
=> STCOM-526 - increased coverage for Accordion smart component

lib/AutoSuggest/AutoSuggest.js
To be able pass down callback with selected item
https://github.com/downshift-js/downshift#onselect
I'm going to use it in redux-form's `FieldArray`
=> UIORGS-71 pass down `onSelect` prop

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/zh_CN.json
=> Update translation strings as of 20190807T131714

lib/Headline/tests/Headline-test.js
test coverage should increase now...
=> Remove 'only' from Headline tests

lib/Selection/SelectList.js, lib/Selection/tests/SingleSelection-test.js, lib/Selection/tests/interactor.js
In this PR, I deleted unused code and added more tests to increase SelectList test coverage.
=> STCOM-525: Increase SelectList test coverage to 80%

translations/stripes-components/it_IT.json
=> Update translation strings as of 20190823T083240

translations/stripes-components/ar.json
=> Update translation strings as of 20190828T124751

lib/PasswordStrength/tests/interactor.js, lib/PasswordStrength/tests/password-strength-test.js
https://issues.folio.org/browse/STCOM-556
=> STCOM-556: Add tests for password strength component.

translations/stripes-components/ar.json
=> Update translation strings as of 20191004T135530

translations/stripes-components/es_ES.json
=> Update translation strings as of 20191104T173556

index.js, lib/MultiColumnList/readme.md, lib/Spinner/Spinner.js, lib/Spinner/index.js
This is a simple copy-job, so my non-ERM app doesn't have to include stripes-erm-components.
=> Add <Spinner> from stripes-erm-components

translations/stripes-components/ru.json
=> Update translation strings as of 20191115T154823

translations/stripes-components/fr_FR.json
=> Update translation strings as of 20191127T181804

translations/stripes-components/it_IT.json, translations/stripes-components/zh_CN.json
=> Update translation strings as of 20191203T022312

lib/Dropdown/Dropdown.js
This was causing an ESLint error, the only one in the repository.
=> Remove unused import of lodash/isBoolean

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200106T223901

lib/Pane/readme.md, lib/Pane/stories/Pane.stories.js, lib/PaneSubheader/PaneSubheader.css, lib/PaneSubheader/stories/PaneSubheaderExample.js
Along with some style adjustments.
The look so far:
=> Add story for PaneSubheader

translations/stripes-components/fr_FR.json
=> Update translation strings as of 20200117T173544

index.js
Noticed these weren't being exported from the top-level.
=> Export Loading components

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200202T214053

translations/stripes-components/es_419.json, translations/stripes-components/it_IT.json
=> Update translation strings as of 20200203T164535

CHANGELOG.md, lib/Card/Card.css, lib/Card/Card.js, lib/Card/readme.md, lib/Card/stories/BasicUsage.js, lib/Card/tests/Card-test.js, lib/Card/tests/interactor.js
- Added deprecation warning for `hasMargin` prop
- Added the `marginBottom0` prop to remove the margin bottom if needed
- Handle tests
- CHANGELOG
=> Add spacing between the Cards by default, refs STCOM-626

translations/stripes-components/ar.json, translations/stripes-components/fr_FR.json
=> Update translation strings as of 20200217T172736

translations/stripes-components/ar.json
=> Update translation strings as of 20200224T151433

translations/stripes-components/ru.json
=> Update translation strings as of 20200312T133304

translations/stripes-components/fr_FR.json
=> Update translation strings as of 20200316T134017

translations/stripes-components/ru.json
=> Update translation strings as of 20200319T202257

lib/NavList/NavList.js, lib/NavListItem/NavListItem.js, lib/NavListSection/NavListSection.js
I needed to add a ref for a `<NavListSection>` for an update in stripes-core and decided to add the option for all 3 of the NavList-related components.
=> Added forwardRef for NavList, NavListItem and NavListSection

lib/MultiSelection/MultiSelect.css
Settings>Users>Fee/Fine Owner: Associated Service Point that has a long name overpaps `Save`, `Cancel` buttons 
https://issues.folio.org/browse/UIU-1537
**Before**
**After**
=> UIU-1537: Change style

lib/FilterGroups/FilterGroups.js
https://issues.folio.org/browse/STCOM-583
Couldn't reproduce, but I've got my suspects... shoring up some better practices here. We can re-open if it shows up again....
=> STCOM-583 key using name-index or group-index combination

translations/stripes-components/ja.json
=> Update translation strings as of 20200421T180634

translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200428T150732

translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200505T210535

CHANGELOG.md, lib/Selection/DefaultOptionFormatter.js, lib/Selection/OptionSegment.js, lib/Selection/tests/DefaultOptionFormatter-test.js, lib/Selection/tests/SingleSelection-test.js, lib/Selection/tests/interactor.js
https://issues.folio.org/browse/STCOM-668
=> STCOM-668 Increase test coverage to 80% | Selection

CHANGELOG.md, lib/DropdownMenu/DropdownMenu.js, lib/DropdownMenu/tests/DropdownMenu-test.js
https://issues.folio.org/browse/STCOM-667
=> STCOM-667 Increase test coverage to 80% | Dropdown menu

lib/Modal/Modal.css
Reduce distance from top of the page (from `100px` to `50px`) for `large` modal
**Before**
**After**
=> Fix modal layout

translations/stripes-components/ru.json
=> Update translation strings as of 20200609T205925

lib/MultiSelection/MultiSelection.js
https://issues.folio.org/browse/UIOR-522
Accessibility Error: ARIA attributes must conform to valid values
=> UIOR-522 fix aria-owns attribute value

lib/SearchField/SearchField.js, translations/stripes-components/en.json
https://issues.folio.org/browse/UIOR-524
Accessibility Error: Form elements must have labels
=> UIOR-524 add aria-label to search index select

CHANGELOG.md, index.js, lib/CountrySelection/CountrySelection.js, lib/CountrySelection/index.js, lib/CountrySelection/tests/CountrySelection-test.js
Provide a country-picker component.
Refs [STCOM-291](https://issues.folio.org/browse/STCOM-291)
=> STCOM-291 implement CountrySelection

CHANGELOG.md, lib/CurrencySelect/CurrencySelect.js, lib/CurrencySelect/tests/CurrencySelect-test.js
Fixes [STCOM-614](https://issues.folio.org/browse/STCOM-614)
=> STCOM-614 localize currency values

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/ur.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200618T161121

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/ur.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200623T182030

CHANGELOG.md, lib/Selection/SelectList.js, lib/Selection/tests/SingleSelection-test.js, lib/Selection/tests/interactor.js
**Ticket:**
https://issues.folio.org/browse/STCOM-702
**Changes:**
remove `role="listbox"` for `<input>` as no needed
add `role="combobox"`, aria-controls, aria-expanded
=> STCOM-702 Accessibility Error: ARIA role must be appropriate for the element (Selection)

lib/FocusLink/FocusLink.js, lib/FocusLink/tests/FocusLink.js, lib/FocusLink/tests/interactor.js, package.json
https://issues.folio.org/browse/STCOM-669
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify …
=> STCOM-669 Increase test coverage to 80% | Focus link

lib/MultiSelection/MultiSelect.css, lib/MultiSelection/MultiSelectFilterField.js, lib/MultiSelection/MultiSelectValueInput.js, lib/MultiSelection/MultiSelection.js, lib/MultiSelection/tests/MultiSelection-test.js, lib/MultiSelection/tests/interactor.js
Correctly present validation error for `<MultiSelection>` component if it has no value and disable `Save&Close` button
Refs STCOM-715
=> STCOM-715 Correct validation for User Record Custom Fields MultiSelection

CHANGELOG.md, hooks/useCurrencyOptions/index.js, hooks/useCurrencyOptions/useCurrencyOptions.js, index.js, lib/CurrencySelect/CurrencySelect.js
we have to leverage logic piece into a reusable hook and export it, so currency options could be easily imported in any module from one place.
=> STCOM-614 leverage currency options to a hook for re-use

CHANGELOG.md, lib/Editor/tests/Editor.js
https://issues.folio.org/browse/STCOM-660
=> STCOM-660 Increase test coverage to 80% | Editor

translations/stripes-components/zh_CN.json
=> Update translation strings as of 20200721T202356

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/ur.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200723T031126

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/ur.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200804T124827

lib/Datepicker/Datepicker.js, lib/Datepicker/tests/Datepicker-ReduxForm-test.js, lib/Datepicker/tests/Datepicker-test.js
Fixes a bug where the datepicker input goes blank after tabbing out of it... redux-form's blur-handling (calling a change handler, what?) is to blame... 🙄
=> Datepicker patch 3

CHANGELOG.md, lib/Datepicker/Calendar.js, lib/Label/components/Asterisk/Asterisk.js
[[STCOM-741]](https://issues.folio.org/browse/STCOM-741) Label: Asterisk in required labels is read by screen reader
Asterisk in required labels was read by screen reader.
=> [STCOM-741] Label: Asterisk in required labels is read by screen reader

translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json
=> Update translation strings as of 20200901T173106

lib/NavList/readme.md
Updating the example code to reflect react-router v5 best practices.
=> update example per react-router v5

CHANGELOG.md, lib/Selection/SingleSelect.js, lib/Selection/utils.js
purpose: https://issues.folio.org/browse/STCOM-709 componentWillReceiveProps is deprecated
approach: getDerivedStateFromProps is used
approach is not ideal because component itself should be reimplemented, memoization is more suitable approach here, but can't be used
=> STCOM-709 refactor SingleSelect away from componentWillReceiveProps

CHANGELOG.md, lib/SRStatus/SRStatus.js
purpose: https://issues.folio.org/browse/STCOM-708 componentWillReceiveProps is deprecated
approach: componentDidUpdate is used
=> STCOM-708 Refactor SRStatus away from componentWillReceiveProps

lib/Accordion/headers/DefaultAccordionHeader.js
Related to [UIEH-923](https://issues.folio.org/browse/UIEH-923)
Fixed passed props not being added to elements in `DefaultAcordionHeader`
=> UIEH-923 Added additional props to DefaultAcordionHeader

translations/stripes-components/zh_CN.json
=> Update translation strings as of 20200928T202231

translations/stripes-components/ar.json, translations/stripes-components/ca.json, translations/stripes-components/da.json, translations/stripes-components/de.json, translations/stripes-components/en_GB.json, translations/stripes-components/en_SE.json, translations/stripes-components/en_US.json, translations/stripes-components/es.json, translations/stripes-components/es_419.json, translations/stripes-components/es_ES.json, translations/stripes-components/fr.json, translations/stripes-components/fr_FR.json, translations/stripes-components/he.json, translations/stripes-components/hi_IN.json, translations/stripes-components/hu.json, translations/stripes-components/it_IT.json, translations/stripes-components/ja.json, translations/stripes-components/ko.json, translations/stripes-components/pl.json, translations/stripes-components/pt_BR.json, translations/stripes-components/pt_PT.json, translations/stripes-components/ru.json, translations/stripes-components/ur.json, translations/stripes-components/zh_CN.json, translations/stripes-components/zh_TW.json
=> Update translation strings as of 20200930T202600

CHANGELOG.md, lib/SearchField/SearchField.js, lib/SearchField/tests/SearchField-test.js, lib/SearchField/tests/interactor.js
https://issues.folio.org/browse/STCOM-762
Focus does not move to search bar when plugin is opened
=> STCOM-762 Focus does not move to search bar

CHANGELOG.md, lib/Timepicker/Timepicker.js, lib/Timepicker/tests/Timepicker-test.js
purpose: https://issues.folio.org/browse/STCOM-275
approach: replace `componentWillReceiveProps` with `getDerivedStateFromProps`
=> STCOM-275 Refactor  away from  lifecycle hook

CHANGELOG.md, lib/Callout/Callout.css, lib/Callout/CalloutElement.js, lib/Callout/tests/Callout-test.js, lib/Callout/tests/interactor.js
Implement info callout in the scope of the [STCOM-776](https://issues.folio.org/browse/STCOM-776).
=> STCOM-776: Implement info callout

translations/stripes-components/fr_FR.json, translations/stripes-components/it_IT.json
=> Update translation strings as of 20201111T142927

lib/Checkbox/tests/Checkbox-test.js, lib/Select/tests/Select-test.js, lib/Tooltip/tests/Tooltip-test.js
See https://github.com/folio-org/stripes-testing/pull/84
=> STCOM-7875 Use all the interactors on stripes-components#new-bigtest-interactors

CHANGELOG.md, lib/Select/Select.js
- add inputRef
- add explicit aria-labelledby after possible labels'
=> UITEN-119 make Select tooltip-ready

lib/Layer/tests/Layer-test.js, lib/Layer/tests/LayerHarness.js
Layer is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785 that appears in almost every application. Depends on folio-org/stripes-testing#87.
=> STCOM-785: interactors update: layer

lib/Pane/tests/Pane-test.js
Pane is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785 that appears in almost every application. Depends on folio-org/stripes-testing#83.
=> STCOM-785: interactors update: pane

lib/TextArea/TextArea.js, lib/TextArea/tests/TextArea-ReduxForm-test.js, lib/TextArea/tests/TextArea-test.js
`TextArea` is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785.
Depends on: https://github.com/folio-org/stripes-testing/pull/91
Consumed the new interactor and migrated all assertions to the new api.
=> STCOM-785: interactors update: textarea

lib/Dropdown/tests/dropdown-test.js
`Dropdown` is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785.
Depends on: https://github.com/folio-org/stripes-testing/pull/94
Consumed the new interactor and migrated all assertions to the new api.
=> STCOM-785: interactors update: dropdown

README.md, lib/Callout/readme.md
* Add note to `<Callout>` doc explaining that you probably want `<CalloutContext>`
* Add `<Loading>` and related components to front-page index
=> Minor documentation improvements

.gitignore, CHANGELOG.md, lib/Callout/Callout.css, lib/Callout/CalloutElement.js, lib/Callout/readme.md, lib/Callout/stories/BasicUsage.js, lib/Callout/tests/Callout-test.js, lib/Callout/tests/interactor.js
https://issues.folio.org/browse/STCOM-809
Adding Callout type `warning` , like in MessageBanner, same style
=> STCOM-809 Implement warning callout

lib/RepeatableField/tests/RepeatableField-test.js
https://issues.folio.org/browse/STCOM-787
=> STCOM-787 add test with custom delete

lib/ErrorBoundary/components/ProductionError/ProductionError.js, lib/MultiSelection/MultiSelection.js
- usage of <FormattedMessage> with function as a child https://formatjs.io/docs/react-intl/components/#function-as-the-child
- usage of <FormattedMessage> where only string is accepted
=> STCOM-810 fix JS console errors

README.md
_Two_ people have now pinged #stripes about whether a component like this exists and mentioned it wasn't in the TOC 😞 
Time to right that.
=> README: Added ButtonGroup to list of components

CHANGELOG.md, index.js, lib/Datepicker/Datepicker.js, lib/Datepicker/index.js
https://issues.folio.org/browse/STCOM-854
=> STCOM-854 Expose getLocalFormat Datepicker util

lib/MultiColumnList/tests/MultiColumnList-test.js
Finished off the MultiColumnList, and opening a new PR due to permission considerations.
Original PR: https://github.com/folio-org/stripes-components/pull/1481
MultiColumnList is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785.
Depends on: folio-org/stripes-testing#95
Consumed the new interactor and migrated all assertions to the new api.
=> STCOM-785: interactors update: MultiColumnList (part 2)

lib/Datepicker/tests/Datepicker-ReduxForm-test.js, lib/Datepicker/tests/Datepicker-test.js
Datepicker is one of the critical path interactors listed in https://issues.folio.org/browse/STCOM-785.
Depends on: folio-org/stripes-testing#99
Consumes the new interactor and migrated all assertions to the new api.
=> STCOM-785: interactors update: datepicker

lib/AutoSuggest/AutoSuggest.js, lib/AutoSuggest/tests/AutoSuggest-test.js, lib/Avatar/tests/Avatar-test.js, lib/IconButton/tests/IconButton-test.js, lib/RepeatableField/tests/RepeatableField-ReduxForm-test.js, lib/RepeatableField/tests/RepeatableField-test.js
Update tests for
- AutoSuggest
- Avatar
- Badge (IconButton tests)
- RepeatableField
Using new interactors from `@folio/stripes-testing`
=> STCOM-886 autosuggest avatar badge interactors

lib/Accordion/Accordion.css
Added text-align property to label area of accordion headers.
resolves [STCOM-893](https://issues.folio.org/browse/STCOM-893)
=> STCOM-893 text alignment of accordion headers.

lib/RadioButton/tests/RadioButton-ReduxForm-test.js
Fix tests in `b10.0` branch by following https://github.com/folio-org/stripes-components/pull/1630 example
=> Fix Radibutton Redux Form tests

lib/MultiColumnList/readme.md, lib/Pane/readme.md
Add description of totalCount prop.
=> Update MCL readme

CHANGELOG.md, index.js, lib/ConflictDetectionBanner/ConflictDetectionBanner.css, lib/ConflictDetectionBanner/ConflictDetectionBanner.js, lib/ConflictDetectionBanner/index.js, lib/ConflictDetectionBanner/readme.md, lib/ConflictDetectionBanner/tests/ConflictDetectionBanner-test.js, lib/ConflictDetectionBanner/tests/interactor.js, lib/TextLink/tests/interactor.js, translations/stripes-components/en.json
Created a Conflict Detection banner which will be displayed when a conflict due to optimistic locking occurs.
Issue: [STCOM-889](https://issues.folio.org/browse/STCOM-889)
=> STCOM-889: Create a Conflict Detection banner

index.js
Exposed nativeChangeFieldValue for those wishing to create stripes form components
=> feat: nativeChangeFieldValue

lib/LayoutHeader/LayoutHeader.js
Adds a valid label to the Edit Icon button that's presented in the `<LayoutHeaders>` rendered by AddressList and AddressView
=> STSMACOM-608 AddressList components update (Testing)

package.json
In a previous PR, was replaced with a github branch... this PR restores.
=> Use version for stripes-testing dependency.

lib/LayoutHeader/readme.md
Specify the correct shape of the `actions` array's objects.
Refs [STCOM-914](https://issues.folio.org/browse/STCOM-914)
=> STCOM-914 correct LayoutHeader documentation

lib/Select/Select.js
https://issues.folio.org/browse/STCOM-925
=> STCOM-925 restore Select `multiple` prop support

lib/NavListSection/NavListSection.js, lib/Select/Select.js
HI, @zburke! In scope of my task I need to replace DIV for General, Fee/Fine, Patron blocks with H3 tag. So, in NavListSection I added tag prop to Headline component. What do you think about this change? Can we apply it for my task? 
Ref: https://issues.folio.org/browse/UIU-2037
=> STCOM-929 NavListSection should accept a tag prop

CHANGELOG.md, lib/KeyValue/tests/KeyValue-test.js, lib/NoValue/NoValue.js, lib/NoValue/tests/NoValue-test.js, lib/NoValue/tests/interactor.js
purpose: https://issues.folio.org/browse/STCOM-936
axe reports many issues when NoValue component is displayed
=> STCOM-936 NoValue component doesn't have role

CHANGELOG.md, lib/Timepicker/TimeDropdown.css, lib/Timepicker/Timepicker.js, lib/Timepicker/readme.md
=> STCOM-969 - re-up of #1767

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Refs [STCOM-996](https://issues.folio.org/browse/STCOM-996)
=> STCOM-996 bump CI node version to 16

CHANGELOG.md, lib/Paneset/Paneset.css, lib/Paneset/Paneset.js, lib/Paneset/tests/Paneset-test.js
* [STCOM-988](https://issues.folio.org/browse/STCOM-988)
* [STCOM-989](https://issues.folio.org/browse/STCOM-989)
* [STCOM-984](https://issues.folio.org/browse/STCOM-984)
* [STCOM-982](https://issues.folio.org/browse/STCOM-982)
* [STCOM-983](https://issues.folio.org/browse/STCOM-983)
* [STCOM-987](https://issues.folio.org/browse/STCOM-987)
=> Uncle johns big paneset party

CHANGELOG.md, lib/Tooltip/Tooltip.js
https://issues.folio.org/browse/STCOM-979
=> STCOM-979 properly provide popper placements

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
Refs [STCOM-996](https://issues.folio.org/browse/STCOM-996)
=> STCOM-996 update NodeJS to active LTS, v16

CHANGELOG.md, translations/stripes-components/zh_TW.json
Refs [STCOM-1003](https://issues.folio.org/browse/STCOM-1003)
=> STCOM-1003 include recent zh-TW translations

CHANGELOG.md, lib/MetaSection/tests/MetaSection.test.js, translations/stripes-components/en.json
https://issues.folio.org/browse/STCOM-882
=> STCOM-882 Additional functionality needed for metadata display when user record is deleted

package.json
New interactors added in 4.3.0 are leveraged in tests.
=> bump stripes-testing to 4.3.0

lib/CountrySelection/tests/CountrySelection-test.js, lib/CurrencySelect/tests/CurrencySelect-test.js
Ongoing effort to reduce usage of old bigtest in stripes-components' tests.
=> CountrySelect and currencySelect tests upgrade interactor

lib/DateRangeWrapper/tests/DateRangeWrapper-ReduxForm-test.js, lib/DateRangeWrapper/tests/DateRangeWrapper-test.js
Continued bigtest interactor upgrade: DateRangeWrapper...
=> Upgrade interactors on Daterangewrapper tests

lib/ConflictDetectionBanner/tests/ConflictDetectionBanner-test.js, lib/CurrencySelect/tests/CurrencySelect-test.js
Ongoing effort to reduce old bigtest interactors in test suite.
=> upgrade to use new bigtest interactors

lib/ConfirmationModal/tests/ConfirmationModal-test.js
Will be green as soon as https://github.com/folio-org/stripes-testing/pull/463 is merged...
=> import confirmation modal interactor from stripes-testing

lib/Editor/tests/Editor.js
Ongoing test upgrade to new interactors.
=> implement new Editor interactor

util/dateTimeUtils.js
necessary for merging of https://github.com/folio-org/stripes-components/pull/1881
=> Obligatory Datetimeutils time format doc fix

CHANGELOG.md, lib/RadioButton/RadioButton.css, lib/RadioButton/RadioButton.js, lib/RadioButton/readme.md
[STCOM-1065](https://issues.folio.org/browse/STCOM-1065)
=> STCOM-1065: Add 'centered' property to the 'RadioButton' component

lib/MultiColumnList/stories/CheckboxSelect.js, lib/MultiColumnList/stories/StickyColumns.js, lib/MultiColumnList/stories/service.js
Updates the sticky columns storybook story as well as the checkbox selection story of MCL to improve the presentation of the feature.
=> update sticky columns story, checkbox select

lib/Paneset/PaneResizeContainer.js
PaneResizeContainer: parentElement prop to instanceOf(Element)
=> STCOM-1085 Proptype validation issue

CHANGELOG.md, lib/KeyValue/KeyValue.css, lib/KeyValue/readme.md
[STCOM-1097](https://issues.folio.org/browse/STCOM-1097)
[UIDATIMP-1342](https://issues.folio.org/browse/UIDATIMP-1342)
=> STCOM-1097: Add line break at newline characters in KeyValue component

lib/MultiColumnList/LoadMorePaginationRow.js, lib/MultiColumnList/PrevNextPaginationRow.js
https://issues.folio.org/browse/STCOM-1114
=> STCOM-1114 remove roles from pagination elements

CHANGELOG.md, lib/Select/stories/BasicUsage.js
Ticket: [STCOM-1121](https://issues.folio.org/browse/STCOM-1121).
Target: Add example of using `Select` with optgroups.
Example:
=> STCOM-1121: Spike - create optgroup component

lib/MultiColumnList/readme.md
=> Fix MCL documentation error

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json, translations/stripes-components/de.json
How did we miss this in stripes-*??!?!!!?!?!?!
Refs [STCOM-1162](https://issues.folio.org/browse/STCOM-1162)
=> STCOM-1162 compile translations

CHANGELOG.md, lib/Icon/icons/graph.svg
Added a new `graph` icon
[STCOM-1187](https://issues.folio.org/browse/STCOM-1187)
=> STCOM-1187 Added graph icon

CHANGELOG.md, lib/MultiColumnList/MCLRenderer.js
[STCOM-1196](https://issues.folio.org/browse/STCOM-1196)
* When array is sparse focus index starts with `this.focusTargetIndex`
* When array is non-sparse, set focusIndex to 0
=> STCOM-1196: Adjust scroll position to the top for non-sparse array

CHANGELOG.md
Refs [STCOM-1215](https://issues.folio.org/browse/STCOM-1215), [FOLREL-584](https://issues.folio.org/browse/FOLREL-584)
=> Release v12.0.0

lib/Loading/readme.md, lib/Spinner/README.md
Improves the README of the Loading components by specifically documenting props and example usage.
=> Improve Loading components documentation

CHANGELOG.md, lib/CurrencySelect/tests/CurrencySelect-test.js, util/currencies.js
https://folio-org.atlassian.net/browse/STCOM-1274
Exclude invalid Uruguayan additional currencies
=> STCOM-1274: Exclude invalid additional currencies

CHANGELOG.md, translations/stripes-components/en.json
New "Save & keep editing" is needed for Inventory app
[UIIN-2457](https://folio-org.atlassian.net/browse/UIIN-2457)
=> STCOM-1296 Add a "Save & keep editing" translation

.github/workflows/build-storybook.yml
Bump build-storybook actions for compatibility with Sunflower, i.e. use NodeJS v20.
Refs [STCOM-1407](https://folio-org.atlassian.net/browse/STCOM-1407)
=> STCOM-1407 bump build-storybook workflow versions

CHANGELOG.md, lib/AutoSuggest/AutoSuggest.js, lib/MessageBanner/MessageBanner.js, lib/MessageBanner/readme.md, lib/MessageBanner/stories/ShowHide.js, lib/MessageBanner/tests/MessageBanner-test.js, lib/MultiSelection/MultiSelectOptionsList.js, lib/MultiSelection/MultiSelection.js, lib/Selection/Selection.js, lib/Timepicker/TimeDropdown.js
https://folio-org.atlassian.net/browse/STCOM-1398
Here we removed *deprecated* props for components
=> STCOM-1398: *BREAKING* remove deprecated props

lib/AuditLog/tests/AuditLogChangedFieldsList-test.js, lib/AuditLog/tests/AuditLogModal-test.js
Main story PR - https://github.com/folio-org/stripes-components/pull/2433
=> STCOM-1412 Tests for AuditLogChangedFieldsList and AuditLogModal
